const listaMedalla = {
  b1: {name: '🎮 Go MeD', info:'Tienes 1 año o mas en el team'},
  b2: {name: '💰 Quédate el cambio', info: 'Has donado 10m o mas al banco del team de una sola vez'},
  b3: {name: '🧩 Pieza clave', info: 'Formas parte de los miembros fundadores del team'},
  b4: {name: '👑 Dictador', info: 'Has sido líder de MeD'},
  b5: {name: '💂 Guardián', info: 'Has kickeado a alguien de MeD'},
  b6: {name: '🧘 Cuerpo y mente', info: 'Has obtenido un shiny Meditite'},
  b7: {name: '🎲 De vida o muerte', info: 'Has capturado un shiny en la Zona Safari'},
  b8: {name: '🗺️ Tour por el mundo', info: 'Has obtenido un shiny de swarm'},
  b9: {name: '💔 Desafortunado', info: 'Has perdido un shiny durante un encuentro'},
  b10: {name: '🌟 Top secret', info: 'Has obtenido un shiny secret (salvaje)'},
  b11: {name: '📆 Shunter del mes', info: 'Has capturado la mayor cantidad de shinys en un mes'},
  b12: {name: '🎣 Maestro pescador', info: 'Has obtenido un shiny pescando'},
  b13: {name: '🥇 Race winner', info: 'Has ganado una shiny race'},
  b14: {name: '🥈 Fail race', info: 'Has obtenido una fase buscando el shiny de la race'},
  b15: {name: '🍀 Suertudo', info: 'Has obtenido 2 o mas shiny en 1 día (24h o menos)'},
  b16: {name: '💫 Enrachado', info: 'Has obtenido un shiny en 3 o mas días seguidos'},
  b17: {name: '🛐 El elegido', info: 'Has obtenido un shiny alpha o legendario'},
  b18: {name: '👴 Paciencia de abuelo', info: 'Has obtenido 3 o mas fases buscando un shiny'},
  b19: {name: '🧬 Raza perfecta', info: 'Has obtenido un shiny por crianza'},
  b20: {name: '❔Misterio resuelto', info: 'Has obtenido un shiny de una Ball Misteriosa'},
  b21: {name: '🦖Arqueólogo', info: 'Has obtenido un fósil shiny'},
  b22: {name: '🌳Arborista', info: 'Has obtenido un shiny de golpe cabeza/árbol de miel'},
  b23: {name: '📦 Golden box', info: 'Has obtenido una caja llena (60) de shinys'},
  b24: {name: '👿 Pecador', info: 'Has vendido, liberado o regalado un shiny'},
  b25: {name: '🎀 Shiny completo', info: 'Has obtenido un shiny que posee todas las cintas'},
  b26: {name: '📝Apóstol', info: 'Has registrado una nueva especie en la Shiny Dex de MeD'},
  b27: {name: '🎫 Built different', info: 'Has obtenido un shiny ganando un torneo o evento oficial'},
  b28: {name: '🌱 MeD Supremacy 1', info: 'Formaste parte del equipo ganador de la MeD Supremacy 1'},
  b29: {name: '🏆 Winners PokeLympics 2024', info: 'Formaste parte del equipo ganador de las PokeLympics 2024'},
  b30: {name: '🅿️ MeD Supremacy 2', info: 'Formaste parte del equipo ganador de la MeD Supremacy 2'},
  b31: {name: '🎉 AniMeDsario 2025', info: 'Formaste parte de los ganadores del evento del AniMeDsario 2025'}
};

const memberData = {
        AdrixJK: {      name:'AdrixJK',
                        rol: 'Chad',
                        medallas:['b9','b10','b15','b24','b26'],
                        shinys:['torkoal'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/farfetchd.gif'],
                        vendidos: []
        },
        aeamanh: {      name:'aeamanh',
                        rol: 'MaxiChad',
                        medallas:['b10','b14','b15','b26','b29'],
                        shinys:['donphan','sandslash','scolipede','raticate','tangrowth','spinda','raticate','magneton','mienfoo','frillish-f','smeargle','nidoking','ditto','grimer',
                                'chandelure','leavanny','primeape','ditto','deino','snover','bibarel','quagsire','bellossom','weezing','durant','cryogonal','rapidash','pelipper','altaria',
                                'politoed','duskull','duosion','mightyena','gliscor','gyarados','amoonguss'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/gulpin.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/pansage.gif',
                                'https://media.giphy.com/media/ELEoC52RYPBnz8Vf4s/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/vxRM9XurU5lvpae8Ko/giphy.gif']
        },
        AkaliWard: {    name:'AkaliWard',
                        rol: 'Chad',
                        medallas:['b1','b4','b5','b12','b14','b15','b24','b26'],
                        shinys:['tyranitar','horsea','duskull','mienshao','sharpedo','ninetales','poochyena','beedrill','cottonee','slugma','wooper','azumarill','gyarados','shinx','snorunt',
                                'weavile','axew','pachirisu','lanturn','cottonee','torkoal','gible','jumpluff','weezing','bibarel'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/gulpin.gif'],
                        vendidos: ['https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZW54bXF1OWhocTF3cHMzd3lyMmd2MW5xdTFpNWxucmRkbjlhcjI2ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHBxbzBvM2k5OGFpZXJsMHQ4dzk5NGxteW42NXk3N3IyNjEwaXNnYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ubXLD0w80oZjtsrIUH/giphy.gif',
                                'https://media.giphy.com/media/PMMrLwzj3iqyMtpxQs/giphy.gif',
                                'https://media.giphy.com/media/A2NlfU2OIPj0GAVoJy/giphy.gif',
                                'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXY3dXh2MnNsZHQyYjNzdHE3MmpqMnI5dnoxeDU1cW40cTAyMmc3NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ptSTYVxdNLH5oH4Siw/giphy.gif'
                        ]
        },
        AlexisBlu: {    name:'AlexisBlu',
                        rol: 'MegaChad',
                        medallas:['b19','b21','b26','b29'],
                        shinys:['haxorus','weavile','camerupt','gyarados','swoobat','zigzagoon','cubone'],
                        destacados:['https://media.giphy.com/media/kI6DHEnVibteJcUDtY/giphy.gif',
                                'https://media.giphy.com/media/sP3E4z0rFHUtZ7gd9x/giphy.gif'],
                        vendidos: []
        },
        AshbellUwU: {   name:'AshbellUwU',
                        rol: 'GigaChad',
                        medallas:['b10','b12','b30'],
                        shinys:['drifblim','dratini','raticate','gardevoir','duskull','marill','smeargle','scolipede','zangoose','staravia','bellossom','gloom','lanturn','golett'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/carvanha.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/breloom.gif',
                                'https://media.giphy.com/media/4fOM1fIVBlAM7xh90c/giphy.gif'
                        ],
                        vendidos: []
        },
        Azathotxv: {    name:'Azathotxv',
                        rol: 'Chad',
                        medallas:['b8','b14','b26','b29'],
                        shinys:['lotad','cacnea','dustox','cinccino','bidoof','mismagius','gastrodon','mienfoo','spinda','venomoth','vanillish','golduck','camerupt','boldore','dugtrio',
                                'smeargle','dusclops','weezing','parasect','scolipede','beedrill'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/kecleon.gif',
                                'https://media.giphy.com/media/ggxHTXdRvXKT0VgZ1V/giphy.gif'
                        ],
                        vendidos: []
        },
        CeceMerdosa: {  name:'CeceMerdosa',
                        rol: 'MaxiChad',
                        medallas:['b4','b6','b30'],
                        shinys:['sneasel','meditite','luxio','girafarig','wingull','magmar','deerling','golett'],
                        destacados:[],
                        vendidos: []
        },
        Cenoa: {        name:'Cenoa',
                        rol: 'Chad',
                        medallas:['b17','b26','b30'],
                        shinys:['drifblim','donphan'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/totodile.gif',
                                'https://media.giphy.com/media/da60GIUj74BHRR9Px5/giphy.gif'
                        ],
                        vendidos: []
        },
        DavidCitos: {   name:'DavidCitos',
                        rol: 'Chad',
                        medallas:['b10','b11','b15','b16','b18','b23','b26','b28','b29','b30'],
                        shinys:['lopunny','marill','trapinch','roserade','vulpix','hydreigon','magmar','poliwag','swablu','meowth','gyarados','grimer','weezing','weavile','pikachu','psyduck','mareep','miltank',
                                'litwick','duskull','jigglypuff','electabuzz','rapidash','natu','wobbuffet','accelgor','banette','sealeo','vanilluxe','ferroseed','woobat','poliwhirl','parasect','magnezone','hoppip',
                                'mienfoo','rhydon','hariyama','voltorb','smeargle','onix','electrike','magcargo','solrock','poliwhirl','gurdurr','graveler','watchog','mareep','gligar','hypno','cubchoo','swoobat','woobat',
                                'shinx','lanturn','bronzong','stunfisk','dugtrio','palpitoad','donphan','ursaring','snover','tranquill','cofagrigus','basculin','bronzong','horsea','magikarp','krokorok','woobat','axew',
                                'golbat','mankey','girafarig','lunatone','gloom','fearow','gloom','lunatone','spinda','golduck','machoke','lombre'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/treecko.gif',
                                'https://media.giphy.com/media/g7C0f00QAimyUAMsYd/giphy.gif'
                        ],
                        vendidos: []
        },
        Davinchy: {     name:'Davinchy',
                        rol: 'Chad',
                        medallas:['b20'],
                        shinys:['exploud','gallade','amoonguss','durant','banette','rapidash','ditto','poliwrath','darumaka','haunter','ditto','heatmor','arcanine','poliwrath','beedrill','ralts','raticate','meowth','sawk',
                                'gothitelle','deino','cubchoo','vanilluxe','petilil','diglett','stantler','noctowl','nidorino','venipede'],
                        destacados:[],
                        vendidos: []
        },
        DiGoMo: {       name:'DiGoMo',
                        rol: 'MegaChad',
                        medallas:['b15','b24','b26','b29','b30'],
                        shinys:['muk','cascoon','spearow','pidgeotto','magby','pelipper','raticate','ponyta','tynamo','raticate','chandelure','poliwrath','spinda','parasect','smeargle','banette','ponyta','weezing','raticate',
                                'murkrow','joltik'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/breloom.gif'],
                        vendidos: ['https://media.giphy.com/media/GpMgr8p0p13wASvhVk/giphy.gif',
                                'https://media.giphy.com/media/y9dID1S7X6zTE330td/giphy.gif',
                                'https://media.giphy.com/media/CNOYDXXMeqrcpEhIE1/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        Dohrito: {      name:'Dohrito',
                        rol: 'Chad',
                        medallas:['b6','b10','b11','b14','b30'],
                        shinys:['medicham','beedrill','gliscor','jynx','marill','wooper','sealeo','magikarp','rapidash','rapidash','dratini','electrike','stunfisk','druddigon','poliwag','swablu','wingull','pelipper','psyduck',
                                'hypno','amoonguss','dunsparce','cubchoo','beartic','cryogonal','vanillite','vanillish','vanilluxe','crustle','grimer','torkoal','litwick','camerupt','magnezone','mareep','tentacruel','wurmple',
                                'wurmple','weezing','vulpix','accelgor','shuppet','lopunny','teddiursa','quagsire','smeargle','spinarak','slugma'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/pinsir.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/cherubi.gif',
                                'https://media.giphy.com/media/b3VLSA5czIMhv6WOKp/giphy.gif',
                                'https://media.giphy.com/media/RFG3g6MyN5VpGHSqkK/giphy.gif'

                        ],
                        vendidos: ['https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc281Y3cxbTRlNGY1YnVwYXFsMzM4Z3FudW1uYWMxZzJrZjcybGt1OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/xbpVD0pTXBBJVkgUKP/giphy.gif']
        },
        Moonlyze: {     name:'Moonlyze',
                        rol: 'MaxiChad',
                        medallas:['b6','b9','b18','b24','b26'],
                        shinys:['smeargle','weezing','ninetales','wigglytuff','magikarp','ditto','bibarel','whismur'],
                        destacados:[],
                        vendidos: [ 'https://media.giphy.com/media/WMaKtMeEQ0nbIBSXL3/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/VW7acYe1rLsGN7fkec/giphy.gif',
                                'https://media.giphy.com/media/cEYKWJiZtqVfvWoy8n/giphy.gif',
                                'https://media.giphy.com/media/Cf3jlPlB66Clh0QAlB/giphy.gif',
                                'https://media.giphy.com/media/XJG6BYtBosorvy0vBF/giphy.gif',
                                'https://media.giphy.com/media/jPuEQEPogo9ZbPJHRQ/giphy.gif',
                                'https://media.giphy.com/media/jPuEQEPogo9ZbPJHRQ/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/m8tGRCtwerALjP9fnz/giphy.gif',
                                'https://media.giphy.com/media/m8tGRCtwerALjP9fnz/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/wgoVjRL6nzlW7JToaD/giphy.gif',
                                'https://media.giphy.com/media/F6yoZWYZ6rf1fJyUEY/giphy.gif',
                                'https://media.giphy.com/media/LWm8fjHUKxqb0qyZpD/giphy.gif',
                                'https://media.giphy.com/media/822MTo2BKJqejpx8is/giphy.gif',
                                'https://media.giphy.com/media/e6ZkFqt8nd84QuSEbP/giphy.gif'
                        ]
        },
        Panchimio: {    name: 'Panchimio',
                        rol: 'MaxiChad',
                        medallas: ['b1','b4','b5','b13','b14','b18','b24','b26','b28','b29','b30'],
                        shinys: ['ninetales','ponyta','golem','vulpix','swellow','bouffalant','chandelure','purrloin','lickilicky','budew','pidgey','pidgeot','tangrowth','growlithe',
                                'jumpluff','solrock','vileplume','slugma','grimer','electrike'],
                        destacados: ['https://img.pokemondb.net/sprites/black-white/anim/shiny/riolu.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/furret.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/simisear.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/iaE6ItdRy56H79jQjg/giphy.gif',
                                'https://media.giphy.com/media/EaNDmWPv4U1x4Jy7tM/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        }
    };
