const listaMedalla = {
  m_vacio:      {name: 'vacío', info: '...'},
  m_gomed:      {name: '🎮 Go MeD', info:'Tienes 1 año o mas en el team'},
  m_cambio:     {name: '💰 Quédate el cambio', info: 'Has donado 10m o mas al banco del team de una sola vez'},
  m_fundador:   {name: '🧩 Pieza clave', info: 'Formas parte de los miembros fundadores del team'},
  m_lider:      {name: '👑 Dictador', info: 'Has sido líder de MeD'},
  m_guardian:   {name: '💂 Guardián', info: 'Has kickeado a alguien de MeD'},
  m_meditite:   {name: '🧘 Cuerpo y mente', info: 'Has obtenido un shiny Meditite'},
  m_safari:     {name: '🎲 De vida o muerte', info: 'Has capturado un shiny en la Zona Safari'},
  m_swarm:      {name: '🗺️ Tour por el mundo', info: 'Has obtenido un shiny de swarm'},
  m_dead:       {name: '💔 Desafortunado', info: 'Has perdido un shiny durante un encuentro'},
  m_secret:     {name: '🌟 Top secret', info: 'Has obtenido un shiny secret (salvaje)'},
  m_shunter:    {name: '📆 Shunter del mes', info: 'Has obtenido la mayor puntuación de shinys en un mes'},
  m_pescador:   {name: '🎣 Maestro pescador', info: 'Has obtenido un shiny pescando'},
  m_cardumen:   {name: '🐟  Cardumen', info: 'Has obtenido 3 shiny pescando (Sin repetir especies)'},
  m_raceW:      {name: '🥇 Race winner', info: 'Has ganado una shiny race'},
  m_raceL:      {name: '🥈 Fail race', info: 'Has obtenido una fase buscando el shiny de la race'},
  m_suertudo:   {name: '🍀 Suertudo', info: 'Has obtenido 2 o mas shiny en 1 día (24h o menos)'},
  m_racha:      {name: '💫 Enrachado', info: 'Has obtenido un shiny en 3 o mas días seguidos'},
  m_sequia:     {name: '💯 Aferrado', info: 'Has obtenido un shiny después de los 100k de encuentros'},
  m_elegido:    {name: '🛐 El elegido', info: 'Has obtenido un shiny alpha o legendario'},
  m_rare:       {name: '🎩 Hat Trick', info: 'Has obtenido 3 shiny \"rare\"'},
  m_abuelo:     {name: '👴 Paciencia de abuelo', info: 'Has obtenido 3 o mas fases buscando un shiny'},
  m_huevo:      {name: '🥚 Raza perfecta', info: 'Has obtenido un shiny por crianza'},
  m_misterio:   {name: '❔ Misterio resuelto', info: 'Has obtenido un shiny de una Ball Misteriosa'},
  m_fosil:      {name: '🦖 Arqueólogo', info: 'Has obtenido un fósil shiny'},
  m_arbol:      {name: '🌳 Arborista', info: 'Has obtenido un shiny de golpe cabeza/árbol de miel'},
  m_mundo:      {name: '🌎 Trotamundos', info:'Has obtenido un mínimo de 3 shiny de cada región (Sin repetir especies)'},
  m_goldenbox:  {name: '📦 Golden box', info: 'Has obtenido una caja llena (60) de shinys'},
  m_raza:       {name: '🧬 Maestro de raza', info: 'Posees la línea evolutiva completa de un shiny (Solo Pokémon que puedan evolucionar)'},
  m_pecador:    {name: '👿 Pecador', info: 'Has vendido, liberado o regalado un shiny'},
  m_cintas:     {name: '🎀 Shiny completo', info: 'Has obtenido un shiny que posee todas las cintas'},
  m_apostol:    {name: '📝 Apóstol', info: 'Has registrado una nueva especie en la Shiny Dex de MeD'},
  m_pvp:        {name: '🎫 Built different', info: 'Has obtenido un shiny ganando un torneo o evento oficial'},
  m_supremacy1: {name: '🌱 MeD Supremacy 1', info: 'Formaste parte del equipo ganador de la MeD Supremacy 1'},
  m_olimpiadas: {name: '🏆 Winners PokeLympics 2024', info: 'Formaste parte del equipo ganador de las PokeLympics 2024'},
  m_supremacy2: {name: '🅿️ MeD Supremacy 2', info: 'Formaste parte del equipo ganador de la MeD Supremacy 2'},
  m_aniMeD:     {name: '🎉 AniMeDsario 2025', info: 'Formaste parte de los ganadores del evento del AniMeDsario 2025'},
  m_shinywar:   {name: '🆖 Shiny War \"OG vs NG\"', info: 'Formaste parte del equipo ganador de la Shiny War \"Old Gen vs New Gen\"'},
  m_adrix:      {name: '☠️ Pecador supremo', info: 'elegido como el mayor pecador del equipo'},
  
};

const memberData = {
        aeamanh: {      name:'aeamanh',
                        rol: 'MaxiChad',
                        medallas:['m_secret','m_raceL','m_suertudo','m_sequia','m_mundo','m_pecador','m_apostol','m_olimpiadas','m_shinywar'],
                        shinys:['donphan','sandslash','scolipede','raticate','tangrowth','spinda','raticate','mienfoo','frillish-f','smeargle','nidoking','ditto','grimer',
                                'chandelure','leavanny','primeape','ditto','deino','snover','bibarel','quagsire','bellossom','weezing','durant','cryogonal','rapidash','pelipper','altaria',
                                'politoed','duskull','duosion','mightyena','gliscor','gyarados','amoonguss','hippowdon','illumise','loudred','stunfisk','cubchoo'],
                        destacados:[ {name: 'gulpin', type: 'normal', link:'gulpin'},
                                     {name: 'pansage', type: 'normal', link:'pansage'},
                                     {name: 'magnetone', type: 'secret', link:'https://media.giphy.com/media/ELEoC52RYPBnz8Vf4s/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/vxRM9XurU5lvpae8Ko/giphy.gif']
        },
        AguitaGooddUwU: {name:'AguitaGooddUwU',
                        rol: 'Chad',
                        medallas:['m_dead','m_pescador','m_pecador','m_shinywar'],
                        shinys:['raticate','ditto','marill','parasect','mienfoo','shuppet','duskull','smeargle','deino','magikarp','frillish-f','chatot','cottonee','cryogonal','swadloon','raticate','meowth','raticate',
                                'lombre','golbat','poliwag','sneasel'
                        ],
                        destacados:[{name: 'zorua', type: 'normal', link:'zorua'}],
                        perdidos: ['https://media.giphy.com/media/yJy0PKLIFGlvtJJaew/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif'
                        ]
        },
        Akalii: {    name:'Akalii',
                        rol: 'Chad',
                        medallas:['m_gomed','m_lider','m_guardian','m_secret','m_pescador','m_raceL','m_suertudo','m_huevo','m_mundo','m_raza','m_pecador','m_apostol'],
                        shinys:['tyranitar','horsea','duskull','mienshao','sharpedo','ninetales','poochyena','beedrill','cottonee','slugma','wooper','azumarill','gyarados','shinx','snorunt',
                                'weavile','axew','pachirisu','lanturn','cottonee','torkoal','gible','jumpluff','weezing','bibarel','vulpix','loudred','ralts','cascoon','scraggy','litwick',
                        ],
                        destacados:[{name: 'gulpin', type: 'normal', link:'gulpin'},
                                    {name: 'chimchar', type: 'egg', link:'https://media.giphy.com/media/fes3PgOa0BRFASIqCg/giphy.gif'},
                                    {name: 'gligar', type: 'secret', link:'https://media.giphy.com/media/KHJMmSNa171LNWJOPK/giphy.gif'}
                                
                        ],
                        perdidos: [],
                        vendidos: ['https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZW54bXF1OWhocTF3cHMzd3lyMmd2MW5xdTFpNWxucmRkbjlhcjI2ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHBxbzBvM2k5OGFpZXJsMHQ4dzk5NGxteW42NXk3N3IyNjEwaXNnYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ubXLD0w80oZjtsrIUH/giphy.gif',
                                'https://media.giphy.com/media/PMMrLwzj3iqyMtpxQs/giphy.gif',
                                'https://media.giphy.com/media/A2NlfU2OIPj0GAVoJy/giphy.gif',
                                'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXY3dXh2MnNsZHQyYjNzdHE3MmpqMnI5dnoxeDU1cW40cTAyMmc3NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ptSTYVxdNLH5oH4Siw/giphy.gif'
                        ]
        },
        Alakxel: {      name:'Alakxel',
                        rol: 'MegaChad',
                        medallas:['m_cambio','m_meditite','m_dead','m_pescador','m_suertudo','m_racha','m_sequia','m_mundo','m_goldenbox','m_apostol','m_raza'],
                        shinys:['rapidash','tentacruel','tentacruel','banette','ponyta','ponyta','patrat','venipede','litwick','magikarp','vulpix','axew','ponyta','lombre','stantler','electivire','koffing','gyarados',
                                'meowth','meowth','magikarp','durant','miltank','deino','ditto','lanturn','heatmor','meowth','duskull','smeargle','slugma','horsea','golett','druddigon','kadabra','haunter','pikachu',
                                'larvitar','psyduck','swablu','machoke','bibarel','magmar','throh','timburr','lairon','hariyama','clamperl','sealeo','marill','shellos-east','kakuna','voltorb','lanturn','cryogonal',
                                'pidgeotto','cottonee','trubbish','snorunt','meditite','sableye','murkrow'
                        ],
                        destacados:[{name:'shellder' ,type:'normal' , link:'shellder'}],
                        perdidos: ['https://media.giphy.com/media/YJrB0vDStEI7gBhlx5/giphy.gif'],
                        vendidos: [],
        },
        AlexisBlu: {    name:'AlexisBlu',
                        rol: 'Chad',
                        medallas:['m_gomed','m_huevo','m_fosil','m_apostol','m_olimpiadas'],
                        shinys:['haxorus','weavile','camerupt','gyarados','swoobat','zigzagoon','cubone'],
                        destacados:[{name: 'charizard', type: 'egg', link:'https://media.giphy.com/media/KHJMmSNa171LNWJOPK/giphy.gif'},
                                {name: 'tirtouga', type: 'egg', link:'https://media.giphy.com/media/sP3E4z0rFHUtZ7gd9x/giphy.gif'}
                                ,
                                
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Alicia: {       name:'Alicia',
                        rol: 'Chad',
                        medallas:['m_gomed','m_lider','m_guardian','m_pescador','m_suertudo','m_rare','m_huevo','m_pecador','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2'],
                        shinys:['parasect','rhydon','camerupt','bronzong','vanilluxe','rattata','girafarig','mareep','spinda','koffing','litwick','horsea','dunsparce'],
                        destacados:[{name: 'corphish', type: 'normal', link:'corphish'},
                                    {name: 'eevee', type: 'egg', link:'https://media.giphy.com/media/nJZvHOjihRvNqn2v8d/giphy.gif'},
                                    {name: 'typhlosion', type: 'egg', link:'https://media.giphy.com/media/EuzEj0pJDbl50OeRQ1/giphy.gif'},
                                    {name: 'porygon-z', type: 'egg', link:'https://media.giphy.com/media/QvBYmu8hATjJhgUuCS/giphy.gif'}
                        ],
                        perdidos: ['https://media.giphy.com/media/4SabkxUjL8LmZRGsK9/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/v9IOxgCRm5BbGXEUEG/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/TvZULFmyJBHodh9Py0/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/jz9aaVnHL7w4V8cX9R/giphy.gif',
                                'https://media.giphy.com/media/GewTzo5C9FI68FMJol/giphy.gif',
                                'https://media.giphy.com/media/7B05VelRsf0qfQptsT/giphy.gif'
                        ]
        },
        AnderHacks: {   name:'AnderHacks',
                        rol: 'Chad',
                        medallas:['m_vacio'],
                        shinys:['mienshao','camerupt','wooper','psyduck','durant','bibarel','roselia'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Ashy: {         name:'Ashy',
                        rol: 'GigaChad',
                        medallas:['m_secret','m_pescador','m_pecador','m_supremacy2','m_shinywar'],
                        shinys:['drifblim','dratini','raticate','gardevoir','duskull','marill','smeargle','scolipede','zangoose','staravia','bellossom','gloom','lanturn','golett','scraggy','swablu','cubchoo'],
                        destacados:[{name: 'carvanha', type: 'normal', link:'carvanha'},
                                    {name: 'breloom', type: 'normal', link:'breloom'},
                                    {name: 'fearow', type: 'secret', link:'https://media.giphy.com/media/4fOM1fIVBlAM7xh90c/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/nmviuh9fVteaRspu6U/giphy.gif']
        },
        AsuraSkyFlames: {name:'AsuraSkyFlames',
                        rol: 'MegaChad',
                        medallas:['m_huevo'],
                        shinys:['amoonguss','druddigon','beedrill','beedrill','klinklang','crobat','galvantula','grimer'],
                        destacados:[{name: 'milotic', type: 'normal', link: 'milotic'},
                                    {name: 'larvesta', type: 'egg', link: 'https://media.giphy.com/media/TMQQ5y9QIz9q0fGe4X/giphy.gif'}],
                        perdidos: [],
                        vendidos: []
        },
        Azathotx: {     name:'Azathotx',
                        rol: 'Chad',
                        medallas:['m_gomed','m_swarm','m_shunter','m_raceL','m_rare','m_huevo','m_apostol','m_olimpiadas','m_shinywar'],
                        shinys:['lotad','cacnea','dustox','cinccino','bidoof','mismagius','gastrodon','mienfoo','spinda','venomoth','vanillish','golduck','camerupt','boldore','dugtrio','poochyena',
                                'smeargle','dusclops','weezing','parasect','scolipede','beedrill','eelektrik','piloswine','solrock'],
                        destacados:[{name: 'Shroomish', type: 'normal', link:'Shroomish'},
                                    {name: 'kecleon', type: 'normal', link:'kecleon'},
                                    {name: 'jolteon', type: 'normal', link:'jolteon'},
                                    {name: 'chansey', type: 'normal', link:'chansey'},
                                    {name:'squirtle', type:'egg', link:'https://media.giphy.com/media/fs3JDMSsrr7R1PwUL9/giphy.gif'},
                                    {name: 'growlithe', type: 'swarm', link:'https://media.giphy.com/media/ggxHTXdRvXKT0VgZ1V/giphy.gif'},
                                    {name: 'absol', type: 'multi', link:'https://media.giphy.com/media/TYOQEUUmVDA3mc5bzW/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Cece: {         name:'Cece',
                        rol: 'MaxiChad',
                        medallas:['m_lider','m_meditite','m_apostol','m_supremacy2'],
                        shinys:['sneasel','meditite','luxray','girafarig','wingull','magmar','deerling','golett','weedle','purrloin','dratini','bronzong','jynx','cofagrigus','hypno','cryogonal','misdreavus'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Cypher: {       name:'Cypher',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_sequia','m_pecador','m_apostol','m_olimpiadas'],
                        shinys:['spearow','golduck','tentacool','vanillish','gyarados','ludicolo','rapidash','conkeldurr','galvantula','mienshao','bellossom','durant','smeargle','sandile','pidgeotto','jumpluff','meowth',
                                'spinda','politoed','vanilluxe','cinccino','lanturn','rhydon','gligar','shelmet','koffing','litwick','cubchoo','starly'
                        ],
                        destacados:[{name: 'furret', type: 'normal', link:'furret'}],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif'
                        ]
        },
        DavidCitos: {   name:'DavidCitos',
                        rol: 'Chad',
                        medallas:['m_shunter','m_suertudo','m_racha','m_abuelo','m_mundo','m_goldenbox','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['lopunny','marill','trapinch','roserade','vulpix','hydreigon','magmar','poliwag','swablu','meowth','gyarados','grimer','weezing','weavile','pikachu','psyduck','mareep','miltank',
                                'litwick','duskull','jigglypuff','electabuzz','rapidash','natu','wobbuffet','accelgor','banette','sealeo','vanilluxe','ferroseed','woobat','poliwhirl','parasect','magnezone','hoppip',
                                'mienfoo','rhydon','hariyama','voltorb','gardevoir','smeargle','onix','electrike','magcargo','solrock','poliwhirl','gurdurr','graveler','watchog','mareep','gligar','hypno','cubchoo','swoobat','woobat',
                                'shinx','lanturn','bronzong','stunfisk','dugtrio','palpitoad','donphan','ursaring','snover','tranquill','cofagrigus','basculin','bronzong','horsea','magikarp','krokorok','woobat','axew',
                                'golbat','mankey','girafarig','lunatone','gloom','fearow','gloom','lunatone','spinda','golduck','machoke','lombre','growlithe','kadabra','misdreavus','golbat','floatzel','haunter','lairon','camerupt',
                                'piloswine','zebstrika','snorunt','poliwag','tentacool'
                        ],
                        perdidos: [],
                        destacados:[{name: 'treecko', type: 'normal', link:'treecko'},
                        ],
                        vendidos: []
        },
        DavinchY: {     name:'DavinchY',
                        rol: 'Chad',
                        medallas:['m_misterio'],
                        shinys:['exploud','gallade','amoonguss','durant','banette','rapidash','ditto','poliwrath','darumaka','haunter','ditto','heatmor','arcanine','poliwrath','beedrill','ralts','raticate','meowth','sawk',
                                'gothitelle','deino','cubchoo','vanilluxe','petilil','diglett','stantler','noctowl','nidorino','venipede','grimer','dratini'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        DiGoMo: {       name:'DiGoMo',
                        rol: 'MegaChad',
                        medallas:['m_dead','m_suertudo','m_pecador','m_apostol','m_olimpiadas','m_supremacy2'],
                        shinys:['muk','cascoon','spearow','pidgeotto','magmortar','pelipper','raticate','ponyta','tynamo','raticate','chandelure','poliwrath','spinda','parasect','smeargle','banette','ponyta','weezing','raticate',
                                'murkrow','joltik','haxorus','vanillish'
                        ],
                        perdidos: ['https://media.giphy.com/media/ixzzR0H9cgH6YX9EJI/giphy.gif'],
                        destacados:[{name: 'breelom', type: 'normal', link:'breloom'},
                                    {name: 'snorlax', type: 'normal', link:'snorlax'}
                        ],
                        vendidos: ['https://media.giphy.com/media/GpMgr8p0p13wASvhVk/giphy.gif',
                                'https://media.giphy.com/media/CNOYDXXMeqrcpEhIE1/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        Distraaa: {     name:'Distraaa',
                        rol: 'Chad',
                        medallas:['m_suertudo','m_shinywar'],
                        shinys:['leavanny','krookodile','weezing','chandelure','smeargle','wigglytuff','tentacruel','zigzagoon'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Doce: {         name:'Doce',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_raceW','m_suertudo','m_huevo','m_pecador','m_apostol','m_supremacy2'],
                        shinys:['crobat','litwick','altaria','ditto','raticate','ditto','shuppet','smeargle','duskull','vanillish','spinarak','lombre','golbat','luxio'],
                        destacados:[{name: 'volcarona', type: 'egg', link:'https://media.giphy.com/media/agBIyJ5VezN1rEyAH7/giphy.gif'},],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/WF2DTy2zrS7IYBXwtQ/giphy.gif',
                             'https://media.giphy.com/media/nEIv8rJh2tV9rMWaAi/giphy.gif'   
                        ]
        },
        Dohrito: {      name:'Dohrito',
                        rol: 'Chad',
                        medallas:['m_meditite','m_secret','m_shunter','m_raceL','m_rare','m_mundo','m_supremacy2'],
                        shinys:['medicham','beedrill','gliscor','jynx','marill','wooper','sealeo','magikarp','rapidash','rapidash','dratini','electrike','stunfisk','druddigon','poliwag','swablu','wingull','pelipper','psyduck',
                                'hypno','amoonguss','dunsparce','cubchoo','beartic','cryogonal','vanillite','vanillish','vanilluxe','crustle','grimer','torkoal','litwick','camerupt','magnezone','mareep','tentacruel','wurmple',
                                'wurmple','weezing','vulpix','accelgor','shuppet','lopunny','teddiursa','quagsire','smeargle','spinarak','slugma'
                        ],
                        destacados:[{name:'pinsir', type:'normal', link:'pinsir'},
                                {name:'cherubi', type:'normal', link:'cherubi'},
                                {name:'wailmer', type:'normal', link:'wailmer'},
                                {name:'serperior', type:'secret', link:'https://media.giphy.com/media/b3VLSA5czIMhv6WOKp/giphy.gif'},
                                {name:'treecko', type:'secret', link:'https://media.giphy.com/media/RFG3g6MyN5VpGHSqkK/giphy.gif'}

                        ],
                        perdidos: [],
                        vendidos: ['https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc281Y3cxbTRlNGY1YnVwYXFsMzM4Z3FudW1uYWMxZzJrZjcybGt1OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/xbpVD0pTXBBJVkgUKP/giphy.gif']
        },
        ElMiga: {       name:'ElMiga',
                        rol: 'MegaChad',
                         medallas:['m_gomed','m_secret','m_raceL','m_pecador','m_apostol','m_supremacy2','m_shinywar'],
                        shinys:['poochyena','staraptor','zigzagoon','larvitar','roserade','raticate','marill'],
                        destacados:[{name: 'jolteon', type: 'normal', link:'jolteon'},
                                    {name: 'poochyena', type: 'secret', link:'https://media.giphy.com/media/3lzuIyWvEzHmmgIFp7/giphy.gif'}
                        ],
                        perdidos: ['https://media.giphy.com/media/EZvvoZS947Meh0bo2E/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/gSUVBePKqAbJpmfIoA/giphy.gif',
                                'https://media.giphy.com/media/cPHoY81t2gnlZ8kqg5/giphy.gif',
                                'https://media.giphy.com/media/xLXn3LWXz0X7vL1Gsd/giphy.gif',
                                'https://media.giphy.com/media/xLXn3LWXz0X7vL1Gsd/giphy.gif'
                        ]
        },
        ermifeNoPremium: {name:'ermifeNoPremium',
                        rol: 'Chad',
                        medallas:['m_apostol','m_shinywar'],
                        shinys:['gyarados','lunatone','rattata','gothorita','rhyperior','jigglypuff','litwick','horsea','sewaddle','raticate','mankey','swablu'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        ErnestoSwampert: {name:'ErnestoSwampert',
                        rol: 'Chad',
                        medallas:['m_safari','m_shunter','m_pescador','m_secret','m_suertudo','m_raza','m_apostol'],
                        shinys:['nidoking','gyarados','poliwag','weavile','mienshao','weezing','beedrill','marill','jigglypuff','smeargle','banette','parasect','wingull','spinarak','shelmet','persian'],
                        destacados:[{name: 'wailord', type: 'normal', link:'wailord'},
                                    {name: 'magikarp' ,type: 'safari', link: 'https://media.giphy.com/media/UNahzhszvptLgyuChJ/giphy.gif'},
                                    {name: 'staryu', type: 'secret', link:'https://media.giphy.com/media/zCSh5QHt2WemejGjzh/giphy.gif'},
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Estorbiito: {   name:'Estorbiito',
                        rol: 'Chad',
                        medallas:['m_suertudo','m_abuelo','m_apostol'],
                        shinys:['smeargle','beedrill','haxorus','poliwrath','weavile','banette','weezing','amoonguss','spinda','ditto','magikarp'],
                        destacados:[{name: 'slaking', type: 'normal', link:'slaking'}],
                        perdidos: [],
                        vendidos: []
        },
        Ferbus: {       name:'Ferbus',
                        rol:'Chad',
                        medallas:['m_meditite','m_swarm','m_secret','m_pescador','m_suertudo','m_mundo'],
                        shinys:['tentacruel','gyarados','ponyta','altaria','politoed','ludicolo','donphan','muk','chandelure','camerupt','donphan','aggron','weezing','dusclops','poliwrath','cofagrigus','psyduck','scolipede',
                                'galvantula','ninetales','slowbro','mienshao','azumarill','medicham','bellossom','bibarel','accelgor','stantler','bibarel','crobat','vanilluxe','solrock','jigglypuff','machamp','dodrio','wobbuffet',
                                'shinx','shellos-east','budew','walrein','hydreigon','smeargle','meowth','banette','spinda','gallade','dugtrio','haxorus','gurdurr','hoppip','wooper','frillish-f'
                        ],
                        destacados:[{name: 'salamence', type:'normal', link:'salamence'},
                                    {name: 'luvdisc', type:'normal', link:'luvdisc'},
                                    {name: 'graveler', type:'secret', link:'https://media.giphy.com/media/yxz6b5ZmjyR3bTEF44/giphy.gif'},
                                    {name: 'corsola', type:'swarm', link:'https://media.giphy.com/media/OYuBjj4gY4R0OlarUz/giphy.gif'}
                        ],
                        perdidos:[],
                        vendidos:[],

        },
        FranCRLZ: {     name:'FranCRLZ',
                        rol: 'Chad',
                        medallas:['m_suertudo'],
                        shinys:['horsea','pikachu','graveler','venipede','kakuna','oddish','krookodile'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Guabixd: {      name:'Guabixd',
                        rol: 'Chad',
                        medallas:['m_raceL','m_suertudo','m_racha','m_pecador','m_apostol','m_shinywar'],
                        shinys:['bibarel','gothita','budew','zigzagoon','heatmor','ditto','seedot','rufflet','golett','frillish','scraggy','mienfoo','ponyta'],
                        destacados:[],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/0vF7t16ROOFeGekWcF/giphy.gif',
                                'https://media.giphy.com/media/dlxXpY9xfkQ1OuNIux/giphy.gif',
                                'https://media.giphy.com/media/2AcQyIAzpCLU22J9ps/giphy.gif',
                                'https://media.giphy.com/media/R0MfWMPIGXgWZgF5gG/giphy.gif',
                                'https://media.giphy.com/media/JV7Psnvy4K5rl24OMw/giphy.gif',
                                'https://media.giphy.com/media/olvnpZMLJ9Thfm9Vo7/giphy.gif',
                                'https://media.giphy.com/media/PMMrLwzj3iqyMtpxQs/giphy.gif',
                                'https://media.giphy.com/media/3Z43q20eTxPd3flPxV/giphy.gif',
                                'https://media.giphy.com/media/y4R16mDezBPthJ6eHQ/giphy.gif'
                        ]
        },
        Hectoralberto: {name:'Hectoralberto',
                        rol: 'Chad',
                        medallas:['m_raceL','m_apostol','m_olimpiadas'],
                        shinys:['quagsire','gyarados','tentacruel','tentacruel','rhyperior','mienfoo','whismur','mightyena','mightyena','grimer','rapidash','rapidash','vanilluxe','ariados','hydreigon',
                                'swablu'
                        ],
                        destacados:[],
                        vendidos: []
        },
        HoraxPC: {      name:'HoraxPC',
                        rol: 'Chad',
                        medallas:['m_suertudo'],
                        shinys:['haxorus','klink','klinklang','chandelure','onix','onix','joltik'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Ingrid: {       name:'Ingrid',
                        rol: 'Chad',
                        medallas:['m_mundo','m_raza','m_pvp','m_shinywar'],
                        shinys:['raticate','pikachu','clefairy','jigglypuff','meowth','arcanine','gengar','onix','kingler','koffing','gyarados','gyarados','crobat','azumarill','politoed','gligar','kingdra','stantler','smeargle',
                                'tyranitar','poochyena','medicham','duskull','luxray','buizel','floatzel','stunky','bronzong','chatot','weavile','tangrowth','mamoswine','cottonee','krookodile','krookodile','maractus','jellicent',
                                'ferroseed','litwick','chandelure','haxorus','beartic','mienfoo','mienshao','mandibuzz','durant','hydreigon','hydreigon','cubchoo','cryogonal'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Iucifer: {      name:'Iucifer',
                        rol: 'MegaChad',
                        medallas:['m_raceL','m_raza','m_pecador','m_apostol'],
                        shinys:['roselia','mienfoo','mienshao','swoobat','solrock','mienfoo','mienfoo','wooper','swablu','stunfisk','golett'],
                        destacados:[{name: 'sentret', type: 'normal', link:'sentret'}],
                        perdidos: [],
                        vendidos: []
        },
        IxGab: {        name:'IxGab',
                        rol: 'MegaChad',
                        medallas:['m_secret','m_pescador','m_raceL','m_suertudo','m_apostol'],
                        shinys:['kirlia','hydreigon','dragonair','crobat','accelgor','leavanny','weezing','dodrio','poliwag','linoone','vanilluxe','raticate'],
                        destacados:[{name: 'corphish', type: 'normal', link:'corphish'},
                                {name: 'luvdisc', type: 'normal', link:'luvdisc'},
                                {name: 'breloom', type: 'normal', link:'breloom'},
                                {name: 'snivy', type: 'normal', link:'snivy'},
                                {name: 'gulpin', type:'secret', link:'https://media.giphy.com/media/dMqaWGfSPgBwKmrZqZ/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Jabubuu: {      name:'Jabubuu',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_dead','m_secret','m_shunter','m_suertudo','m_racha','m_sequia','m_abuelo','m_huevo','m_raza','m_pecador','m_apostol','m_shinywar'],
                        shinys:['solrock','gastrodon','lopunny','politoed','scolipede','raticate','chandelure','bellossom','ninetales','azurill','lilligant','golem','rattata','vanillite','gorebyss','psyduck','wooper',
                                'jumpluff','escavalier','deerling','vileplume','ariados','victreebel','graveler','graveler','sableye','spearow','durant','boldore','sneasel','crustle','slowking','meowth','dewgong','krokorok',
                                'grimer','cubchoo','banette'
                        ],
                        destacados:[{name: 'munna', type: 'secret', link:'https://media.giphy.com/media/HpSnC62YvwsymoUU0o/giphy.gif'},
                                {name: 'umbreon', type: 'egg', link:'https://media.giphy.com/media/rZB8ws1KfCkByqtjn5/giphy.gif'},
                                {name: 'aipom', type: 'second', link:'https://media.giphy.com/media/5XY7dRvTVNprm5Givp/giphy.gif'}
                        ],
                        perdidos: ['https://media.giphy.com/media/JLXanaUxCRYzlAEKWp/giphy.gif'],
                        vendidos: ['https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDFwaGc5MmNwMWgyMmNkdmwyOG9wenoyNGYxanF1b3BreTVsbzg2dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/WwQzqNsYX0l6SgCQZV/giphy.gif']
        },
        JJean: {        name:'JJean',
                        rol: 'Chad',
                        medallas:['m_secret','m_suertudo','m_rare','m_huevo','m_goldenbox','m_raza','m_apostol','m_supremacy2','m_aniMeD'],
                        shinys:['golurk','tyranitar','lanturn','haxorus','aggron','pidove','haunter','steelix','darmanitan','magikarp','gyarados','gyarados','gorebyss','altaria','ferrothorn','grimer','grimer','muk',
                                'chandelure','wooper','quagsire','accelgor','torkoal','geodude','tentacool','duskull','dusclops','marill','camerupt','vanillite','vanilluxe','poliwrath','politoed','miltank','ponyta',
                                'ponyta','rapidash','kingdra','ludicolo','druddigon','weavile','krokorok','psyduck','gigalith','electrike','hydreigon','mienshao','ampharos','wingull','weezing','smeargle','banette',
                                'spinda','braviary','magneton','pikachu','whismur','raticate','ariados','nidorino','miltank','miltank','golbat','loudred'
                        ],
                        destacados:[{name: 'charizard', type: 'egg', link:'https://media.giphy.com/media/kI6DHEnVibteJcUDtY/giphy.gif'},
                                {name: 'breloom', type: 'egg', link:'https://media.giphy.com/media/BuHDxkzqmEhtCIzaLE/giphy.gif'},
                                {name: 'pinsir', type: 'normal', link:'pinsir'},
                                {name: 'metagross', type: 'egg', link:'https://media.giphy.com/media/nUM3Kz42e3MZIkWuiv/giphy.gif'},
                                {name: 'victreebel', type: 'secret', link:'https://media.giphy.com/media/sonHNRtZEAI8bKerAX/giphy.gif'},
                                {name: 'spheal', type: 'secret', link:'https://media.giphy.com/media/lb1D8AmAiq9MaZMXok/giphy.gif'},
                                {name: 'bulbasaur', type: 'egg', link: 'https://media.giphy.com/media/WvZW5hIvmF33I0bYDI/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        JosiasMccartney: {name:'JosiasMccartney',
                        rol: 'Chad',
                        medallas:['m_raza'],
                        shinys:['fearow','arbok','tentacool','rapidash','gothorita','poliwhirl','woobat','meowth','ponyta','gengar','gyarados','kingdra','smeargle','rhydon','mienshao','chandelure','camerupt','luxio'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        JuniorJMx: {    name:'JuniorJMx',
                        rol: 'GigaChad',
                        medallas:['m_guardian','m_meditite','m_safari','m_pescador','m_cardumen','m_raceL','m_suertudo','m_racha','m_mundo','m_goldenbox','m_raza','m_apostol','m_aniMeD','m_shinywar'],
                        shinys:['tentacruel','tentacruel','watchog','kricketune','golduck','smeargle','banette','weezing','torkoal','pelipper','petilil','gothitelle','graveler','vanilluxe','chandelure','rhyperior',
                                'ponyta','meowth','venipede','accelgor','vulpix','bronzong','stantler','golbat','wingull','magikarp','spinda','whirlipede','lilligant','swellow','cryogonal','pidgey','piloswine',
                                'skuntank','golem','probopass','oddish','gloom','volbeat','trubbish','garbodor','trapinch','dratini','misdreavus','dusclops','tauros','cinccino','foongus','jynx','golurk','donphan',
                                'girafarig','lunatone','meditite','parasect','ditto','ditto','cacnea','pachirisu','staravia','vibrava','cryogonal','vanillish','bellsprout','noctowl'
                        ],
                        destacados:[{name: 'shellder', type: 'normal', link:'shellder'},
                                {name: 'carvanha', type: 'normal', link:'carvanha'},
                                {name: 'luvdisc', type: 'normal', link:'luvdisc'},
                                {name: 'koffing', type: 'safari', link:'https://media.giphy.com/media/bro6Bi85eRrGodIkYs/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        KilluaZoldyck: {name:'KilluaZoldyck',
                        rol: 'Chad',
                        medallas:['m_gomed'],
                        shinys:['dratini','smeargle','duskull','koffing','gyarados','donphan','rapidash','ponyta','vulpix','woobat'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Krackon: {      name:'Krackon',
                        rol: 'Chad',
                        medallas:['m_secret','m_huevo','m_apostol'],
                        shinys:['mienshao','gyarados','altaria','chandelure','reuniclus','crobat','pachirisu','noctowl','timburr','timburr','vanillite','luxray','primeape','quagsire','drowzee','spinda','shuppet',
                                'watchog','weezing','mienfoo','gloom','venipede','venipede','raticate','ditto','steelix','smeargle','zigzagoon','beautifly','weavile','purrloin','golbat','ninetales','golbat','kingdra',
                                'fearow'
                        ],
                        destacados:[{name: 'chansey', type: 'secret', link:'https://media.giphy.com/media/PbdZZMpNNmIk3uTqCp/giphy.gif'},
                                {name: 'serperior', type: 'egg', link:'https://media.giphy.com/media/tCGXXyoEV1I2kuGyGv/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Krampus: {      name:'Krampus',
                        rol: 'MegaChad',
                        medallas:['m_pescador','m_suertudo','m_pecador','m_apostol'],
                        shinys:['gigalith','altaria','raticate','politoed','victreebel','accelgor','quagsire','donphan','hydreigon','ludicolo','poliwrath','chandelure','magcargo','haxorus','darmanitan','psyduck','doduo',
                                'gyarados','smeargle','weezing','braviary','jellicent-f','raichu','rapidash','gurdurr','grimer','bellsprout','metapod','scraggy','cubchoo','piloswine','krokorok','duskull','duosion'
                        ],
                        destacados:[{name: 'luvdisc', type: 'normal', link:'luvdisc'}],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/QAmOMaVAIsfyhe1qi1/giphy.gif']
        },
        KnowJiYong: {   name:'KnowJiYong',
                        rol: 'MaxiChad',
                        medallas:['m_gomed','m_guardian','m_secret','m_shunter','m_pescador','m_raceL','m_suertudo','m_huevo','m_mundo','m_raza','m_pecador','m_apostol','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['kakuna','tentacruel','tentacruel','tentacruel','tentacruel','slugma','banette','chandelure','camerupt','torkoal','claydol','smeargle','lanturn','gloom','bellossom','pikachu','minccino',
                                'sandshrew','psyduck','surskit','dewgong','beedrill','weezing','pelipper','krokorok','rapidash','durant','deino','glalie','abomasnow','accelgor','duskull','ditto','donphan','floatzel',
                                'zebstrika','magnemite','wingull','electabuzz','vulpix','haunter','luxio'
                        ],
                        destacados:[{name: 'staryu', type: 'normal', link:'staryu'},
                                {name: 'lumineon', type: 'normal', link:'lumineon'},
                                {name: 'breloom', type: 'normal', link:'breloom'},
                                {name: 'mothim', type: 'egg', link:'https://media.giphy.com/media/8VumrMKv5zs67UtkvH/giphy.gif'},
                                {name: 'tauros', type: 'secret', link:'https://media.giphy.com/media/lZAtjAs3Goy7Q8YT5l/giphy.gif'},
                                {name: 'pidgey', type: 'secret', link:'https://media.giphy.com/media/wuQKOEVvovxvZElCoZ/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/WnUoZLB0Sa1LV9rel3/giphy.gif']
        },
        LauraSkylar: {  name:'LauraSkylar',
                        rol: 'Chad',
                        medallas:['m_gomed','m_safari','m_dead','m_suertudo','m_raza','m_apostol','m_shinywar'],
                        shinys:['lanturn','roserade','geodude','golem','donphan','braviary','pelipper','volbeat','sigilyph','minccino','cinccino','trubbish'],
                        destacados:[{name: 'nidoran-f', type: 'safari', link:'https://media.giphy.com/media/iqqZaJgalqVoPITNnV/giphy.gif'}],
                        perdidos: ['https://media.giphy.com/media/03cHN7rGUFZA515olc/giphy.gif',
                                'https://media.giphy.com/media/Z5eN8XmGSmU8YGqxIj/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/nbxsygYVLvm1Z9IXpu/giphy.gif',
                                'https://media.giphy.com/media/RiSG1piNjO9VPGPjmV/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif'
                        ]
        },
        Liarfuneral: {  name:'Liarfuneral',
                        rol: 'Chad',
                        medallas:['m_shinywar'],
                        shinys:['dusclops','dragonite','hydreigon','bouffalant','gyarados','lilligant','chandelure','golett','ponyta','pelipper'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Lirio: {        name:'Lirio',
                        rol: 'Chad',
                        medallas:['m_pescador','m_mundo','m_pecador'],
                        shinys:['ampharos','froslass','altaria','ninetales','wigglytuff','crobat','manectric','spinda','haxorus','hydreigon','ditto','garchomp','gyarados','kingdra','pikachu','krookodile',
                                'honchkrow','pelipper','gengar','chandelure','cofagrigus','banette','dusclops','delibird','magcargo','weezing','amoonguss','weavile','conkeldurr','reuniclus','mienshao','gastrodon',
                                'gastrodon-east','wynaut','gothitelle','mawile','golduck','lilligant','bellossom','jumpluff','dustox','roselia','parasect','ariados','slowbro','politoed','smeargle',
                                'poliwrath','ludicolo','lanturn','nidoking','solrock','torkoal','cottonee','diglett','smeargle','ponyta'
                        ],
                        destacados:[{name: 'unown-em', type: 'normal', link:'unown-em'},
                                {name: 'corphish', type: 'normal', link:'corphish'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/x7RaJ1XovphNsEueqk/giphy.gif']
        },
        Maicol: {     name:'Maicol',
                        rol: 'Chad',
                        medallas:['m_dead','m_huevo','m_apostol','m_supremacy2'],
                        shinys:['ludicolo','larvitar','steelix','venipede','chandelure','smeargle','magikarp','gyarados','cubchoo','cacnea','alakazam','parasect','spinda','duskull'],
                        destacados:[{name: 'breloom', type: 'normal', link:'breloom'},
                                {name: 'venusaur', type: 'egg', link:'https://media.giphy.com/media/71JqlJebXFCWBdw4j4/giphy.gif'}
                                ],
                        perdidos: ['https://media.giphy.com/media/xApUnnnPV5cJhTqy2c/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/7uxLPTrZZAl2HjGG9y/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/bsxtXWvus1jvqHDZA7/giphy.gif'
                        ]
        },
        MangoOscuro: {  name:'MangoOscuro',
                        rol: 'Chad',
                        medallas:['m_gomed','m_swarm','m_apostol'],
                        shinys:['spinda','nidoking','spinarak','poliwrath','weedle','scrafty','mightyena'],
                        destacados:[{name: 'misdreavus', type: 'swarm', link:'https://media.giphy.com/media/4UZxfBHHPVtzNGkt2o/giphy.gif'}],
                        perdidos: [],
                        vendidos: []
        },
        MarkosW: {      name:'MarkosW',
                        rol: 'GigaChad',
                        medallas:['m_dead','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['sunflora','litwick','cryogonal','beedrill','ponyta','smeargle','koffing','tentacruel','psyduck','golett','clefable','vanilluxe'],
                        destacados:[],
                        perdidos: ['https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDQzM2g0YjNjaDIwNjF6ODl0MTV5ZHRyc2UzdWZpYTBkamE1bjZ5aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/xIpPVNVgAxrr7mfHV2/giphy.gif'],
                        vendidos: []
        },
        Martxn: {        name:'Martxn',
                        rol: 'Chad',
                        medallas:['m_pescador','m_suertudo','m_racha','m_apostol'],
                        shinys:['onix','chandelure','gliscor','banette','gyarados','smeargle','exploud','tentacruel','shelmet','koffing','slowbro','buneary'],
                        destacados:[{name: 'luvdisc', type: 'normal', link:'luvdisc'},
                                {name: 'remoraid', type: 'normal', link:'remoraid'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        MasterFox: {    name:'MasterFox',
                        rol: 'Chad',
                        medallas:['m_gomed','m_dead','m_secret','m_pescador','m_suertudo','m_huevo','m_pecador','m_apostol','m_supremacy2'],
                        shinys:['butterfree','raticate','parasect','venomoth','golem','rapidash','kingler','ditto','dunsparce','kingdra','exploud','altaria','lunatone','huntail','gigalith','leavanny','lilligant',
                                'crustle','cinccino','gothitelle','vanilluxe','sawsbuck','galvantula','haxorus','accelgor','golurk','bouffalant','durant','chandelure','tyranitar','sandslash','slowbro','sawsbuck-winter',

                        ],
                        destacados:[{name: 'corsola', type: 'normal', link:'corsola'},
                                {name: 'volcarona', type: 'egg', link:'https://media.giphy.com/media/agBIyJ5VezN1rEyAH7/giphy.gif'},
                                {name: 'raichu', type: 'secret', link:'https://media.giphy.com/media/eCSsSbLABW1K8BMlrG/giphy.gif'},
                                {name: 'beedrill', type: 'secret', link:'https://media.giphy.com/media/S14AkMdwMqLPtXwyTB/giphy.gif'}
                        ],
                        perdidos: ['https://media.giphy.com/media/GB3mLVQZvNawNjVxRT/giphy.gif'],
                        vendidos: []
        
        },
        MasterSainz: {  name:'MasterSainz',
                        rol: 'Chad',
                        medallas:['m_pecador'],
                        shinys:['donphan','ditto','donphan'],
                        destacados:[],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/RiSG1piNjO9VPGPjmV/giphy.gif'
                        ]
        },
        Maxii: {        name:'Maxii',
                        rol: 'Chad',
                        medallas:['m_apostol'],
                        shinys:['aggron','dusclops','eelektross','golduck','alakazam','weezing','grimer','magcargo','krabby','loudred','pidgey','parasect'],
                        destacados:[{name: 'heracross', type: 'normal', link:'heracross'}],
                        perdidos: [],
                        vendidos: []
        },
        Mexb: {         name:'Mexb',
                        rol: 'MegaChad',
                        medallas:['m_swarm','m_secret','m_raceL','m_suertudo','m_sequia','m_abuelo','m_raza','m_apostol','m_shinywar'],
                        shinys:['dusclops','gallade','weezing','mienshao','dugtrio','ponyta','chandelure','scrafty','smeargle','spinda','poliwrath','accelgor','mienfoo','yamask','kricketune','cacnea','shellos-east',
                                'shellos-east'
                        ],
                        destacados:[{name: 'staryu', type: 'normal', link:'staryu'},
                                {name: 'porygon-z', type: 'swarm', link:'https://media.giphy.com/media/1THDLYByT8yEctYNEy/giphy.gif'},
                                {name: 'roselia', type: 'secret', link:'https://media.giphy.com/media/oRnsLHK2wKMqpMcC5z/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Mikuwuu: {      name:'Mikuwuu',
                        rol: 'Chad',
                        medallas:['m_shunter','m_pescador','m_raceW','m_huevo','m_apostol'],
                        shinys:['gyarados','ninetales','girafarig'],
                        destacados:[{name: 'delcatty', type: 'normal', link:'delcatty'},
                                {name: 'milotic', type: 'normal', link:'milotic'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Mittoh: {       name:'Mittoh',
                        rol: 'GigaChad',
                        medallas:['m_gomed','m_pecador','m_pescador','m_racha','m_huevo','m_apostol','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['litwick','meowth','deino','purugly','duosion','ninetales','bibarel','bibarel','petilil','donphan','golett','vanilluxe','magikarp','mankey','murkrow','ralts','wooper','poliwag',
                                'koffing','krabby','swadloon'
                        ],
                        destacados:[{name: 'eevee', type: 'egg', link:'https://media.giphy.com/media/nJZvHOjihRvNqn2v8d/giphy.gif'}],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/WBCKmSHx1P3rtJeWFe/giphy.gif',
                                'https://media.giphy.com/media/WBCKmSHx1P3rtJeWFe/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        MonkeyCake: {   name:'MonkeyCake',
                        rol: 'Chad',
                        medallas:['m_gomed','m_swarm','m_dead','m_pecador','m_apostol'],
                        shinys:[],
                        destacados:[{name: 'arbok', type: 'swarm', link:'https://media.giphy.com/media/8W1sZrHzScrNbg6NZI/giphy.gif'}],
                        perdidos: ['https://media.giphy.com/media/n1rn0watJNvobQdzqb/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/gwavhTbufATct7EFs0/giphy.gif',
                                'https://media.giphy.com/media/v7BwuKEmsYbSzTXu2Z/giphy.gif',
                                'https://media.giphy.com/media/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media.giphy.com/media/D0VlsgLGW6enaA5m7m/giphy.gif',
                                'https://media.giphy.com/media/ABbHis5AHV4KFY18so/giphy.gif'
                        ]
        },
        Monozee: {      name:'Monozee',
                        rol: 'Chad',
                        medallas:['m_dead','m_suertudo','m_pecador'],
                        shinys:['watchog','dodrio','dodrio','donphan','donphan','horsea','purrloin','koffing','litwick','sneasel','smeargle','magikarp','duskull','vulpix','axew','banette','krokorok','misdreavus','poliwag'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Moonlyze: {     name:'Moonlyze',
                        rol: 'Chad',
                        medallas:['m_meditite','m_dead','m_pescador','m_suertudo','m_abuelo','m_pecador','m_apostol'],
                        shinys:['smeargle','weezing','ninetales','wigglytuff','magikarp','ditto','bibarel','whismur'],
                        destacados:[],
                        perdidos: ['https://media.giphy.com/media/WMaKtMeEQ0nbIBSXL3/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/VW7acYe1rLsGN7fkec/giphy.gif',
                                'https://media.giphy.com/media/cEYKWJiZtqVfvWoy8n/giphy.gif',
                                'https://media.giphy.com/media/Cf3jlPlB66Clh0QAlB/giphy.gif',
                                'https://media.giphy.com/media/XJG6BYtBosorvy0vBF/giphy.gif',
                                'https://media.giphy.com/media/jPuEQEPogo9ZbPJHRQ/giphy.gif',
                                'https://media.giphy.com/media/jPuEQEPogo9ZbPJHRQ/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/m8tGRCtwerALjP9fnz/giphy.gif',
                                'https://media.giphy.com/media/m8tGRCtwerALjP9fnz/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/wgoVjRL6nzlW7JToaD/giphy.gif',
                                'https://media.giphy.com/media/F6yoZWYZ6rf1fJyUEY/giphy.gif',
                                'https://media.giphy.com/media/LWm8fjHUKxqb0qyZpD/giphy.gif',
                                'https://media.giphy.com/media/822MTo2BKJqejpx8is/giphy.gif',
                                'https://media.giphy.com/media/e6ZkFqt8nd84QuSEbP/giphy.gif'
                        ]
        },
        MrCartago: {    name:'MrCartago',
                        rol: 'Chad',
                        medallas:['m_pescador','m_raceW','m_apostol'],
                        shinys:['crobat','hydreigon','dodrio','scolipede','gigalith','durant','gyarados','conkeldurr','rapidash','donphan','mienfoo','haxorus','cottonee','krokorok'
                        ],
                        destacados:[{name: 'milotic', type: 'normal', link: 'milotic'}],
                        perdidos: [],
                        vendidos: []
        },
        must: {         name:'must',
                        rol: 'Chad',
                        medallas:['m_safari','m_dead','m_abuelo','m_raza','m_pecador'],
                        shinys:['pidgeot','persian','ludicolo','mantine','altaria','smeargle','hoothoot','poochyena','meowth','beautifly','wingull','jumpluff','poliwag','torkoal','dewgong','mareep','meowth'
                                ,'gligar'
                        ],
                        destacados:[{name: 'furret', type: 'normal', link:'furret'},
                                {name: 'sceptile', type: 'normal', link:'sceptile'},
                                {name: 'lapras', type: 'safari', link:'https://media.giphy.com/media/GKVQ6Xdjm9DDDIb63C/giphy.gif'}
                        ],
                        perdidos: ['https://media.giphy.com/media/BYhOYqM8qaER7ukxVW/giphy.gif',
                                'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDR5Nm12eG9lNDM5Y3VoeWN1ZHVwcTFmYXJsYml1YW1hZDN0N3hodCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/DNXSProoe7z5LX0l7h/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/lAcpPVwrBgQfMfBHlD/giphy.gif',
                                'https://media.giphy.com/media/T2bUB6ZHTIO3fxlH11/giphy.gif',
                                'https://media.giphy.com/media/FF9MGEFeqTS4Mn2vAJ/giphy.gif',
                                'https://media.giphy.com/media/13ZtgbQM9NwuIjtoyN/giphy.gif',
                                'https://media.giphy.com/media/rAa3yXQEgFsN72fvoY/giphy.gif',
                                'https://media.giphy.com/media/rAa3yXQEgFsN72fvoY/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/EQIOBvPaS0RoyW6P2J/giphy.gif',
                                'https://media.giphy.com/media/vgltunPjQb3mMh3pYq/giphy.gif'
                        ]
        },
        Mxxarc: {       name:'Mxxarc',
                        rol: 'Chad',
                        medallas:['m_gomed','m_huevo','m_apostol','m_supremacy1','m_olimpiadas'],
                        shinys:['mienshao','flygon','nidoran-f','chandelure','ninetales','muk','lanturn','altaria','seismitoad','smeargle','druddigon','kingdra','gyarados','joltik'],
                        destacados:[{name: 'typhlosion', type: 'egg', link:'https://media.giphy.com/media/EuzEj0pJDbl50OeRQ1/giphy.gif'}],
                        perdidos: [],
                        vendidos: []
        },
        nyumichaelis: {name:'nyumichaelis',
                        rol: 'Chad',
                        medallas:['m_gomed','m_pescador','m_secret','m_suertudo','m_abuelo','m_raza','m_pecador','m_apostol','m_olimpiadas','m_shinywar'],
                        shinys:['tentacruel','bouffalant','rapidash','ponyta','scolipede','slugma','lopunny','poochyena','weedle','steelix','cottonee','bibarel','silcoon','dustox','beautifly','graveler','golem'],
                        destacados:[{name: 'zorua', type: 'normal', link:'zorua'},
                                {name: 'shroomish', type: 'normal', link:'shroomish'},
                                {name: 'carvanha', type: 'normal', link:'carvanha'},
                                {name: 'phanpy', type: 'secret', link:'https://media.giphy.com/media/A9lxfTVpkbM0x68HlH/giphy.gif'},
                                {name: 'fearow', type: 'secret', link:'https://media.giphy.com/media/4fOM1fIVBlAM7xh90c/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif'
                        ]
        },
        OniED: {        name:'OniED',
                        rol: 'MegaChad',
                        medallas:['m_secret','m_pescador','m_suertudo','m_racha','m_rare','m_abuelo','m_huevo','m_fosil','m_raza','m_pecador','m_apostol','m_shinywar'],
                        shinys:['weavile','tentacruel','amoonguss','sandslash','gligar','grimer','koffing','meowth','poochyena','zigzagoon','pelipper','wingull','mienshao','ditto','accelgor','ledyba','hoothoot',
                                'bellsprout','scolipede','sewaddle','lotad','golett','slugma','claydol','cryogonal'
                        ],
                        destacados:[{name: 'pansage', type: 'normal', link:'pansage'},
                                {name: 'remoraid', type: 'normal', link:'remoraid'},
                                {name: 'slakoth', type: 'normal', link:'slakoth'},
                                {name: 'shroomish', type: 'normal', link:'shroomish'},
                                {name: 'shroomish', type: 'normal', link:'pawniard'},
                                {name: 'cranidos', type: 'egg', link:'https://media.giphy.com/media/Dk1ECUJy7ElgT24Ncu/giphy.gif'},
                                {name: 'larvesta', type: 'egg', link:'https://media.giphy.com/media/TMQQ5y9QIz9q0fGe4X/giphy.gif'},
                                {name: 'pelipper', type: 'secret', link:'https://media.giphy.com/media/g9HysJkxwY4NjKzrjg/giphy.gif'},
                                {name: 'zigzagoon', type: 'secret', link:'https://media.giphy.com/media/KtpRlWqgvUC1uBAJbI/giphy.gif'},
                                {name: 'growlithe', type: 'secret', link:'https://media.giphy.com/media/vYapmKuh0r9xrREN5K/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/3XWhYuF1IEcTsDBJXD/giphy.gif',
                                'https://media.giphy.com/media/tILTB4DTScZ7Sd5PIP/giphy.gif',
                                'https://media.giphy.com/media/7B05VelRsf0qfQptsT/giphy.gif',
                                'https://media.giphy.com/media/D3Lvv8nOqyVEkRFrWZ/giphy.gif',
                                'https://media.giphy.com/media/ofHxoizb5ZyN3uvFU6/giphy.gif',
                                'https://media.giphy.com/media/Lk4bupthAXzZiYNLPx/giphy.gif',
                                'https://media.giphy.com/media/juwTFb2dmySsKb2N3b/giphy.gif',
                                'https://media.giphy.com/media/juwTFb2dmySsKb2N3b/giphy.gif',
                                'https://media.giphy.com/media/25US6QyxVKt91tanHm/giphy.gif',
                                'https://media.giphy.com/media/25US6QyxVKt91tanHm/giphy.gif',
                                'https://media.giphy.com/media/DTGNzyLWgweQqRRGJ4/giphy.gif',
                                'https://media.giphy.com/media/DTGNzyLWgweQqRRGJ4/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media.giphy.com/media/jUZ6vbouEmCb3ZEKlA/giphy.gif',
                                'https://media.giphy.com/media/jLFYwkOfbOK6EYuImb/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif'
                        ]
        },
        OreganoPVP: {   name:'OreganoPVP',
                        rol: 'Chad',
                        medallas:['m_gomed','m_secret','m_raceW','m_huevo','m_apostol','m_olimpiadas'],
                        shinys:['gardevoir','tentacruel','nidoking','crobat','bouffalant','sandslash','beheeyem','azumarill','drifblim','rhyperior','hariyama','solrock','rapidash','persian','mantine'],
                        destacados:[ {name: 'mudkip', type: 'egg', link:'https://media.giphy.com/media/tbC1NEwy3G4QZ3ng7t/giphy.gif'},
                                {name: 'heracross', type: 'secret', link:'https://media.giphy.com/media/yrby6ktEldwSDonlg1/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Palafo: {       name:'Palafo',
                        rol: 'Chad',
                        medallas:['m_gomed','m_fundador','m_lider','m_guardian','m_meditite','m_pescador','m_raza','m_pecador','m_apostol','m_supremacy1','m_olimpiadas'],
                        shinys:['machop','spoink','hypno','meowth','hypno','meowth','ponyta','masquerain','gyarados','tangela','drowzee','victreebel','bellossom','jumpluff','beautifly','psyduck','mienfoo'],
                        destacados:[{name: 'whiscash', type: 'normal', link:'whiscash'}],
                        perdidos: [],
                        vendidos: []
        },
        Pancho: {       name: 'Pancho',
                        rol: 'MaxiChad',
                        medallas: ['m_gomed','m_lider','m_guardian','m_raceW','m_abuelo','m_mundo','m_raza','m_pecador','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys: ['nidoking','ninetales','ponyta','golem','vulpix','swellow','bouffalant','chandelure','purrloin','lickilicky','budew','pidgey','pidgeot','tangrowth','growlithe',
                                'jumpluff','solrock','vileplume','slugma','grimer','electrike','mandibuzz'],
                        destacados: [{name: 'riolu', type: 'normal', link:'riolu'},
                                {name: 'furret', type: 'normal', link:'furret'},
                                {name: 'simisear', type: 'normal', link:'simisear'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/EaNDmWPv4U1x4Jy7tM/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        Payo: {         name:'Payo',
                        rol: 'Chad',
                        medallas:['m_raceL','m_pecador','m_shinywar'],
                        shinys:['psyduck','roserade','golett','rapidash','shelmet','shellos-east'],
                        destacados:[],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif'
                        ]
        },
        pimientadaza: { name:'pimientadaza',
                        rol: 'Chad',
                        medallas:['m_pecador','m_apostol'],
                        shinys:['haxorus','muk','fearow'],
                        destacados:[],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/AB2zHXNURMrFmsWTee/giphy.gif']
        },
        RagnarokBs: {   name:'RagnarokBs',
                        rol: 'Chad',
                        medallas:['m_gomed','m_olimpiadas'],
                        shinys:['azumarill','accelgor','gyarados','scrafty','politoed','krokorok','pidgey','watchog','chandelure','abra','slowbro','zubat','koffing','mienfoo','vanillite','smeargle','bibarel',
                                'durant','gurdurr'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        rebukittheveil: {name:'rebukittheveil',
                        rol: 'Chad',
                        medallas:['m_pescador','m_suertudo','m_huevo','m_pecador','m_cardumen','m_olimpiadas','m_supremacy2'],
                        shinys:['haxorus','manectric','camerupt','nidoqueen','lickitung','lanturn','luxio','vulpix','horsea','dragonair','krokorok','mienfoo','lilligant','golbat','seadra','krabby','poliwhirl'],
                        destacados:[{name:'barboach', type:'normal', link:'barboach'},
                                    {name: 'charizard', type: 'egg', link:'https://media.giphy.com/media/kI6DHEnVibteJcUDtY/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/0vF7t16ROOFeGekWcF/giphy.gif',
                                'https://media.giphy.com/media/0vF7t16ROOFeGekWcF/giphy.gif',
                                'https://media.giphy.com/media/qI0CeWonaxP7k6Y4Lx/giphy.gif'
                        ]
        },
        Reimy: {        name:'Reimy',
                        rol: 'Chad',
                        medallas:['m_dead','m_secret','m_pescador','m_suertudo','m_racha','m_pecador','m_apostol','m_shinywar'],
                        shinys:['gardevoir','haxorus','ninetales','torkoal','flygon','elgyem','clamperl','snorunt','dratini','glameow','lunatone'],
                        destacados:[{name:'octillery', type:'secret', link:'https://media.giphy.com/media/6DMtcidcohaobjRyCY/giphy.gif'}],
                        perdidos: ['https://media.giphy.com/media/5NXDeILPVEJs8H43qW/giphy.gif',
                                'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjVqdGVsbXlrMjdxMDI4NzhydjdvcHdxYWdlcWVvdnhmcGxxZGFubyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/fKT5lPOrx2PXodB2BD/giphy.gif'
                                ],
                        vendidos: ['https://media.giphy.com/media/gSUVBePKqAbJpmfIoA/giphy.gif',
                                'https://media.giphy.com/media/UCSl0CT0X05tKQKvmv/giphy.gif',
                                'https://media.giphy.com/media/iaE6ItdRy56H79jQjg/giphy.gif',
                                'https://media.giphy.com/media/cZI8bvqidD7iphlbdH/giphy.gif',
                                'https://media.giphy.com/media/v7BwuKEmsYbSzTXu2Z/giphy.gif',
                                'https://media.giphy.com/media/QBMPSmPsPc2VXpWte4/giphy.gif',
                                'https://media.giphy.com/media/QBMPSmPsPc2VXpWte4/giphy.gif',
                                'https://media.giphy.com/media/maxPYO7zrPpNCFO0pV/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/I3nMAb29UTofjDsWFg/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/SMttCxbkrQWz8LNsx5/giphy.gif',
                                'https://media.giphy.com/media/olvnpZMLJ9Thfm9Vo7/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/IttNS3VLZryvvxmoL9/giphy.gif'
                        ]
        },
        Renz: {         name:'Renz',
                        rol: 'Chad',
                        medallas:['m_gomed','m_guardian','m_meditite','m_secret','m_raceW','m_pecador','m_apostol'],
                        shinys:['chandelure','camerupt','meowth'],
                        destacados:[{name: 'whismur', type:'secret', link:'https://media.giphy.com/media/ISSi5NgbdVWg0yjwXo/giphy.gif'}],
                        perdidos: [],
                        vendidos: []
        },
        reylegendarioK: {name:'reylegendarioK',
                        rol: 'Chad',
                        medallas:['m_shinywar'],
                        shinys:['scolipede','smeargle','mismagius','hydreigon','krokorok','rapidash','raticate','raticate','sawk','cryogonal'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        RIIW: {         name:'RIIW',
                        rol: 'Chad',
                        medallas:['m_dead'],
                        shinys:['gengar','graveler','chandelure','mienshao'],
                        destacados:[],
                        perdidos: ['https://media.giphy.com/media/x9SlMSbBu4sM92smld/giphy.gif'],
                        vendidos: []
        },
        ritosenpai: {   name:'ritosenpai',
                        rol: 'MaxiChad',
                        medallas:['m_gomed','m_secret','m_shunter','m_raceL','m_suertudo','m_sequia','m_abuelo','m_mundo','m_goldenbox','m_raza','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['slugma','mienfoo','mienfoo','mienfoo','mienfoo','volbeat','shelmet','voltorb','politoed','deino','bellsprout','linoone','weepinbell','drifblim','houndour','zigzagoon','zigzagoon','wynaut',
                                'larvitar','seviper','snorunt','geodude','cubchoo','cubchoo','cubchoo','ponyta','stantler','sableye','golduck','cottonee','sawsbuck','stunky','dratini','wooper','eelektross','jigglypuff',
                                'spinda','zangoose','swadloon','mawile','zubat','kingdra','psyduck','cryogonal','torkoal','poochyena','beartic','vanillish','victreebel','deerling','deerling-autumn','krokorok','weezing',
                                'fearow','fearow','fearow','jumpluff','flygon','shuppet','scraggy','darmanitan','herdier','jynx','pidgey','weepinbell','spearow','chandelure','bronzong','bronzong','lairon','gabite',
                                'surskit','pidove','clamperl','mightyena','golbat','lunatone','lunatone','ralts','zebstrika'
                        ],
                        destacados:[{name: 'ninjask', type: 'normal', link:'ninjask'},
                                {name: 'swampert', type: 'normal', link:'swampert'},
                                {name: 'jolteon', type: 'normal', link:'jolteon'},
                                {name: 'scizor', type: 'normal', link:'scizor'},
                                {name: 'gulpin', type: 'secret', link:'https://media.giphy.com/media/dMqaWGfSPgBwKmrZqZ/giphy.gif'},
                                {name: 'zigzagoon', type: 'secret', link:'https://media.giphy.com/media/KtpRlWqgvUC1uBAJbI/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        sadending: {    name:'sadending',
                        rol: 'Chad',
                        medallas:['m_swarm','m_secret','m_shunter','m_raceW','m_abuelo','m_apostol'],
                        shinys:['poochyena','poochyena','zigzagoon','bidoof','ponyta','wurmple','magikarp','mienshao','onix','onix'],
                        destacados:[{name: 'shroomish', type: 'normal', link:'shroomish'},
                                {name: 'skarmory', type: 'normal', link:'skarmory'},
                                {name: 'gliscor', type: 'secret', link:'https://media.giphy.com/media/2pKZUMHKeaw2v48YC7/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Salva: {        name:'Salva',
                        rol: 'MegaChad',
                        medallas:['m_swarm','m_secret','m_pescador','m_cardumen','m_pecador','m_apostol','m_shinywar'],
                        shinys:['haxorus','ninetales','gigalith','litwick','weezing','swellow','torkoal','smeargle','bibarel','golurk','elgyem','electrode','magikarp','krabby','shelmet','tauros'],
                        destacados:[{name:'corphish', type:'normal', link:'corphish'},
                                    {name:'feebas', type:'normal', link:'feebas'},
                                    {name:'beldum', type:'normal', link:'beldum'},
                                    {name: 'duskull', type: 'secret', link:'https://media.giphy.com/media/sbptGtIipK7BKqDckI/giphy.gif'}],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/3Z43q20eTxPd3flPxV/giphy.gif',
                                'https://media.giphy.com/media/ybT9l6ye0rTcCJfv7T/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/Dlf0PstQvtGUFEiImQ/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif'
                        ]
        },
        Seaba: {        name:'Seaba',
                        rol: 'MegaChad',
                        medallas:['m_safari','m_swarm','m_suertudo','m_racha','m_sequia','m_abuelo','m_huevo','m_apostol'],
                        shinys:['gigalith','chandelure','solrock','jynx','crobat','dusknoir','haxorus','hydreigon','gyarados','smeargle','psyduck','gardevoir','liepard','gothitelle','cinccino','jumpluff','masquerain',
                                'accelgor','petilil','wingull','cacnea','darumaka','electrike','cubchoo'
                        ],
                        destacados:[{name: 'bisharp', type: 'normal', link:'bisharp'},
                                {name:'oshawott', type:'egg', link:'https://media.giphy.com/media/hDg7AqmhGkzMiHFQer/giphy.gif'},
                                {name: 'mime-jr', type: 'swarm', link:'https://media.giphy.com/media/5goPOaLsUxMsfDIvTe/giphy.gif'},
                                {name: 'marill', type: 'safari', link:'https://media.giphy.com/media/aV92vbm8R8tZgg6Tvr/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Shroomiish: {   name:'Shroomiish',
                        rol: 'Chad',
                        medallas:['m_secret','m_huevo','m_pecador'],
                        shinys:['bellsprout','geodude'],
                        destacados:[{name: 'charizard', type: 'egg', link:'https://media.giphy.com/media/kI6DHEnVibteJcUDtY/giphy.gif'}],
                        perdidos: [],
                        vendidos: []
        },
        Silvaryl: {     name:'Silvaryl',
                        rol: 'Chad',
                        medallas:['m_gomed','m_raceL','m_pecador','m_apostol','m_olimpiadas'],
                        shinys:['vanilluxe','haxorus','ledian','tyranitar'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Snip: {         name:'Snip',
                        rol: 'Chad',
                        medallas:['m_secret','m_suertudo','m_abuelo','m_raza','m_apostol','m_olimpiadas'],
                        shinys:['reuniclus','nidorina','chandelure','smeargle','rapidash','woobat','haxorus','beautifly','muk','fraxure','magikarp','hydreigon','krokorok','swoobat','weezing','psyduck','steelix','amoonguss',
                                'bronzor','banette','onix','onix','timburr','tympole'
                        ],
                        destacados:[{name: 'woobat', type: 'secret', link:'https://media.giphy.com/media/te7Adm14Tbgp65TnjB/giphy.gif'}],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/g6kCi54TtATJcjgnUj/giphy.gif']
        },
        SorlanNorfleet: {name:'SorlanNorfleet',
                        rol: 'Chad',
                        medallas:['m_elegido'],
                        shinys:['mienshao','liepard'],
                        destacados:[{name: 'gyarados', type: 'alpha', link:'https://media.giphy.com/media/Y3xTFbUukABDjtMNhp/giphy.gif'}],
                        perdidos: [],
                        vendidos: []
        },
        Souen: {        name:'Souen',
                        rol: 'Lider',
                        medallas:['m_gomed','m_lider','m_guardian','m_meditite','m_swarm','m_secret','m_pescador','m_raceL','m_suertudo','m_racha','m_sequia','m_abuelo','m_huevo','m_raza','m_pecador','m_apostol','m_olimpiadas'],
                        shinys:['pidgeot','chandelure','ditto','amoonguss','scolipede','ninetales','crobat','arcanine','rapidash','golem','roserade','slugma','crobat','graveler','rapidash','weezing','tentacruel','ditto',
                                'shellos-east','bibarel','kricketune','oddish','bibarel','misdreavus','smeargle','woobat','mienshao','jellicent-f','nidoking','luxio','meditite','cubchoo','cryogonal','petilil','rapidash'
                        ],
                        destacados:[{name: 'octillery', type: 'normal', link:'octillery'},
                                {name: 'dragonite', type: 'swarm', link:'https://media.giphy.com/media/MtbA3WQ8H564xigCqN/giphy.gif'},
                                {name: 'breloom', type: 'egg', link:'https://media.giphy.com/media/BuHDxkzqmEhtCIzaLE/giphy.gif'},
                                {name: 'gastrodon', type: 'secret', link:'https://media.giphy.com/media/hWAgtS6Wjh2OL9d71b/giphy.gif'},
                                {name: 'graveler', type: 'secret', link:'https://media.giphy.com/media/yxz6b5ZmjyR3bTEF44/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Suzuya:         {name:'Suzuya',
                        rol: 'Chad',
                        medallas:['m_suertudo','m_mundo','m_pecador'],
                        shinys:['cubchoo','alakazam','rhyhorn','torkoal','pikachu','stunky','lunatone','tyranitar','garchomp','phanpy','hoppip','krookodile','hydreigon','magmortar','koffing','honchkrow','nidoran-f','mawile'],
                        destacados:[],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/TWlNAIDfpw23BhIogu/giphy.gif']
        },
        TheJesucristian: {name:'TheJesucristian',
                        rol: 'Chad',
                        medallas:['m_gomed','m_suertudo','m_rare','m_huevo','m_mundo','m_raza','m_apostol'],
                        shinys:['golbat','crobat','mienshao','manectric','rapidash','magikarp','gyarados','tentacruel','swoobat','mamoswine','altaria','horsea','slugma','magcargo','duskull','lunatone','raticate','rattata',
                                'ditto','sandshrew','amoonguss','dodrio','mismagius','flygon','murkrow','tyranitar','hydreigon','chandelure','vanilluxe','whimsicott','smeargle','gliscor','spinda','krookodile','haxorus',
                                'zubat','graveler','graveler','sableye','pikachu'
                        ],
                        destacados:[{name: 'feraligatr', type: 'normal', link:'feraligatr'},
                                {name: 'metagross', type: 'egg', link:'https://media.giphy.com/media/nUM3Kz42e3MZIkWuiv/giphy.gif'},
                                {name: 'absol', type: 'egg', link:'https://media.giphy.com/media/85gvugRYucFsnkUNOZ/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        ToddGold: {   name:'ToddGold',
                        rol: 'Chad',
                        medallas:['m_raceW','m_apostol'],
                        shinys:['weavile','dragonair','kingdra','azumarill','ampharos','miltank','reuniclus'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        ToxicPlumber: { name:'ToxicPlumber',
                        rol: 'GigaChad',
                        medallas:['m_gomed','m_guardian','m_meditite','m_safari','m_dead','m_secret','m_pescador','m_suertudo','m_huevo','m_arbol','m_raza','m_apostol','m_olimpiadas','m_aniMeD'],
                        shinys:['krookodile','raticate','venipede','weezing','nidoqueen','quagsire','altaria','kingdra','pichu','rattata','seaking','machamp','smeargle','gengar','chandelure','pidgey','ferrothorn','aggron',
                                'pelipper','scolipede','swellow','petilil','graveler','whismur','taillow','grimer','alakazam','crobat','marowak','noctowl','beautifly','reuniclus','rapidash','venonat','tentacruel','zubat',
                                'gigalith','vileplume','maractus','manectric','marowak','xatu','gyarados','baltoy','voltorb','lunatone','tyranitar','spinda','raticate','trubbish'
                        ],
                        destacados:[{name: 'combee', type: 'normal', link:'combee'},
                                {name: 'corphish', type: 'normal', link:'corphish'},
                                {name: 'metagross', type: 'normal', link:'metagross'},
                                {name: 'starmie', type: 'egg', link:'https://media.giphy.com/media/9GOx2u2i4ejAC7rF8p/giphy.gif'},
                                {name: 'swallot', type: 'egg', link:'https://media.giphy.com/media/0xJcdmbclOlUmG0HGL/giphy.gif'},
                                {name: 'marill', type: 'secret', link:'https://media.giphy.com/media/Xb6XTWhgzk9sa1PPwW/giphy.gif'},
                                {name: 'gliscor', type: 'secret', link:'https://media.giphy.com/media/ezbIutaZL5gHj2yroq/giphy.gif'}
                        ],
                        perdidos: ['https://media.giphy.com/media/h20dDuV1nQ3syyCMeu/giphy.gif'],
                        vendidos: []
        },
        Tyrantrum: {    name:'Tyrantrum',
                        rol: 'Chad',
                        medallas:['m_elegido','m_pecador','m_apostol','m_supremacy2'],
                        shinys:['drifblim','donphan','arbok','druddigon','roselia','tentacool','cubchoo','cryogonal','raticate'],
                        destacados:[{name: 'totodile', type: 'normal', link:'totodile'},
                                {name: 'sudowoodo', type: 'alpha', link:'https://media.giphy.com/media/da60GIUj74BHRR9Px5/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        UltimoMorador: {name:'UltimoMorador',
                        rol: 'Chad',
                        medallas:['m_shunter','m_suertudo','m_apostol'],
                        shinys:['bellossom','escavalier','litwick','donphan','machamp','graveler','graveler','weezing','dodrio','hariyama','masquerain','igglybuff','snubbull','mantyke','clamperl','marill','boldore','scraggy',
                                'tranquill','wobbuffet','smoochum','patrat','persian','sawk','xatu','makuhita','joltik','stoutland','cubchoo'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        vitro: {        name:'vitro',
                        rol: 'Chad',
                        medallas:['m_dead','m_pecador','m_supremacy2'],
                        shinys:['magikarp','nidoking'],
                        destacados:[],
                        perdidos: ['https://media.giphy.com/media/4usxGoNyYaW4iTubxf/giphy.gif',
                                'https://media.giphy.com/media/QbwsfAawOZMWOA9mDd/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        wallycbammo: {  name:'wallycbammo',
                        rol: 'Chad',
                        medallas:['m_apostol','m_shinywar'],
                        shinys:['pelipper','wurmple','wooper','venipede','tentacruel'],
                        destacados:[{name:'shedinja', type:'normal',link:'shedinja'}],
                        perdidos: [],
                        vendidos: []
        },
        xDerxx: {       name:'xDerxx',
                        rol: 'Chad',
                        medallas:['m_apostol'],
                        shinys:['wooper','walrein','graveler','jigglypuff','rapidash','jellicent','cofagrigus'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        xSorC: {        name:'xSorC',
                        rol: 'Chad',
                        medallas:['m_vacio'],
                        shinys:['duosion','bronzor'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        YuukiTwo: {     name:'YuukiTwo',
                        rol: 'MaxiChad',
                        medallas:['m_gomed','m_cambio','m_guardian','m_pescador','m_huevo','m_pecador','m_apostol'],
                        shinys:['beedrill','sawsbuck','vileplume','nidoking','rhyperior','ninetales'],
                        destacados:[{name: 'crawdaunt', type: 'normal', link:'crawdaunt'},
                                {name: 'skorupi', type: 'egg', link:'https://media.giphy.com/media/X7GjW3K9Sq3BOVQljZ/giphy.gif'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/ofHxoizb5ZyN3uvFU6/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/LWm8fjHUKxqb0qyZpD/giphy.gif'
                        ]
        },
        Zeurir: {       name:'Zeurir',
                        rol: 'Chad',
                        medallas:['m_dead','m_pecador'],
                        shinys:['ninetales','pelipper','quagsire'],
                        destacados:[],
                        perdidos: ['https://media.giphy.com/media/QbwsfAawOZMWOA9mDd/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/7eBAfbvAahCmhTreRI/giphy.gif',
                                'https://media.giphy.com/media/joRe8SDxlxpAZOQ8VQ/giphy.gif'
                        ]
        },
        zShilphye: {    name:'zShilphye',
                        rol: 'Chad',
                        medallas:['m_pecador'],
                        shinys:['stantler','mamoswine','dodrio','golbat','tentacruel','duskull','ponyta','mienfoo','scrafty','onix','rapidash','durant','mienfoo'],
                        destacados:[],
                        perdidos:[],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif']
        }
        
    };

function capitalize(str) {
        return str.charAt(0).toUpperCase() + str.slice(1);
}