const listaMedalla = {
  b0: {name: 'vacío', info: '...'},
  b1: {name: '🎮 Go MeD', info:'Tienes 1 año o mas en el team'},
  b2: {name: '💰 Quédate el cambio', info: 'Has donado 10m o mas al banco del team de una sola vez'},
  b3: {name: '🧩 Pieza clave', info: 'Formas parte de los miembros fundadores del team'},
  b4: {name: '👑 Dictador', info: 'Has sido líder de MeD'},
  b5: {name: '💂 Guardián', info: 'Has kickeado a alguien de MeD'},
  b6: {name: '🧘 Cuerpo y mente', info: 'Has obtenido un shiny Meditite'},
  b7: {name: '🎲 De vida o muerte', info: 'Has capturado un shiny en la Zona Safari'},
  b8: {name: '🗺️ Tour por el mundo', info: 'Has obtenido un shiny de swarm'},
  b9: {name: '💔 Desafortunado', info: 'Has perdido un shiny durante un encuentro'},
  b10: {name: '🌟 Top secret', info: 'Has obtenido un shiny secret (salvaje)'},
  b11: {name: '📆 Shunter del mes', info: 'Has capturado la mayor cantidad de shinys en un mes'},
  b12: {name: '🎣 Maestro pescador', info: 'Has obtenido un shiny pescando'},
  b13: {name: '🥇 Race winner', info: 'Has ganado una shiny race'},
  b14: {name: '🥈 Fail race', info: 'Has obtenido una fase buscando el shiny de la race'},
  b15: {name: '🍀 Suertudo', info: 'Has obtenido 2 o mas shiny en 1 día (24h o menos)'},
  b16: {name: '💫 Enrachado', info: 'Has obtenido un shiny en 3 o mas días seguidos'},
  b17: {name: '🛐 El elegido', info: 'Has obtenido un shiny alpha o legendario'},
  b18: {name: '👴 Paciencia de abuelo', info: 'Has obtenido 3 o mas fases buscando un shiny'},
  b19: {name: '🧬 Raza perfecta', info: 'Has obtenido un shiny por crianza'},
  b20: {name: '❔Misterio resuelto', info: 'Has obtenido un shiny de una Ball Misteriosa'},
  b21: {name: '🦖Arqueólogo', info: 'Has obtenido un fósil shiny'},
  b22: {name: '🌳Arborista', info: 'Has obtenido un shiny de golpe cabeza/árbol de miel'},
  b23: {name: '📦 Golden box', info: 'Has obtenido una caja llena (60) de shinys'},
  b24: {name: '👿 Pecador', info: 'Has vendido, liberado o regalado un shiny'},
  b25: {name: '🎀 Shiny completo', info: 'Has obtenido un shiny que posee todas las cintas'},
  b26: {name: '📝Apóstol', info: 'Has registrado una nueva especie en la Shiny Dex de MeD'},
  b27: {name: '🎫 Built different', info: 'Has obtenido un shiny ganando un torneo o evento oficial'},
  b28: {name: '🌱 MeD Supremacy 1', info: 'Formaste parte del equipo ganador de la MeD Supremacy 1'},
  b29: {name: '🏆 Winners PokeLympics 2024', info: 'Formaste parte del equipo ganador de las PokeLympics 2024'},
  b30: {name: '🅿️ MeD Supremacy 2', info: 'Formaste parte del equipo ganador de la MeD Supremacy 2'},
  b31: {name: '🎉 AniMeDsario 2025', info: 'Formaste parte de los ganadores del evento del AniMeDsario 2025'},
  b32: {name: '☠️ Pecador supremo', info: 'elegido como el mayor pecador del equipo'}
};

const memberData = {
        AdrixJK: {      name:'AdrixJK',
                        rol: 'Chad',
                        medallas:['b9','b10','b15','b24','b26','b32'],
                        shinys:[],
                        destacados:[],
                        vendidos: []
        },
        aeamanh: {      name:'aeamanh',
                        rol: 'MaxiChad',
                        medallas:['b10','b14','b15','b26','b29'],
                        shinys:['donphan','sandslash','scolipede','raticate','tangrowth','spinda','raticate','magneton','mienfoo','frillish-f','smeargle','nidoking','ditto','grimer',
                                'chandelure','leavanny','primeape','ditto','deino','snover','bibarel','quagsire','bellossom','weezing','durant','cryogonal','rapidash','pelipper','altaria',
                                'politoed','duskull','duosion','mightyena','gliscor','gyarados','amoonguss'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/gulpin.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/pansage.gif',
                                'https://media.giphy.com/media/ELEoC52RYPBnz8Vf4s/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/vxRM9XurU5lvpae8Ko/giphy.gif']
        },
        AkaliWard: {    name:'AkaliWard',
                        rol: 'Chad',
                        medallas:['b1','b4','b5','b10','b12','b14','b15','b24','b26'],
                        shinys:['tyranitar','horsea','duskull','mienshao','sharpedo','ninetales','poochyena','beedrill','cottonee','slugma','wooper','azumarill','gyarados','shinx','snorunt',
                                'weavile','axew','pachirisu','lanturn','cottonee','torkoal','gible','jumpluff','weezing','bibarel','vulpix','loudred'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/gulpin.gif',
                                'https://media.giphy.com/media/KHJMmSNa171LNWJOPK/giphy.gif'
                        ],
                        vendidos: ['https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZW54bXF1OWhocTF3cHMzd3lyMmd2MW5xdTFpNWxucmRkbjlhcjI2ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHBxbzBvM2k5OGFpZXJsMHQ4dzk5NGxteW42NXk3N3IyNjEwaXNnYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ubXLD0w80oZjtsrIUH/giphy.gif',
                                'https://media.giphy.com/media/PMMrLwzj3iqyMtpxQs/giphy.gif',
                                'https://media.giphy.com/media/A2NlfU2OIPj0GAVoJy/giphy.gif',
                                'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXY3dXh2MnNsZHQyYjNzdHE3MmpqMnI5dnoxeDU1cW40cTAyMmc3NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ptSTYVxdNLH5oH4Siw/giphy.gif'
                        ]
        },
        AlexisBlu: {    name:'AlexisBlu',
                        rol: 'MegaChad',
                        medallas:['b19','b21','b26','b29'],
                        shinys:['haxorus','weavile','camerupt','gyarados','swoobat','zigzagoon','cubone'],
                        destacados:['https://media.giphy.com/media/kI6DHEnVibteJcUDtY/giphy.gif',
                                'https://media.giphy.com/media/sP3E4z0rFHUtZ7gd9x/giphy.gif'],
                        vendidos: []
        },
        AnderHacks: {   name:'AnderHacks',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['mienshao','camerupt','wooper','psyduck','durant'],
                        destacados:[],
                        vendidos: []
        },
        AshbellUwU: {   name:'AshbellUwU',
                        rol: 'GigaChad',
                        medallas:['b10','b12','b24','b30'],
                        shinys:['drifblim','dratini','raticate','gardevoir','duskull','marill','smeargle','scolipede','zangoose','staravia','bellossom','gloom','lanturn','golett'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/carvanha.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/breloom.gif',
                                'https://media.giphy.com/media/4fOM1fIVBlAM7xh90c/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/nmviuh9fVteaRspu6U/giphy.gif']
        },
        AsuraSkyFlames: {name:'AsuraSkyFlames',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['amoonguss','druddigon','beedrill','beedrill','klinklang','crobat','galvantula'],
                        destacados:[],
                        vendidos: []
        },
        Azathotx: {     name:'Azathotx',
                        rol: 'Chad',
                        medallas:['b8','b14','b26','b29'],
                        shinys:['lotad','cacnea','dustox','cinccino','bidoof','mismagius','gastrodon','mienfoo','spinda','venomoth','vanillish','golduck','camerupt','boldore','dugtrio',
                                'smeargle','dusclops','weezing','parasect','scolipede','beedrill'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/kecleon.gif',
                                'https://media.giphy.com/media/ggxHTXdRvXKT0VgZ1V/giphy.gif'
                        ],
                        vendidos: []
        },
        CeceMerdosa: {  name:'CeceMerdosa',
                        rol: 'MaxiChad',
                        medallas:['b4','b6','b30'],
                        shinys:['sneasel','meditite','luxio','girafarig','wingull','magmar','deerling','golett'],
                        destacados:[],
                        vendidos: []
        },
        Cenoa: {        name:'Cenoa',
                        rol: 'Chad',
                        medallas:['b17','b26','b30'],
                        shinys:['drifblim','donphan'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/totodile.gif',
                                'https://media.giphy.com/media/da60GIUj74BHRR9Px5/giphy.gif'
                        ],
                        vendidos: []
        },
        DavidCitos: {   name:'DavidCitos',
                        rol: 'Chad',
                        medallas:['b10','b11','b15','b16','b18','b23','b26','b28','b29','b30'],
                        shinys:['lopunny','marill','trapinch','roserade','vulpix','hydreigon','magmar','poliwag','swablu','meowth','gyarados','grimer','weezing','weavile','pikachu','psyduck','mareep','miltank',
                                'litwick','duskull','jigglypuff','electabuzz','rapidash','natu','wobbuffet','accelgor','banette','sealeo','vanilluxe','ferroseed','woobat','poliwhirl','parasect','magnezone','hoppip',
                                'mienfoo','rhydon','hariyama','voltorb','smeargle','onix','electrike','magcargo','solrock','poliwhirl','gurdurr','graveler','watchog','mareep','gligar','hypno','cubchoo','swoobat','woobat',
                                'shinx','lanturn','bronzong','stunfisk','dugtrio','palpitoad','donphan','ursaring','snover','tranquill','cofagrigus','basculin','bronzong','horsea','magikarp','krokorok','woobat','axew',
                                'golbat','mankey','girafarig','lunatone','gloom','fearow','gloom','lunatone','spinda','golduck','machoke','lombre'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/treecko.gif',
                                'https://media.giphy.com/media/g7C0f00QAimyUAMsYd/giphy.gif'
                        ],
                        vendidos: []
        },
        Davinchy: {     name:'Davinchy',
                        rol: 'Chad',
                        medallas:['b20'],
                        shinys:['exploud','gallade','amoonguss','durant','banette','rapidash','ditto','poliwrath','darumaka','haunter','ditto','heatmor','arcanine','poliwrath','beedrill','ralts','raticate','meowth','sawk',
                                'gothitelle','deino','cubchoo','vanilluxe','petilil','diglett','stantler','noctowl','nidorino','venipede'],
                        destacados:[],
                        vendidos: []
        },
        DiGoMo: {       name:'DiGoMo',
                        rol: 'MegaChad',
                        medallas:['b15','b24','b26','b29','b30'],
                        shinys:['muk','cascoon','spearow','pidgeotto','magby','pelipper','raticate','ponyta','tynamo','raticate','chandelure','poliwrath','spinda','parasect','smeargle','banette','ponyta','weezing','raticate',
                                'murkrow','joltik'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/breloom.gif'],
                        vendidos: ['https://media.giphy.com/media/GpMgr8p0p13wASvhVk/giphy.gif',
                                'https://media.giphy.com/media/y9dID1S7X6zTE330td/giphy.gif',
                                'https://media.giphy.com/media/CNOYDXXMeqrcpEhIE1/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        Dohrito: {      name:'Dohrito',
                        rol: 'Chad',
                        medallas:['b6','b10','b11','b14','b30'],
                        shinys:['medicham','beedrill','gliscor','jynx','marill','wooper','sealeo','magikarp','rapidash','rapidash','dratini','electrike','stunfisk','druddigon','poliwag','swablu','wingull','pelipper','psyduck',
                                'hypno','amoonguss','dunsparce','cubchoo','beartic','cryogonal','vanillite','vanillish','vanilluxe','crustle','grimer','torkoal','litwick','camerupt','magnezone','mareep','tentacruel','wurmple',
                                'wurmple','weezing','vulpix','accelgor','shuppet','lopunny','teddiursa','quagsire','smeargle','spinarak','slugma'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/pinsir.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/cherubi.gif',
                                'https://media.giphy.com/media/b3VLSA5czIMhv6WOKp/giphy.gif',
                                'https://media.giphy.com/media/RFG3g6MyN5VpGHSqkK/giphy.gif'

                        ],
                        vendidos: ['https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc281Y3cxbTRlNGY1YnVwYXFsMzM4Z3FudW1uYWMxZzJrZjcybGt1OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/xbpVD0pTXBBJVkgUKP/giphy.gif']
        },
        DrMaicol: {     name:'DrMaicol',
                        rol: 'Chad',
                        medallas:['b9','b19','b26','b30'],
                        shinys:['ludicolo','larvitar','steelix','venipede','chandelure','smeargle','magikarp','gyarados','cubchoo','cacnea','alakazam'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/breloom.gif',
                                'https://media.giphy.com/media/71JqlJebXFCWBdw4j4/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/xApUnnnPV5cJhTqy2c/giphy.gif',
                                'https://media.giphy.com/media/7uxLPTrZZAl2HjGG9y/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/bsxtXWvus1jvqHDZA7/giphy.gif'
                        ]
        },
        ElMasterFox: {  name:'ElMasterFox',
                        rol: 'Chad',
                        medallas:['b9','b10','b19','b12','b26','b30'],
                        shinys:['butterfree','raticate','parasect','venomoth','golem','rapidash','kingler','ditto','dunsparce','kingdra','exploud','altaria','lunatone','huntail','gigalith','leavanny','lilligant',
                                'crustle','cinccino','gothitelle','vanilluxe','sawsbuck','galvantula','haxorus','accelgor','golurk','bouffalant','durant','chandelure','tyranitar'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/corsola.gif',
                                'https://media.giphy.com/media/agBIyJ5VezN1rEyAH7/giphy.gif',
                                'https://media.giphy.com/media/eCSsSbLABW1K8BMlrG/giphy.gif',
                                'https://media.giphy.com/media/S14AkMdwMqLPtXwyTB/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/GB3mLVQZvNawNjVxRT/giphy.gif']
        
        },
        ElMiga: {       name:'ElMiga',
                        rol: 'MegaChad',
                         medallas:['b1','b10','b14','b24','b26','b30'],
                        shinys:['poochyena','staraptor','zigzagoon','larvitar','roserade','raticate'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/jolteon.gif',
                                'https://media.giphy.com/media/3lzuIyWvEzHmmgIFp7/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/EZvvoZS947Meh0bo2E/giphy.gif',
                                'https://media.giphy.com/media/gSUVBePKqAbJpmfIoA/giphy.gif',
                                'https://media.giphy.com/media/cPHoY81t2gnlZ8kqg5/giphy.gif',
                                'https://media.giphy.com/media/xLXn3LWXz0X7vL1Gsd/giphy.gif',
                                'https://media.giphy.com/media/xLXn3LWXz0X7vL1Gsd/giphy.gif'
                        ]
        },
        Estorbiito: {   name:'Estorbiito',
                        rol: 'Chad',
                        medallas:['b15','b18'],
                        shinys:['smeargle','beedrill','haxorus','poliwrath','weavile','banette','weezing','amoonguss','spinda','ditto'],
                        destacados:[],
                        vendidos: []
        },
        FranCRLZ: {     name:'FranCRLZ',
                        rol: 'Chad',
                        medallas:['b15'],
                        shinys:['horsea','pikachu','graveler','venipede','kakuna','oddish','krookodile'],
                        destacados:[],
                        vendidos: []
        },
        Guabixd: {      name:'Guabixd',
                        rol: 'Chad',
                        medallas:['b16','b24','b26'],
                        shinys:['bibarel'],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/0vF7t16ROOFeGekWcF/giphy.gif',
                                'https://media.giphy.com/media/dlxXpY9xfkQ1OuNIux/giphy.gif',
                                'https://media.giphy.com/media/2AcQyIAzpCLU22J9ps/giphy.gif',
                                'https://media.giphy.com/media/R0MfWMPIGXgWZgF5gG/giphy.gif',
                                'https://media.giphy.com/media/JV7Psnvy4K5rl24OMw/giphy.gif',
                                'https://media.giphy.com/media/olvnpZMLJ9Thfm9Vo7/giphy.gif',
                                'https://media.giphy.com/media/PMMrLwzj3iqyMtpxQs/giphy.gif',
                                'https://media.giphy.com/media/3Z43q20eTxPd3flPxV/giphy.gif',
                                'https://media.giphy.com/media/y4R16mDezBPthJ6eHQ/giphy.gif'

                        ]
        },
        HoraxPc: {      name:'HoraxPc',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['haxorus','klink','klinklang','chandelure'],
                        destacados:[],
                        vendidos: []
        },
        IgnacioCZ: {    name:'IgnacioCZ',
                        rol: 'Chad',
                        medallas:['b24'],
                        shinys:[],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/2XolNQLvYlGqCJ1N0r/giphy.gif',
                                'https://media.giphy.com/media/vQHNb11Syu3aXoKUBz/giphy.gif'

                        ]
        },
        Jabubuu: {      name:'Jabubuu',
                        rol: 'Chad',
                        medallas:['b1','b9','b10','b11','b15','b19','b24','b26'],
                        shinys:['solrock','gastrodon','lopunny','politoed','scolipede','rattata','chandelure','bellossom','ninetales','azurill','lilligant','golem','rattata','vanillite','gorebyss','psyduck','wooper',
                                'jumpluff','escavalier','deerling','gloom','ariados','weepinbell'
                        ],
                        destacados:['https://media.giphy.com/media/HpSnC62YvwsymoUU0o/giphy.gif',
                                'https://media.giphy.com/media/qxLS97I8yoUYRzSdIj/giphy.gif',
                                'https://media.giphy.com/media/5XY7dRvTVNprm5Givp/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/JLXanaUxCRYzlAEKWp/giphy.gif',
                                'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDFwaGc5MmNwMWgyMmNkdmwyOG9wenoyNGYxanF1b3BreTVsbzg2dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/WwQzqNsYX0l6SgCQZV/giphy.gif'
                        ]
        },
        JackLoquinn: {  name:'JackLoquinn',
                        rol: 'Chad',
                        medallas:['b24'],
                        shinys:['wurmple','cinccino'],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/822MTo2BKJqejpx8is/giphy.gif'
                        ]
        },
        JCancelo: {     name:'JCancelo',
                        rol: 'Chad',
                        medallas:['b24'],
                        shinys:['rapidash','magikarp','litwick'],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif'
                        ]
        },
        JJeam: {        name:'JJeam',
                        rol: 'Chad',
                        medallas:['b10','b19','b23','b26','b30','b31'],
                        shinys:['golurk','tyranitar','lanturn','haxorus','aggron','pidove','haunter','steelix','darmanitan','magikarp','gyarados','gyarados','gorebyss','altaria','ferrothorn','grimer','grimer','muk',
                                'chandelure','wooper','quagsire','accelgor','torkoal','geodude','tentacool','duskull','dusclops','marill','camerupt','vanillite','vanilluxe','poliwrath','politoed','miltank','ponyta',
                                'ponyta','rapidash','kingdra','ludicolo','druddigon','weavile','krookorok','psyduck','gigalith','electrike','hydreigon','mienshao','ampharos','wingull','weezing','smeargle','banette',
                                'spinda','braviary','magneton','pikachu','whismur'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/pinsir.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/breloom.gif',
                                'https://media.giphy.com/media/nUM3Kz42e3MZIkWuiv/giphy.gif',
                                'https://media.giphy.com/media/mGgghAuoGKJeWg2B0v/giphy.gif',
                                'https://media.giphy.com/media/sonHNRtZEAI8bKerAX/giphy.gif',
                                'https://media.giphy.com/media/s9iQ0TQppj5vj8COtm/giphy.gif'
                        ],
                        vendidos: []
        },
        JosiasMccartney: {name:'JosiasMccartney',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['fearow','arbok','tentacool','rapidash','gothorita','poliwhirl','woobat','meowth','ponyta','gengar','gyarados','kingdra','smeargle','rhydon','mienshao','chandelure','camerupt'],
                        destacados:[],
                        vendidos: []
        },
        JuniorMx: {     name:'JuniorMx',
                        rol: 'GigaChad',
                        medallas:['b6','b12','b14','b15','b16','b26','b23','b31'],
                        shinys:['tentacruel','tentacruel','watchog','kricketune','golduck','smeargle','banette','weezing','torkoal','pelipper','petilil','gothitelle','graveler','vanilluxe','chandelure','rhyperior',
                                'ponyta','meowth','venipede','accelgor','vulpix','bronzong','stantler','golbat','wingull','magikarp','spinda','whirlipede','lilligant','swellow','cryogonal','pidgey','piloswine',
                                'skuntank','golem','probopass','oddish','gloom','volbeat','trubbish','garbodor','trapinch','dratini','misdreavus','dusclops','tauros','cinccino','foongus','jynx','golurk','donphan',
                                'girafarig','lunatone','meditite','parasect','ditto','ditto'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/shellder.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/carvanha.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/luvdisc.gif'
                        ],
                        vendidos: []
        },
        Krackon: {      name:'Krackon',
                        rol: 'Chad',
                        medallas:['b10','b19','b26'],
                        shinys:['mienshao','gyarados','altaria','chandelure','reuniclus','crobat','pachirisu','noctowl','timburr','timburr','vanillite','luxray','primeape','quagsire','drowzee','spinda','shuppet',
                                'watchog','weezing','mienfoo','gloom','venipede','venipede','raticate','ditto','steelix','smeargle','zigzagoon','beautifly','weavile','purrloin','golbat','ninetales','golbat','kingdra',
                                'fearow'
                        ],
                        destacados:['https://media.giphy.com/media/PbdZZMpNNmIk3uTqCp/giphy.gif',
                                'https://media.giphy.com/media/xSsZ6Gwoo7SlACFFPL/giphy.gif'
                        ],
                        vendidos: []
        },
        KnowJiYong: {   name:'KnowJiYong',
                        rol: 'MaxiChad',
                        medallas:['b1','b5','b10','b11','b12','b14','b15','b19','b24','b26','b29','b30'],
                        shinys:['kakuna','tentacruel','tentacruel','tentacruel','tentacruel','slugma','banette','chandelure','camerupt','torkoal','claydol','smeargle','lanturn','gloom','bellossom','pikachu','minccino',
                                'sandshrew','psyduck','surskit','dewgong','beedrill','weezing','pelipper','krokorok','rapidash','durant','deino','glalie','abomasnow','accelgor','duskull','ditto'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/staryu.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/lumineon.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/breloom.gif',
                                'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTY3M3lhcmpkeXI4dWhhM3p6NHU1b3NwMmp1cG1wY2FvdHp6NDNlYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/8VumrMKv5zs67UtkvH/giphy.gif',
                                'https://media.giphy.com/media/lZAtjAs3Goy7Q8YT5l/giphy.gif',
                                'https://media.giphy.com/media/ssHB4elDG6T4Ri8PJA/giphy.gif'
                        ],
                        vendidos: []
        },
        LauraSkylar: {  name:'LauraSkylar',
                        rol: 'Chad',
                        medallas:['b7','b9','b15','b26'],
                        shinys:['lanturn','roserade','geodude','golem','donphan','braviary','pelipper','volbeat','sigilyph','minccino','minccino','whismur','trubbish'],
                        destacados:['https://media.giphy.com/media/iqqZaJgalqVoPITNnV/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/03cHN7rGUFZA515olc/giphy.gif',
                                'https://media.giphy.com/media/Z5eN8XmGSmU8YGqxIj/giphy.gif',
                                'https://media.giphy.com/media/nbxsygYVLvm1Z9IXpu/giphy.gif',
                                'https://media.giphy.com/media/RiSG1piNjO9VPGPjmV/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif'
                        ]
        },
        Liarfuneral: {  name:'Liarfuneral',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['dusclops','dragonite','hydreigon','bouffalant','gyarados','lilligant','chandelure','golett','ponyta'],
                        destacados:[],
                        vendidos: []
        },
        LiXriio: {      name:'LiXriio',
                        rol: 'MegaChad',
                        medallas:['b0'],
                        shinys:['ampharos','froslass','altaria','ninetales','wigglytuff','luxray','crobat','manectric','spinda','haxorus','hydreigon','ditto','garchomp','gyarados','kingdra','pikachu','krookodile',
                                'honchkrow','pelipper','gengar','chandelure','cofagrigus','banette','dusclops','delibird','magcargo','weezing','amoonguss','weavile','conkeldurr','reuniclus','mienshao','gastrodon',
                                'gastrodon-east','wynaut','gothitelle','mawile','golduck','lilligant','bellossom','jumpluff','dustox','roselia','parasect','ariados','slowbro','politoed',
                                'poliwrath','ludicolo','lanturn','nidoking','solrock','torkoal'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/unown-em.gif',
                                'https://media.giphy.com/media/9QCzuGqPrW812xEU7B/giphy.gif'
                        ],
                        vendidos: []
        },
        lRenzz: {       name:'lRenzz',
                        rol: 'Chad',
                        medallas:['b1','b5','b6','b13','b24','b26'],
                        shinys:['duosion','mismagius','ninetales','quagsire','rapidash','stunfisk','vulpix','weezing','wooper','bouffalant','horsea','kingdra','medicham'],
                        destacados:[],
                        vendidos: []
        },
        Luciferovo: {   name:'Luciferovo',
                        rol: 'MegaChad',
                        medallas:['b14','b24','b26'],
                        shinys:['roselia','mienfoo','mienshao','swoobat','solrock','mienfoo','mienfoo','wooper','swablu','stunfisk','golett'],
                        destacados:[],
                        vendidos: []
        },
        Mawilice: {     name:'Mawilice',
                        rol: 'Chad',
                        medallas:['b1','b4','b5','b15','b19','b24','b26','b28','b29','b30'],
                        shinys:['parasect','rhydon','camerupt','bronzong','vanilluxe'],
                        destacados:['https://media.giphy.com/media/nctj6wUD0o6plh95Vy/giphy.gif',
                                'https://media.giphy.com/media/EuzEj0pJDbl50OeRQ1/giphy.gif',
                                'https://media.giphy.com/media/QvBYmu8hATjJhgUuCS/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/4SabkxUjL8LmZRGsK9/giphy.gif',
                                'https://media.giphy.com/media/v9IOxgCRm5BbGXEUEG/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/TvZULFmyJBHodh9Py0/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/jz9aaVnHL7w4V8cX9R/giphy.gif',
                                'https://media.giphy.com/media/GewTzo5C9FI68FMJol/giphy.gif',
                                'https://media.giphy.com/media/7B05VelRsf0qfQptsT/giphy.gif'
                        ]
        },
        MangoOscuro: {  name:'MangoOscuro',
                        rol: 'Chad',
                        medallas:['b1','b8','b26'],
                        shinys:['spinda','nidoking','spinarak','poliwrath','weedle','scrafty'],
                        destacados:['https://media.giphy.com/media/4UZxfBHHPVtzNGkt2o/giphy.gif'],
                        vendidos: []
        },
        MarkosW: {      name:'MarkosW',
                        rol: 'GigaChad',
                        medallas:['b9','b29','b30'],
                        shinys:['sunflora','litwick','cryogonal','beedrill','ponyta','smeargle','koffing','tentacruel','psyduck'],
                        destacados:[],
                        vendidos: ['https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDQzM2g0YjNjaDIwNjF6ODl0MTV5ZHRyc2UzdWZpYTBkamE1bjZ5aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/xIpPVNVgAxrr7mfHV2/giphy.gif']
        },
        Mdbzp: {        name:'Mdbzp',
                        rol: 'Chad',
                        medallas:['b12','b15','b26'],
                        shinys:['onix','chandelure','gliscor','banette','gyarados','smeargle','exploud','tentacruel'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/luvdisc.gif'],
                        vendidos: []
        },
        Mikuwuu: {      name:'Mikuwuu',
                        rol: 'GigaChad',
                        medallas:['b11','b12','b13','b19','b26'],
                        shinys:['gyarados','ninetales','girafarig'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/delcatty.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/milotic.gif'
                        ],
                        vendidos: []
        },
        Mittoh: {       name:'Mittoh',
                        rol: 'GigaChad',
                        medallas:['b24','b29','b30'],
                        shinys:['litwick','meowth','deino','purugly','duosion','ninetales','bibarel','bibarel','petilil','donphan','golett','vanilluxe','magikarp','mankey','murkrow'],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/WBCKmSHx1P3rtJeWFe/giphy.gif',
                                'https://media.giphy.com/media/WBCKmSHx1P3rtJeWFe/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        MixZeppeli: {   name:'MixZeppeli',
                        rol: 'Chad',
                        medallas:['b13','b15','b19','b30'],
                        shinys:['ninetales','beedrill','teddiursa','golbat','weavile','lilligant','politoed','gothitelle','vanillish','purugly','bouffalant','shinx','purrloin'],
                        destacados:['https://media.giphy.com/media/85gvugRYucFsnkUNOZ/giphy.gif'],
                        vendidos: []
        },
        Moonlyze: {     name:'Moonlyze',
                        rol: 'MaxiChad',
                        medallas:['b6','b9','b18','b24','b26'],
                        shinys:['smeargle','weezing','ninetales','wigglytuff','magikarp','ditto','bibarel','whismur'],
                        destacados:[],
                        vendidos: [ 'https://media.giphy.com/media/WMaKtMeEQ0nbIBSXL3/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/VW7acYe1rLsGN7fkec/giphy.gif',
                                'https://media.giphy.com/media/cEYKWJiZtqVfvWoy8n/giphy.gif',
                                'https://media.giphy.com/media/Cf3jlPlB66Clh0QAlB/giphy.gif',
                                'https://media.giphy.com/media/XJG6BYtBosorvy0vBF/giphy.gif',
                                'https://media.giphy.com/media/jPuEQEPogo9ZbPJHRQ/giphy.gif',
                                'https://media.giphy.com/media/jPuEQEPogo9ZbPJHRQ/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/m8tGRCtwerALjP9fnz/giphy.gif',
                                'https://media.giphy.com/media/m8tGRCtwerALjP9fnz/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/wgoVjRL6nzlW7JToaD/giphy.gif',
                                'https://media.giphy.com/media/F6yoZWYZ6rf1fJyUEY/giphy.gif',
                                'https://media.giphy.com/media/LWm8fjHUKxqb0qyZpD/giphy.gif',
                                'https://media.giphy.com/media/822MTo2BKJqejpx8is/giphy.gif',
                                'https://media.giphy.com/media/e6ZkFqt8nd84QuSEbP/giphy.gif'
                        ]
        },
        MusTam: {       name:'MusTam',
                        rol: 'Chad',
                        medallas:['b7','b9','b18','b24'],
                        shinys:['pidgeot','persian','ludicolo','mantine','altaria','smeargle','hoothoot','poochyena','meowth','beautifly','wingull','jumpluff'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/furret.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/sceptile.gif',
                                'https://media.giphy.com/media/GKVQ6Xdjm9DDDIb63C/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/BYhOYqM8qaER7ukxVW/giphy.gif',
                                'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDR5Nm12eG9lNDM5Y3VoeWN1ZHVwcTFmYXJsYml1YW1hZDN0N3hodCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/DNXSProoe7z5LX0l7h/giphy.gif',
                                'https://media.giphy.com/media/lAcpPVwrBgQfMfBHlD/giphy.gif',
                                'https://media.giphy.com/media/T2bUB6ZHTIO3fxlH11/giphy.gif',
                                'https://media.giphy.com/media/FF9MGEFeqTS4Mn2vAJ/giphy.gif',
                                'https://media.giphy.com/media/13ZtgbQM9NwuIjtoyN/giphy.gif',
                                'https://media.giphy.com/media/rAa3yXQEgFsN72fvoY/giphy.gif',
                                'https://media.giphy.com/media/rAa3yXQEgFsN72fvoY/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/EQIOBvPaS0RoyW6P2J/giphy.gif',
                                'https://media.giphy.com/media/vgltunPjQb3mMh3pYq/giphy.gif'
                        ]
        },
        Mxxarc: {       name:'Mxxarc',
                        rol: 'Chad',
                        medallas:['b19','b26','b28','b29'],
                        shinys:['mienshao','flygon','nidoran-f','chandelure','ninetales','muk','lanturn','altaria','seismitoad','smeargle','druddigon','kingdra','gyarados','joltik'],
                        destacados:['https://media.giphy.com/media/EuzEj0pJDbl50OeRQ1/giphy.gif'],
                        vendidos: []
        },
        nyumischaleis: {name:'nyumischaleis',
                        rol: 'Chad',
                        medallas:['b10','b15','b18','b26','b29'],
                        shinys:['tentacruel','bouffalant','rapidash','ponyta','weedle','cottonee','scolipede','buneary','cascoon','dustox','steelix','slugma','bibarel','wurmple','silcoon'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/zorua.gif',
                                'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTR4MDgyYzNpejJicGR6dGJqYnFvYmpibjc2ejd6NmlyeWZtdHNhdCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/A9lxfTVpkbM0x68HlH/giphy.gif',
                                'https://media.giphy.com/media/4fOM1fIVBlAM7xh90c/giphy.gif'
                        ],
                        vendidos: []
        },
        OniED: {        name:'OniED',
                        rol: 'Chad',
                        medallas:['b10','b12','b24'],
                        shinys:['weavile','tentacruel','amoonguss','sandslash','gligar','grimer','koffing','meowth','poochyena','zigzagoon','pelipper','wingull','mienshao','ditto','accelgor','ledyba','hoothoot'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/remoraid.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/slakoth.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/shroomish.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/pawniard.gif',
                                'https://media.giphy.com/media/g9HysJkxwY4NjKzrjg/giphy.gif',
                                'https://media.giphy.com/media/KtpRlWqgvUC1uBAJbI/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/3XWhYuF1IEcTsDBJXD/giphy.gif',
                                'https://media.giphy.com/media/tILTB4DTScZ7Sd5PIP/giphy.gif',
                                'https://media.giphy.com/media/7B05VelRsf0qfQptsT/giphy.gif',
                                'https://media.giphy.com/media/D3Lvv8nOqyVEkRFrWZ/giphy.gif',
                                'https://media.giphy.com/media/ofHxoizb5ZyN3uvFU6/giphy.gif',
                                'https://media.giphy.com/media/Lk4bupthAXzZiYNLPx/giphy.gif',
                                'https://media.giphy.com/media/juwTFb2dmySsKb2N3b/giphy.gif',
                                'https://media.giphy.com/media/juwTFb2dmySsKb2N3b/giphy.gif',
                                'https://media.giphy.com/media/25US6QyxVKt91tanHm/giphy.gif',
                                'https://media.giphy.com/media/25US6QyxVKt91tanHm/giphy.gif',
                                'https://media.giphy.com/media/DTGNzyLWgweQqRRGJ4/giphy.gif',
                                'https://media.giphy.com/media/DTGNzyLWgweQqRRGJ4/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif'
                        ]
        },
        OreganoPVP: {   name:'OreganoPVP',
                        rol: 'Chad',
                        medallas:['b10','b13','b19','b26','b29'],
                        shinys:['gardevoir','tentacruel','nidoking','crobat','bouffalant','sandslash','beheeyem','azumarill','drifblim','rhyperior','hariyama','solrock','rapidash','persian','mantine'],
                        destacados:['https://media.giphy.com/media/tbC1NEwy3G4QZ3ng7t/giphy.gif',
                                'https://media.giphy.com/media/yrby6ktEldwSDonlg1/giphy.gif'
                        ],
                        vendidos: []
        },
        Palafo: {       name:'Palafo',
                        rol: 'Chad',
                        medallas:['b1','b3','b4','b5','b6','b12','b24','b26','b28','b29'],
                        shinys:['machop','spoink','hypno','meowth','hypno','meowth','ponyta','masquerain','gyarados','tangela','drowzee','victreebel','bellossom','jumpluff','beautifly','psyduck','mienfoo'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/barboach.gif'],
                        vendidos: []
        },
        Panchimio: {    name: 'Panchimio',
                        rol: 'MaxiChad',
                        medallas: ['b1','b4','b5','b13','b14','b18','b24','b26','b28','b29','b30'],
                        shinys: ['ninetales','ponyta','golem','vulpix','swellow','bouffalant','chandelure','purrloin','lickilicky','budew','pidgey','pidgeot','tangrowth','growlithe',
                                'jumpluff','solrock','vileplume','slugma','grimer','electrike'],
                        destacados: ['https://img.pokemondb.net/sprites/black-white/anim/shiny/riolu.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/furret.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/simisear.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/iaE6ItdRy56H79jQjg/giphy.gif',
                                'https://media.giphy.com/media/EaNDmWPv4U1x4Jy7tM/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        Pimientadaza: { name:'Pimientadaza',
                        rol: 'Chad',
                        medallas:['b24','b26'],
                        shinys:['seismitoad','haxorus','muk'],
                        destacados:[],
                        vendidos: []
        },
        RagnarokBs: {   name:'RagnarokBs',
                        rol: 'Chad',
                        medallas:['b29'],
                        shinys:['azumarill','accelgor','gyarados','scrafty','politoed','krokorok','pidgey','watchog','chandelure','abra','slowbro','zubat','koffing','mienfoo','vanillite','smeargle','bibarel'],
                        destacados:[],
                        vendidos: []
        },
        RIIW: {         name:'RIIW',
                        rol: 'Chad',
                        medallas:['b9'],
                        shinys:['gengar','graveler','chandelure','mienshao'],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/x9SlMSbBu4sM92smld/giphy.gif']
        },
        ritosenpai: {   name:'ritosenpai',
                        rol: 'MaxiChad',
                        medallas:['b1','b10','b11','b14','b15','b18','b23','b26','b28','b29','b30'],
                        shinys:['slugma','mienfoo','mienfoo','mienfoo','mienfoo','volbeat','shelmet','voltorb','politoed','deino','bellsprout','linoone','weepinbell','drifblim','houndour','zigzagoon','zigzagoon','wynaut',
                                'larvitar','seviper','snorunt','geodude','cubchoo','cubchoo','cubchoo','ponyta','stantler','sableye','golduck','cottonee','sawsbuck','stunky','dratini','wooper','eelektross','jigglypuff',
                                'spinda','zangoose','swadloon','mawile','zubat','kingdra','psyduck','cryogonal','torkoal','poochyena','beartic','vanillish','victreebel','deerling','deerling-autumn','krokorok','weezing',
                                'fearow','fearow','fearow','jumpluff','flygon','shuppet','scraggy','darmanitan','herdier','jynx','pidgey','weepinbell','spearow','chandelure','bronzong','bronzong','lairon','gabite',
                                'surskit'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/nincada.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/swampert.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/jolteon.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/scizor.gif',
                                'https://media.giphy.com/media/dMqaWGfSPgBwKmrZqZ/giphy.gif',
                                'https://media.giphy.com/media/KtpRlWqgvUC1uBAJbI/giphy.gif'
                        ],
                        vendidos: []
        },
        sadending: {    name:'sadending',
                        rol: 'Chad',
                        medallas:['b8','b10'],
                        shinys:['poochyena','poochyena','zigzagoon','bidoof','ponyta','wurmple','magikarp','mienshao'],
                        destacados:['https://media.giphy.com/media/2pKZUMHKeaw2v48YC7/giphy.gif'],
                        vendidos: []
        },
        Seaba: {        name:'Seaba',
                        rol: 'Chad',
                        medallas:['b8','b15','b16','18','b26'],
                        shinys:['gigalith','chandelure','solrock','jynx','crobat','dusknoir','haxorus','hydreigon','gyarados','smeargle','psyduck','gardevoir','liepard','gothitelle','cinccino','jumpluff','masquerain',
                                'accelgor','petilil','wingull'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/bisharp.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWEwM3prdjc2NWdmYTlvYTlidWh0cWViMDNjOG9pNHFicXIxOGx5aSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/5goPOaLsUxMsfDIvTe/giphy.gif'
                        ],
                        vendidos: []
        },
        Sentiel: {      name:'Sentiel',
                        rol: 'MegaChad',
                        medallas:['b24','b26','b29'],
                        shinys:['spearow','golduck','tentacool','vanillish','gyarados','ludicolo','rapidash','conkeldurr','galvantula','mienshao','bellossom','durant','smeargle','sandile','pidgeotto','jumpluff','meowth',
                                'spinda','politoed','vanilluxe','cinccino','lanturn','rhydon','gligar','shelmet','koffing'
                        ],
                        destacados:['https://media.giphy.com/media/9gWStsC8hLjFdmGwIk/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif'
                        ]
        },
        Shroomiish: {   name:'Shroomiish',
                        rol: 'Chad',
                        medallas:['b10','b19','b24'],
                        shinys:['bellsprout','geodude'],
                        destacados:['https://media.giphy.com/media/kI6DHEnVibteJcUDtY/giphy.gif'],
                        vendidos: []
        },
        SniperioYt: {   name:'SniperioYt',
                        rol: 'Chad',
                        medallas:['b10','b18','b26','b29'],
                        shinys:['reuniclus','nidorina','chandelure','smeargle','rapidash','woobat','haxorus','beautifly','muk','fraxure','magikarp','hydreigon','krokorok','swoobat','weezing','psyduck','steelix','amoonguss',
                                'bronzor','banette'
                        ],
                        destacados:['https://media.giphy.com/media/te7Adm14Tbgp65TnjB/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/g6kCi54TtATJcjgnUj/giphy.gif']
        },
        SorlanNorfleet: {name:'SorlanNorfleet',
                        rol: 'Chad',
                        medallas:['b17'],
                        shinys:['mienshao'],
                        destacados:['https://media.giphy.com/media/Y3xTFbUukABDjtMNhp/giphy.gif'],
                        vendidos: []
        },
        Souenx: {       name:'Souenx',
                        rol: 'Lider',
                        medallas:['b1','b4','b5','b8','b10','b12','b15','b16','b19','b24','b26','b29'],
                        shinys:['pidgeot','chandelure','ditto','amoonguss','scolipede','ninetales','crobat','arcanine','rapidash','golem','roserade','slugma','crobat','graveler','rapidash','weezing','tentacruel','ditto'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/octillery.gif',
                                'https://media.giphy.com/media/MtbA3WQ8H564xigCqN/giphy.gif',
                                'https://media.giphy.com/media/BuHDxkzqmEhtCIzaLE/giphy.gif',
                                'https://media.giphy.com/media/hWAgtS6Wjh2OL9d71b/giphy.gif',
                                'https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ3hvODB4ZnAydnRiOWZwMmx0ZHp6MndlZ3F5cWJuZmUyc2psOTd5ZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/yxz6b5ZmjyR3bTEF44/giphy.gif'
                        ],
                        vendidos: []
        },
        spectrerw: {    name:'spectrerw',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['deino','gardevoir','mienfoo','haxorus','magikarp','poochyena','persian','ponyta','woobat','tentacruel','wooper','nidoking','roselia','slowpoke','chandelure'],
                        destacados:[],
                        vendidos: []
        },
        Taiheixd: {     name:'Taiheixd',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['psyduck','ninetales','lilligant','mienfoo','mankey','magikarp'],
                        destacados:[],
                        vendidos: []
        },
        Taqueritobonito: {name:'Taqueritobonito',
                        rol: 'Chad',
                        medallas:['b26'],
                        shinys:['aggron','dusclops','eelektross','golduck','alakazam','weezing','grimer','magcargo','krabby'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/heracross.gif'],
                        vendidos: []
        },
        TheJesucristian: {name:'TheJesucristian',
                        rol: 'Chad',
                        medallas:['b1','b15','b19','b26','b29'],
                        shinys:['golbat','crobat','mienshao','manectric','rapidash','magikarp','gyarados','tentacruel','swoobat','mamoswine','altaria','horsea','slugma','magcargo','duskull','lunatone','raticate','rattata',
                                'ditto','sandshrew','amoonguss','dodrio','mismagius','flygon','murkrow','tyranitar','hydreigon','chandelure','vanilluxe','whimsicott','smeargle','gliscor','spinda','krookodile','haxorus',
                                'golbat','graveler'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/feraligatr.gif',
                                'https://media.giphy.com/media/nUM3Kz42e3MZIkWuiv/giphy.gif'
                        ],
                        vendidos: []
        },
        ToxicPlumber: { name:'ToxicPlumber',
                        rol: 'GigaChad',
                        medallas:['b1','b5','b6','b7','b9','b10','b12','b15','b19','b22','b26','b29','b31'],
                        shinys:['krookodile','raticate','venipede','weezing','nidoqueen','quagsire','altaria','kingdra','pichu','rattata','seaking','machamp','smeargle','gengar','chandelure','pidgey','ferrothorn','aggron',
                                'pelipper','scolipede','swellow','petilil','graveler','whismur','taillow','grimer','alakazam','crobat','marowak','noctowl','beautifly','reuniclus','rapidash','venonat','tentacruel','zubat',
                                'gigalith','vileplume','maractus','manectric','marowak','xatu','gyarados','baltoy','voltorb','lunatone'
                        ],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/combee.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/corphish.gif',
                                'https://img.pokemondb.net/sprites/black-white/anim/shiny/metagross.gif',
                                'https://media.giphy.com/media/9GOx2u2i4ejAC7rF8p/giphy.gif',
                                'https://media.giphy.com/media/0xJcdmbclOlUmG0HGL/giphy.gif',
                                'https://media.giphy.com/media/Xb6XTWhgzk9sa1PPwW/giphy.gif',
                                'https://media.giphy.com/media/ULBhELmX1GMvrg8uoL/giphy.gif',
                                'https://media.giphy.com/media/ezbIutaZL5gHj2yroq/giphy.gif',
                                'https://media.giphy.com/media/qf5boDSdWVT8DaYGDz/giphy.gif'
                        ],
                        vendidos: ['https://media.giphy.com/media/h20dDuV1nQ3syyCMeu/giphy.gif']
        },
        UltimoMorador: {name:'UltimoMorador',
                        rol: 'Chad',
                        medallas:['b15','b26'],
                        shinys:['bellossom','escavalier','litwick','donphan','machamp','graveler','graveler','weezing','dodrio','hariyama','masquerain','igglybuff','snubbull','mantyke','clamperl','marill','boldore','scraggy',
                                'tranquill'
                        ],
                        destacados:[],
                        vendidos: []
        },
        VicReborn: {    name:'VicReborn',
                        rol: 'Chad',
                        medallas:['b24','b30'],
                        shinys:[],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/4usxGoNyYaW4iTubxf/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        wallycba: {     name:'wallycba',
                        rol: 'Chad',
                        medallas:['b10','b19'],
                        shinys:['tentacruel','tentacruel','ponyta','hydreigon','altaria','cottonee','reuniclus','amoonguss','machoke','gurdurr','cubchoo','dodrio','golbat','accelgor'],
                        destacados:[],
                        vendidos: ['https://img.pokemondb.net/sprites/black-white/anim/shiny/zoroark.gif',
                                'https://media.giphy.com/media/QvBYmu8hATjJhgUuCS/giphy.gif',
                                'https://media.giphy.com/media/JzTlsW58P05f8tAUKl/giphy.gif'
                        ]
        },
        xDerxx: {       name:'xDerxx',
                        rol: 'Chad',
                        medallas:['b26'],
                        shinys:['wooper','walrein','graveler','jigglypuff','rapidash','jellicent','cofagrigus'],
                        destacados:[],
                        vendidos: []
        },
        XIPANDAIX: {    name:'XIPANDAIX',
                        rol: 'Chad',
                        medallas:['b15','b26'],
                        shinys:['gigalith','altaria','raticate','politoed','victreebel','accelgor','quagsire','donphan','hydreigon','ludicolo','poliwrath','chandelure','magcargo','haxorus','darmanitan','psyduck','doduo',
                                'gyarados','smeargle','weezing','braviary','jellicent-f','raichu','rapidash'
                        ],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/QAmOMaVAIsfyhe1qi1/giphy.gif']
        },
        xSorC: {        name:'xSorC',
                        rol: 'Chad',
                        medallas:['b0'],
                        shinys:['duosion','bronzor'],
                        destacados:[],
                        vendidos: []
        },
        YuukiTwo: {     name:'YuukiTwo',
                        rol: 'MaxiChad',
                        medallas:['b1','b2','b5','b12','b13','b19','b24','b26'],
                        shinys:['beedrill','sawsbuck','vileplume','nidoking','rhyperior','ninetales'],
                        destacados:['https://img.pokemondb.net/sprites/black-white/anim/shiny/crawdaunt.gif',
                                'https://media.giphy.com/media/X7GjW3K9Sq3BOVQljZ/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/ofHxoizb5ZyN3uvFU6/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/LWm8fjHUKxqb0qyZpD/giphy.gif'
                        ]
        },
        Zergy: {        name:'Zergy',
                        rol: 'Chad',
                        medallas:['b9','b24'],
                        shinys:['gardevoir','haxorus','torkoal','ninetales','flygon'],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/5NXDeILPVEJs8H43qW/giphy.gif',
                                'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjVqdGVsbXlrMjdxMDI4NzhydjdvcHdxYWdlcWVvdnhmcGxxZGFubyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/fKT5lPOrx2PXodB2BD/giphy.gif',
                                'https://media.giphy.com/media/V1D0xcAPuExSsajnWK/giphy.gif',
                                'https://media.giphy.com/media/gSUVBePKqAbJpmfIoA/giphy.gif',
                                'https://media.giphy.com/media/UCSl0CT0X05tKQKvmv/giphy.gif',
                                'https://media.giphy.com/media/iaE6ItdRy56H79jQjg/giphy.gif',
                                'https://media.giphy.com/media/cZI8bvqidD7iphlbdH/giphy.gif',
                                'https://media.giphy.com/media/v7BwuKEmsYbSzTXu2Z/giphy.gif',
                                'https://media.giphy.com/media/QBMPSmPsPc2VXpWte4/giphy.gif',
                                'https://media.giphy.com/media/QBMPSmPsPc2VXpWte4/giphy.gif',
                                'https://media.giphy.com/media/maxPYO7zrPpNCFO0pV/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/I3nMAb29UTofjDsWFg/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/SMttCxbkrQWz8LNsx5/giphy.gif',
                                'https://media.giphy.com/media/olvnpZMLJ9Thfm9Vo7/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/IttNS3VLZryvvxmoL9/giphy.gif'
                        ]
        },
        Zeurir: {       name:'Zeurir',
                        rol: 'Chad',
                        medallas:['b9','b24'],
                        shinys:['ninetales','pelipper','quagsire'],
                        destacados:[],
                        vendidos: ['https://media.giphy.com/media/QbwsfAawOZMWOA9mDd/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/7eBAfbvAahCmhTreRI/giphy.gif',
                                'https://media.giphy.com/media/joRe8SDxlxpAZOQ8VQ/giphy.gif'
                        ]
        },
        zShilphye: {    name:'zShilphye',
                        rol: 'Chad',
                        medallas:['b7','b24'],
                        shinys:['stantler','mamoswine','dodrio','golbat','tentacruel','duskull','ponyta','mienfoo','scrafty','onix','rapidash','durant'],
                        destacados:['https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZXlrMTdnMjdsc3VlZWJ0M3o3amdtajB3ZzFyOTI4cWM0dWh3bXY3cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/vTcPfMe5Iul7kZoYHd/giphy.gif'],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif']
        }
        
    };

function capitalize(str) {
        return str.charAt(0).toUpperCase() + str.slice(1);
}

