const listaMedalla = {
  m_vacio:      {name: 'vacío', info: '...'},
  m_gomed:      {name: '🎮 Go MeD', info:'Tienes 1 año o mas en el team'},
  m_cambio:     {name: '💰 Quédate el cambio', info: 'Has donado 10m o mas al banco del team de una sola vez'},
  m_fundador:   {name: '🧩 Pieza clave', info: 'Formas parte de los miembros fundadores del team'},
  m_lider:      {name: '👑 Dictador', info: 'Has sido líder de MeD'},
  m_guardian:   {name: '💂 Guardián', info: 'Has kickeado a alguien de MeD'},
  m_meditite:   {name: '🧘 Cuerpo y mente', info: 'Has obtenido un shiny Meditite'},
  m_safari:     {name: '🎲 De vida o muerte', info: 'Has capturado un shiny en la Zona Safari'},
  m_swarm:      {name: '🗺️ Tour por el mundo', info: 'Has obtenido un shiny de swarm'},
  m_dead:       {name: '💔 Desafortunado', info: 'Has perdido un shiny durante un encuentro'},
  m_secret:     {name: '🌟 Top secret', info: 'Has obtenido un shiny secret (salvaje)'},
  m_shunter:    {name: '📆 Shunter del mes', info: 'Has obtenido la mayor puntuación de shinys en un mes'},
  m_pescador:   {name: '🎣 Maestro pescador', info: 'Has obtenido un shiny pescando'},
  m_cardumen:   {name: '🐟 Cardumen', info: 'Has obtenido 3 shiny pescando (Sin repetir especies)'},
  m_raceW:      {name: '🥇 Race winner', info: 'Has ganado una shiny race'},
  m_raceL:      {name: '🥈 Fail race', info: 'Has obtenido una fase buscando el shiny de la race'},
  m_suertudo:   {name: '🍀 Suertudo', info: 'Has obtenido 2 o mas shiny en 1 día (24h o menos)'},
  m_racha:      {name: '💫 Enrachado', info: 'Has obtenido un shiny en 3 o mas días seguidos'},
  m_sequia:     {name: '💯 Aferrado', info: 'Has obtenido un shiny después de los 100k de encuentros'},
  m_elegido:    {name: '🛐 El elegido', info: 'Has obtenido un shiny alpha o legendario'},
  m_rare:       {name: '🎩 Hat Trick', info: 'Has obtenido 3 shiny \"rare\"'},
  m_abuelo:     {name: '👴 Paciencia de abuelo', info: 'Has obtenido 3 o mas fases buscando un shiny'},
  m_huevo:      {name: '🥚 Raza perfecta', info: 'Has obtenido un shiny por crianza'},
  m_misterio:   {name: '❔ Misterio resuelto', info: 'Has obtenido un shiny de una Ball Misteriosa'},
  m_fosil:      {name: '🦖 Arqueólogo', info: 'Has obtenido un fósil shiny'},
  m_arbol:      {name: '🌳 Arborista', info: 'Has obtenido un shiny de golpe cabeza/árbol de miel'},
  m_mundo:      {name: '🌎 Trotamundos', info:'Has obtenido un mínimo de 3 shiny de cada región (Sin repetir especies)'},
  m_goldenbox:  {name: '📦 Golden box', info: 'Has obtenido una caja llena (60) de shinys'},
  m_raza:       {name: '🧬 Maestro de raza', info: 'Posees la línea evolutiva completa de un shiny (Solo Pokémon que puedan evolucionar)'},
  m_pecador:    {name: '👿 Pecador', info: 'Has vendido, liberado o regalado un shiny'},
  m_cintas:     {name: '🎀 Shiny completo', info: 'Has obtenido un shiny que posee todas las cintas'},
  m_apostol:    {name: '📝 Apóstol', info: 'Has registrado una nueva especie en la Shiny Dex de MeD'},
  m_pvp:        {name: '🎫 Built different', info: 'Has obtenido un shiny ganando un torneo o evento oficial'},
  m_supremacy1: {name: '🌱 MeD Supremacy 1', info: 'Formaste parte del equipo ganador de la MeD Supremacy 1'},
  m_olimpiadas: {name: '🏆 Winners PokeLympics 2024', info: 'Formaste parte del equipo ganador de las PokeLympics 2024'},
  m_supremacy2: {name: '🅿️ MeD Supremacy 2', info: 'Formaste parte del equipo ganador de la MeD Supremacy 2'},
  m_supremacy3: {name: '🎄 MeD Supremacy 3', info: 'Formaste parte del equipo ganador de la MeD Supremacy 3'},
  m_aniMeD2025: {name: '🎉 AniMeDsario 2', info: 'Formaste parte de los ganadores del evento del AniMeDsario 2025'},
  m_aniMeD2026: {name: '🎉 AniMeDsario 3', info: 'Formaste parte de los ganadores del evento del AniMeDsario 2026'},
  m_shinywar:   {name: '🆖 Shiny War \"OG vs NG\"', info: 'Formaste parte del equipo ganador de la Shiny War \"Old Gen vs New Gen\"'},
  
};

const memberData = {
        aeamanh: {      name:'aeamanh',
                        rol: 'MaxiChad',
                        medallas:['m_secret','m_raceL','m_shunter','m_suertudo','m_sequia','m_mundo','m_rare','m_pecador','m_cardumen','m_apostol','m_olimpiadas','m_supremacy3','m_shinywar'],
                        shinys:['donphan','sandslash','scolipede','raticate','tangrowth','spinda','raticate','mienfoo','frillish-f','smeargle','nidoking','ditto','grimer',
                                'chandelure','leavanny','primeape','ditto','deino','snover','bibarel','quagsire','bellossom','weezing','durant','cryogonal','rapidash','pelipper','altaria',
                                'politoed','duskull','duosion','mightyena','gliscor','gyarados','amoonguss','hippowdon','illumise','loudred','stunfisk','cubchoo','quagsire','cottonee','golett',
                                'zebstrika','horsea','lunatone'
                        ],
                        destacados:[ {name: 'gulpin', type: 'normal'},
                                     {name: 'pansage', type: 'normal'},
                                     {name: 'magneton', type: 'secret'},
                                     {name: 'quilava', type: 'normal'},
                                     {name: 'marshtomp', type: 'normal'},
                                     {name: 'glaceon', type: 'swarm'},
                                     {name: 'barboach', type: 'normal'},
                                     {name: 'wailmer', type: 'normal'},
                                     {name: 'corphish', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/vxRM9XurU5lvpae8Ko/giphy.gif']
        },
        AguitaGooddUwU: {name:'AguitaGooddUwU',
                        rol: 'Chad',
                        medallas:['m_dead','m_pescador','m_pecador','m_shinywar'],
                        shinys:['raticate','ditto','marill','parasect','mienfoo','shuppet','duskull','smeargle','deino','magikarp','frillish-f','chatot','cottonee','cryogonal','swadloon','raticate','meowth','raticate',
                                'lombre','golbat','poliwag','sneasel','golett','slugma','ditto'
                        ],
                        destacados:[{name: 'zorua', type: 'normal'}],
                        perdidos: [{name: 'graveler', type: 'secret'}],
                        vendidos: ['https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif'
                        ]
        },
        Akalii: {    name:'Akalii',
                        rol: 'Chad',
                        medallas:['m_gomed','m_lider','m_guardian','m_secret','m_pescador','m_raceL','m_suertudo','m_huevo','m_mundo','m_raza','m_pecador','m_apostol'],
                        shinys:['tyranitar','horsea','duskull','mienshao','ninetales','poochyena','beedrill','cottonee','slugma','wooper','azumarill','gyarados','shinx','snorunt',
                                'weavile','axew','pachirisu','lanturn','cottonee','torkoal','gible','jumpluff','weezing','bibarel','vulpix','loudred','ralts','cascoon','scraggy','litwick',
                                'xatu'
                        ],
                        destacados:[{name: 'gulpin', type: 'normal'},
                                    {name: 'sharpedo', type: 'normal'},
                                    {name: 'chimchar', type: 'egg'},
                                    {name: 'gligar', type: 'secret'}
                                
                        ],
                        perdidos: [],
                        vendidos: ['https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZW54bXF1OWhocTF3cHMzd3lyMmd2MW5xdTFpNWxucmRkbjlhcjI2ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHBxbzBvM2k5OGFpZXJsMHQ4dzk5NGxteW42NXk3N3IyNjEwaXNnYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ubXLD0w80oZjtsrIUH/giphy.gif',
                                'https://media.giphy.com/media/PMMrLwzj3iqyMtpxQs/giphy.gif',
                                'https://media.giphy.com/media/A2NlfU2OIPj0GAVoJy/giphy.gif',
                                'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXY3dXh2MnNsZHQyYjNzdHE3MmpqMnI5dnoxeDU1cW40cTAyMmc3NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/ptSTYVxdNLH5oH4Siw/giphy.gif'
                        ]
        },
        Alicia: {       name:'Alicia',
                        rol: 'Chad',
                        medallas:['m_gomed','m_lider','m_guardian','m_pescador','m_suertudo','m_rare','m_sequia','m_huevo','m_pecador','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2'],
                        shinys:['parasect','rhydon','camerupt','bronzong','vanilluxe','rattata','girafarig','mareep','spinda','koffing','litwick','horsea','dunsparce','shelmet','fearow'],
                        destacados:[{name: 'corphish', type: 'normal'},
                                    {name: 'eevee', type: 'egg'},
                                    {name: 'typhlosion', type: 'egg'},
                                    {name: 'porygon-z', type: 'egg'}
                        ],
                        perdidos: [{name: 'rotom', type: 'normal'}],
                        vendidos: ['https://media.giphy.com/media/v9IOxgCRm5BbGXEUEG/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/TvZULFmyJBHodh9Py0/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/jz9aaVnHL7w4V8cX9R/giphy.gif',
                                'https://media.giphy.com/media/GewTzo5C9FI68FMJol/giphy.gif',
                                'https://media.giphy.com/media/7B05VelRsf0qfQptsT/giphy.gif'
                        ]
        },
        AnderHacks: {   name:'AnderHacks',
                        rol: 'Chad',
                        medallas:['m_supremacy3'],
                        shinys:['mienshao','camerupt','wooper','psyduck','durant','bibarel','roselia'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        AsuraSkyFlames: {name:'AsuraSkyFlames',
                        rol: 'MegaChad',
                        medallas:['m_pescador','m_huevo','m_pecador'],
                        shinys:['amoonguss','druddigon','beedrill','beedrill','klinklang','crobat','galvantula','grimer','donphan'],
                        destacados:[{name: 'milotic', type: 'normal'},
                                    {name: 'larvesta', type: 'egg'}],
                        perdidos: [],
                        vendidos: []
        },
        Azathotx: {     name:'Azathotx',
                        rol: 'Chad',
                        medallas:['m_gomed','m_swarm','m_shunter','m_raceL','m_rare','m_huevo','m_apostol','m_olimpiadas','m_shinywar'],
                        shinys:['lotad','cacnea','dustox','cinccino','bidoof','mismagius','gastrodon','mienfoo','spinda','venomoth','vanillish','golduck','camerupt','boldore','dugtrio','poochyena',
                                'smeargle','dusclops','weezing','parasect','scolipede','beedrill','eelektrik','piloswine','solrock','zigzagoon','venipede','miltank'],
                        destacados:[{name: 'shroomish', type: 'normal'},
                                    {name: 'kecleon', type: 'normal'},
                                    {name: 'jolteon', type: 'normal'},
                                    {name: 'chansey', type: 'normal'},
                                    {name: 'staryu', type: 'normal'},
                                    {name:'squirtle', type:'egg'},
                                    {name: 'growlithe', type: 'swarm'},
                                    //{name: 'absol', type: ['swarm','multi']},
                                    {name: 'remoraid', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Bwax: {         name:'Bwax',
                        rol: 'Chad',
                        medallas:['m_swarm','m_secret','m_raceL','m_suertudo','m_sequia','m_abuelo','m_raza','m_apostol','m_shinywar'],
                        shinys:['dusclops','gallade','weezing','mienshao','dugtrio','ponyta','chandelure','scrafty','smeargle','spinda','poliwrath','accelgor','mienfoo','yamask','kricketune','cacnea','shellos-east',
                                'shellos-east','vanillish','floatzel','pidgey','linoone','donphan','garchomp','meowth','mienshao'
                        ],
                        destacados:[{name: 'staryu', type: 'normal'},
                                {name: 'porygon-z', type: 'swarm'},
                                {name: 'roselia', type: 'secret'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        CmAshto: {      name:'CmAshto',
                        rol: 'Chad',
                        medallas:['m_dead','m_supremacy3'],
                        shinys:['solrock','gyarados','ditto','poochyena','surskit','ponyta','meowth','pelipper','ludicolo'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Cypher: {       name:'Cypher',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_sequia','m_pecador','m_apostol','m_olimpiadas'],
                        shinys:['spearow','golduck','tentacool','vanillish','gyarados','ludicolo','rapidash','conkeldurr','galvantula','mienshao','bellossom','durant','smeargle','sandile','pidgeotto','jumpluff','meowth',
                                'spinda','politoed','vanilluxe','cinccino','lanturn','rhydon','gligar','shelmet','koffing','litwick','cubchoo','starly','geodude','teddiursa','tranquill','poliwhirl'
                        ],
                        destacados:[{name: 'furret', type: 'normal'}],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif'
                        ]
        },
        DavidCitos: {   name:'DavidCitos',
                        rol: 'Chad',
                        medallas:['m_meditite','m_shunter','m_suertudo','m_racha','m_abuelo','m_mundo','m_goldenbox','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['lopunny','marill','trapinch','roserade','vulpix','hydreigon','magmar','poliwag','swablu','meowth','gyarados','grimer','weezing','weavile','pikachu','psyduck','mareep','miltank',
                                'litwick','duskull','jigglypuff','electabuzz','rapidash','natu','wobbuffet','accelgor','banette','sealeo','vanilluxe','ferroseed','woobat','poliwhirl','parasect','magnezone','hoppip',
                                'mienfoo','rhydon','hariyama','voltorb','gardevoir','smeargle','onix','electrike','magcargo','solrock','poliwhirl','gurdurr','graveler','watchog','mareep','gligar','hypno','cubchoo','swoobat','woobat',
                                'shinx','lanturn','bronzong','stunfisk','dugtrio','palpitoad','donphan','ursaring','snover','tranquill','cofagrigus','basculin','bronzong','horsea','magikarp','krokorok','woobat','axew',
                                'golbat','mankey','girafarig','lunatone','gloom','fearow','gloom','lunatone','spinda','golduck','machoke','lombre','growlithe','kadabra','misdreavus','golbat','floatzel','haunter','lairon','camerupt',
                                'piloswine','zebstrika','snorunt','poliwag','tentacool','slowbro','misdreavus','meditite','drifblim'
                        ],
                        perdidos: [],
                        destacados:[{name: 'treecko', type: 'normal'},
                        ],
                        vendidos: []
        },
        DavinchY: {     name:'DavinchY',
                        rol: 'Chad',
                        medallas:['m_misterio','m_apostol'],
                        shinys:['exploud','gallade','amoonguss','durant','banette','rapidash','ditto','poliwrath','darumaka','haunter','ditto','heatmor','arcanine','poliwrath','beedrill','ralts','raticate','meowth','sawk',
                                'gothitelle','deino','cubchoo','vanilluxe','petilil','diglett','stantler','noctowl','nidorino','venipede','grimer','dratini','mienfoo','larvitar','golbat'],
                        destacados:[{name: 'plusle', type: 'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        DiGoMo: {       name:'DiGoMo',
                        rol: 'MegaChad',
                        medallas:['m_dead','m_pescador','m_suertudo','m_pecador','m_apostol','m_olimpiadas','m_supremacy2','m_supremacy3'],
                        shinys:['muk','cascoon','spearow','pidgeotto','magmortar','pelipper','raticate','ponyta','tynamo','raticate','chandelure','poliwrath','spinda','parasect','smeargle','banette','ponyta','weezing','raticate',
                                'murkrow','joltik','haxorus','vanillish','floatzel','floatzel','gabite','koffing','krabby','golbat','krokorok','cottonee','donphan','gothorita','exploud','vulpix','golbat','murkrow'
                        ],
                        perdidos: [{name: 'dodrio', type: 'normal'}],
                        destacados:[{name: 'breelom', type: 'normal'},
                                    {name: 'snorlax', type: 'normal'}
                        ],
                        vendidos: ['https://media.giphy.com/media/GpMgr8p0p13wASvhVk/giphy.gif',
                                'https://media.giphy.com/media/CNOYDXXMeqrcpEhIE1/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        Distraaa: {     name:'Distraaa',
                        rol: 'Chad',
                        medallas:['m_suertudo','m_shinywar'],
                        shinys:['leavanny','krookodile','weezing','chandelure','smeargle','wigglytuff','tentacruel','zigzagoon'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Doce: {         name:'Doce',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_swarm','m_raceW','m_suertudo','m_huevo','m_pecador','m_apostol','m_supremacy2','m_supremacy3'],
                        shinys:['crobat','litwick','altaria','ditto','raticate','ditto','shuppet','smeargle','duskull','vanillish','spinarak','lombre','golbat','luxio'],
                        destacados:[{name: 'espeon', type: 'egg'},
                                    {name: 'volcarona', type: 'egg'},
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/WF2DTy2zrS7IYBXwtQ/giphy.gif',
                             'https://media.giphy.com/media/nEIv8rJh2tV9rMWaAi/giphy.gif',
                             'https://media.giphy.com/media/UiQHTGjRqobKcFfCqX/giphy.gif',
                             'https://media.giphy.com/media/WBCKmSHx1P3rtJeWFe/giphy.gif'
                        ]
        },
        Dohrito: {      name:'Dohrito',
                        rol: 'Chad',
                        medallas:['m_meditite','m_secret','m_shunter','m_safari','m_raceW','m_raceL','m_rare','m_pescador','m_cardumen','m_mundo','m_goldenbox','m_pecador','m_supremacy2'],
                        shinys:['medicham','beedrill','gliscor','jynx','ninetales','marill','wooper','sealeo','magikarp','rapidash','rapidash','dratini','electrike','stunfisk','druddigon','poliwag','swablu','wingull','pelipper','psyduck',
                                'hypno','amoonguss','dunsparce','cubchoo','beartic','cryogonal','vanillite','vanillish','vanilluxe','crustle','grimer','torkoal','litwick','camerupt','magnezone','mareep','tentacruel','wurmple',
                                'wurmple','weezing','vulpix','accelgor','shuppet','lopunny','teddiursa','quagsire','smeargle','spinarak','slugma','gible','mienfoo','krabby','dodrio','darumaka','walrein','marill'
                        ],
                        destacados:[{name:'pinsir', type:'normal'},
                                {name:'cherubi', type:'normal'},
                                {name:'wailord', type:'normal'},
                                {name:'octillery', type:'normal'},
                                {name:'serperior', type:'secret'},
                                {name:'treecko', type:'secret'},
                                {name:'torchic', type:'egg'},
                                {name:'luvdisc', type:'normal'},
                                {name:'bidoof', type:['secret','safari']},
                                {name:'bayleef', type:'egg'},
                                {name:'mudkip', type:'egg'},
                                {name:'aipom', type:'normal'}

                        ],
                        perdidos: [],
                        vendidos: ['https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc281Y3cxbTRlNGY1YnVwYXFsMzM4Z3FudW1uYWMxZzJrZjcybGt1OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/xbpVD0pTXBBJVkgUKP/giphy.gif']
        },
        Drakulaura: {  name:'Drakulaura',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_guardian','m_shunter','m_safari','m_dead','m_pescador','m_huevo','m_suertudo','m_racha','m_raza','m_mundo','m_apostol','m_shinywar'],
                        shinys:['lanturn','roserade','geodude','golem','donphan','braviary','pelipper','volbeat','sigilyph','minccino','cinccino','trubbish','gyarados','crobat','electrike','drifblim','shellos-east','nosepass',
                                'rhydon','drifloon','mawile','throh','misdreavus'
                        ],
                        destacados:[{name: 'nidoran-f', type: 'safari'},
                                    {name: 'ledyba', type: 'safari'},
                                    {name: 'octillery', type: 'normal'},
                                    {name: 'castform', type: 'egg'},
                                    {name: 'finneon', type: 'normal'}
                        ],
                        perdidos: [{name: 'marill', type: 'safari'},
                                {name: 'houndour', type: 'safari'},
                                {name: 'starly', type: 'safari'}
                        ],
                        vendidos: ['https://media.giphy.com/media/nbxsygYVLvm1Z9IXpu/giphy.gif',
                                'https://media.giphy.com/media/RiSG1piNjO9VPGPjmV/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif'
                        ]
        },
        ElMiga: {       name:'ElMiga',
                        rol: 'MegaChad',
                         medallas:['m_gomed','m_secret','m_raceL','m_pecador','m_apostol','m_supremacy2','m_shinywar'],
                        shinys:['poochyena','staraptor','zigzagoon','larvitar','roserade','raticate','marill','snubbull'],
                        destacados:[{name: 'jolteon', type: 'normal'},
                                    {name: 'poochyena', type: 'secret'}
                        ],
                        perdidos: [{name: 'raticate', type: 'normal'}],
                        vendidos: ['https://media.giphy.com/media/gSUVBePKqAbJpmfIoA/giphy.gif',
                                'https://media.giphy.com/media/cPHoY81t2gnlZ8kqg5/giphy.gif',
                                'https://media.giphy.com/media/xLXn3LWXz0X7vL1Gsd/giphy.gif',
                                'https://media.giphy.com/media/xLXn3LWXz0X7vL1Gsd/giphy.gif'
                        ]
        },
        Elproofe: {     name:'Elproofe',
                        rol: 'GigaChad',
                        medallas:['m_guardian','m_cambio','m_meditite','m_dead','m_pescador','m_suertudo','m_racha','m_sequia','m_mundo','m_goldenbox','m_apostol','m_raza'],
                        shinys:['rapidash','tentacruel','tentacruel','banette','ponyta','ponyta','patrat','venipede','litwick','magikarp','vulpix','axew','ponyta','lombre','stantler','electivire','koffing','gyarados',
                                'meowth','meowth','magikarp','durant','miltank','deino','ditto','lanturn','heatmor','meowth','duskull','smeargle','slugma','horsea','golett','druddigon','kadabra','haunter','pikachu',
                                'larvitar','psyduck','swablu','machoke','bibarel','magmar','throh','timburr','lairon','hariyama','clamperl','sealeo','marill','shellos-east','kakuna','voltorb','lanturn','cryogonal',
                                'pidgeotto','cottonee','trubbish','snorunt','meditite','sableye','murkrow','horsea','gloom','amoonguss','taillow','loudred','wobbuffet','bibarel','sandshrew','stunky','horsea','starly',
                                'wooper','tynamo'
                        ],
                        destacados:[{name:'shellder' ,type:'normal' }],
                        perdidos: [{name: 'koffing', type: 'normal'}],
                        vendidos: [],
        },
        emirfeNoPremium: {name:'emirfeNoPremium',
                        rol: 'Chad',
                        medallas:['m_swarm','m_apostol','m_shinywar'],
                        shinys:['gyarados','lunatone','rattata','gothorita','rhyperior','jigglypuff','litwick','horsea','sewaddle','raticate','mankey','swablu','ditto','sealeo','sneasel','ninetales','graveler','mienfoo'],
                        destacados:[{name: 'squirtle', type:'swarm'},
                                {name: 'furret', type:'normal'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        ErnestoSwampert: {name:'ErnestoSwampert',
                        rol: 'Chad',
                        medallas:['m_safari','m_shunter','m_pescador','m_secret','m_suertudo','m_abuelo','m_raza','m_misterio','m_apostol'],
                        shinys:['nidoking','gyarados','poliwag','weavile','mienshao','weezing','beedrill','marill','jigglypuff','smeargle','banette','parasect','wingull','spinarak','shelmet','persian','graveler','marill','litwick','gliscor',
                                'poliwhirl','poliwhirl','golett','raticate','nidorina','kricketune','vanillish','magikarp','ditto','sableye','slowbro','poochyena','marill','wingull','raticate','ditto','ditto'
                        ],
                        destacados:[{name: 'wailord', type: 'normal'},
                                    {name: 'magikarp' ,type: 'safari'},
                                    {name: 'heracross', type: 'secret'},
                                    {name: 'staryu', type: 'secret'},
                                    {name: 'feebas', type: 'normal'},
                                    {name: 'zigzagoon', type: 'secret'},
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Estorbiito: {   name:'Estorbiito',
                        rol: 'Chad',
                        medallas:['m_suertudo','m_abuelo','m_apostol'],
                        shinys:['smeargle','beedrill','haxorus','poliwrath','weavile','banette','weezing','amoonguss','spinda','ditto','magikarp'],
                        destacados:[{name: 'slaking', type: 'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        Farithi: {      name:'Farithi',
                        rol: 'Chad',
                        medallas:['m_secret','m_supremacy3'],
                        shinys:['leavanny','banette','chandelure','magikarp','vulpix'],
                        destacados:[{name: 'exploud', type: 'secret'}],
                        perdidos: [],
                        vendidos: []
        },
        Felijeicops: {  name:'Felijeicops',
                        rol: 'Chad',
                        medallas:['m_vacio'],
                        shinys:['smeargle','tentacruel','wooper','bellsprout','meowth','magikarp','dodrio','meowth','parasect','meowth','meowth'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Ferbus: {       name:'Ferbus',
                        rol:'Chad',
                        medallas:['m_meditite','m_swarm','m_suertudo','m_racha','m_secret','m_sequia','m_pescador','m_raza','m_goldenbox','m_mundo','m_apostol'],
                        shinys:['tentacruel','gyarados','ponyta','altaria','politoed','ludicolo','donphan','muk','chandelure','camerupt','donphan','aggron','weezing','dusclops','poliwrath','cofagrigus','psyduck','scolipede',
                                'galvantula','ninetales','slowbro','mienshao','azumarill','medicham','bellossom','bibarel','accelgor','stantler','bibarel','crobat','vanilluxe','solrock','jigglypuff','machamp','dodrio','wobbuffet',
                                'shinx','shellos-east','budew','walrein','hydreigon','smeargle','meowth','banette','spinda','gallade','dugtrio','haxorus','conkeldurr','hoppip','wooper','jellicent-f','scrafty','oddish','pelipper','ferroseed',
                                'duosion','magnemite','kricketune','whismur','volbeat','drifblim','purrloin','heatmor','karrablast','hoothoot','zebstrika','machop','machop','grumpig','raticate','parasect','krokorok','sneasel','pikachu','nidorina',
                                'crustle','golbat','golbat','haunter','magikarp','vullaby','horsea','golett','metapod','metapod','fearow','mareep','spearow','nidorino','darumaka','electrike','cacnea','stunky','buneary','trapinch','mantine','hippopotas',
                                'spearrow'
                        ],
                        destacados:[{name: 'salamence', type:'normal'},
                                    {name: 'luvdisc', type:'normal'},
                                    {name: 'farfetchd', type:'normal'},
                                    {name: 'graveler', type:'secret'},
                                    {name: 'corsola', type:'swarm'},
                                    {name: 'remoraid', type:'normal'},
                                    {name: 'unown-g', type:'normal'},
                                    {name: 'raticate', type:'secret'}
                        ],
                        perdidos:[],
                        vendidos:[],

        },
        Guabi: {        name:'Guabi',
                        rol: 'MegaChad',
                        medallas:['m_raceL','m_dead','m_pescador','m_suertudo','m_racha','m_pecador','m_apostol','m_shinywar','m_supremacy3'],
                        shinys:['bibarel','gothita','budew','zigzagoon','heatmor','ditto','seedot','rufflet','golett','frillish','scraggy','mienfoo','ponyta','tauros','gligar','shelmet',
                                'loudred'
                        ],
                        destacados:[{name: 'wailmer', type:'normal'},
                                {name: 'snivy', type:'normal'}
                        ],
                        perdidos: [{name: 'wooper', type: 'safari'}],
                        vendidos: ['https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/0vF7t16ROOFeGekWcF/giphy.gif',
                                'https://media.giphy.com/media/dlxXpY9xfkQ1OuNIux/giphy.gif',
                                'https://media.giphy.com/media/2AcQyIAzpCLU22J9ps/giphy.gif',
                                'https://media.giphy.com/media/R0MfWMPIGXgWZgF5gG/giphy.gif',
                                'https://media.giphy.com/media/JV7Psnvy4K5rl24OMw/giphy.gif',
                                'https://media.giphy.com/media/olvnpZMLJ9Thfm9Vo7/giphy.gif',
                                'https://media.giphy.com/media/PMMrLwzj3iqyMtpxQs/giphy.gif',
                                'https://media.giphy.com/media/3Z43q20eTxPd3flPxV/giphy.gif',
                                'https://media.giphy.com/media/y4R16mDezBPthJ6eHQ/giphy.gif',
                                'https://media.giphy.com/media/sWvXj1UGtwF6qqV5gz/giphy.gif'
                        ]
        },
        Hectoralberto: {name:'Hectoralberto',
                        rol: 'Chad',
                        medallas:['m_raceL','m_apostol','m_olimpiadas','m_supremacy3'],
                        shinys:['quagsire','gyarados','tentacruel','tentacruel','rhyperior','mienfoo','whismur','mightyena','mightyena','grimer','rapidash','rapidash','vanilluxe','ariados','hydreigon',
                                'swablu','rattata'
                        ],
                        destacados:[],
                        vendidos: []
        },
        HoraxPC: {      name:'HoraxPC',
                        rol: 'MegaChad',
                        medallas:['m_swarm','m_huevo','m_pescador','m_suertudo','m_abuelo','m_sequia','m_raza'],
                        shinys:['haxorus','klink','klinklang','chandelure','onix','steelix','galvantula','hydreigon','parasect','smeargle','beautifly','duskull','dustox','gyarados','shelmet'],
                        destacados:[{name: 'drowzee', type: 'swarm'},
                                {name: 'charizard', type: 'egg'},
                                {name: 'rotom', type: 'egg'},
                                {name: 'corphish', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Illumibestii: { name:'Illumibestii',
                        rol: 'Chad',
                        medallas:['m_abuelo'],
                        shinys:['dugtrio','mienshao','reuniclus','hydreigon','swoobat','golett','ninetales','litwick','woobat'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Ingrid: {       name:'Ingrid',
                        rol: 'Chad',
                        medallas:['m_mundo','m_raza','m_pvp','m_shinywar'],
                        shinys:['raticate','pikachu','clefairy','jigglypuff','meowth','arcanine','gengar','onix','kingler','koffing','gyarados','gyarados','crobat','azumarill','politoed','gligar','kingdra','stantler','smeargle',
                                'tyranitar','poochyena','medicham','duskull','luxray','buizel','floatzel','stunky','bronzong','chatot','weavile','tangrowth','mamoswine','cottonee','krookodile','krookodile','maractus','jellicent',
                                'ferroseed','litwick','chandelure','haxorus','beartic','mienfoo','mienshao','mandibuzz','durant','hydreigon','hydreigon','cubchoo','cryogonal','ditto','dodrio','nidoran-f'
                        ],
                        destacados:[{name: 'treecko', type: 'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        IvanMKS: {      name:'IvanMKS',
                        rol: 'Chad',
                        medallas:['m_meditite','m_suertudo','m_pecador'],
                        shinys:['golurk','weezing','gyarados','cryogonal','bouffalant','vanillish','swablu','haxorus','sneasel','cottonee'],
                        destacados:[],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gwavhTbufATct7EFs0/giphy.gif'
                        ]
        },
        IxGab: {        name:'IxGab',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_secret','m_pescador','m_cardumen','m_huevo','m_raceL','m_suertudo','m_apostol','m_supremacy3'],
                        shinys:['kirlia','hydreigon','dragonair','crobat','accelgor','leavanny','weezing','dodrio','poliwag','linoone','vanilluxe','raticate','magikarp','swadloon','starly','golett','darumaka','venipede','petilil','bronzong',
                                'cottonee'
                        ],
                        destacados:[{name: 'corphish', type: 'normal'},
                                {name: 'luvdisc', type: 'normal'},
                                {name: 'breloom', type: 'normal'},
                                {name: 'snivy', type: 'normal'},
                                {name: 'misdreavus', type:'swarm'},
                                {name: 'gulpin', type:'secret'},
                                {name: 'wailmer', type: 'normal'},
                                {name: 'barboach', type: 'normal'},
                                {name: 'oshawott', type: 'egg'},
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Jabubuu: {      name:'Jabubuu',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_safari','m_dead','m_secret','m_shunter','m_suertudo','m_racha','m_sequia','m_abuelo','m_huevo','m_raza','m_pecador','m_apostol','m_shinywar','m_supremacy3'],
                        shinys:['solrock','gastrodon','lopunny','politoed','scolipede','raticate','chandelure','bellossom','ninetales','azurill','lilligant','golem','rattata','vanilluxe','gorebyss','psyduck','wooper',
                                'jumpluff','escavalier','deerling','vileplume','ariados','victreebel','graveler','graveler','sableye','spearow','durant','boldore','sneasel','crustle','slowking','meowth','dewgong','krookodile',
                                'muk','cubchoo','banette','smeargle','wobbuffet','arbok','eelektross','weepinbell','dugtrio','luxray'
                        ],
                        destacados:[{name: 'munna', type: 'secret'},
                                {name: 'eevee', type: 'egg'},
                                {name: 'koffing', type:'safari'},
                                //{name: 'aipom', type: ['secret','swarm','multi']},
                                {name: 'unown-w', type: 'normal'}
                        ],
                        perdidos: [{name: 'hoppip', type: 'normal'}],
                        vendidos: ['https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDFwaGc5MmNwMWgyMmNkdmwyOG9wenoyNGYxanF1b3BreTVsbzg2dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/WwQzqNsYX0l6SgCQZV/giphy.gif']
        },
        JaretZC: {      name:'JaretZC',
                        rol: 'Chad',
                        medallas:['m_shinywar'],
                        shinys:['rhyperior','hydreigon','reuniclus'
                        ],
                        destacados:[{name: 'skarmory', type: 'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        JosiasMccartney: {name:'JosiasMccartney',
                        rol: 'Chad',
                        medallas:['m_raza'],
                        shinys:['fearow','arbok','tentacool','rapidash','gothorita','poliwhirl','woobat','meowth','ponyta','gengar','gyarados','kingdra','smeargle','rhydon','mienshao','chandelure','camerupt','luxio',
                                'swablu','ralts','venipede','venipede','duosion','dodrio','axew'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        JUANKAXGARCIA: {name:'JUANKAXGARCIA',
                        rol: 'Chad',
                        medallas:['m_pescador','m_apostol'],
                        shinys:['vulpix','weezing','horsea','torkoal','gyarados','duosion','heatmor','stantler','bibarel','pelipper','druddigon','krookodile','magnemite','deerling','deino','litwick','mareep','cofagrigus',
                                'frillish','cacnea','lilligant','aron','joltik','ferrothorn','smeargle','jynx','accelgor','mienshao','slowbro','boldore','sneasel','altaria','gliscor','kadabra','zebstrika'
                        ],
                        destacados:[{name: 'carvanha', type: 'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        KamiBone: {      name:'KamiBone',
                        rol: 'MegaChad',
                        medallas:['m_apostol'],
                        shinys:['fearow','pikachu','vanilluxe','chandelure','magnezone','gengar','magikarp','tangrowth','weezing','golem','hydreigon','dragonite','bellsprout'],
                        destacados:[{name: 'exeggcute', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        KilluaZoldyck: {name:'KilluaZoldyck',
                        rol: 'Chad',
                        medallas:['m_gomed','m_misterio','m_apostol'],
                        shinys:['dratini','smeargle','duskull','koffing','gyarados','donphan','rapidash','ponyta','vulpix','woobat','darumaka','elekid'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Krampus: {      name:'Krampus',
                        rol: 'MegaChad',
                        medallas:['m_meditite','m_pescador','m_suertudo','m_raceL','m_sequia','m_secret','m_pecador','m_apostol'],
                        shinys:['gigalith','altaria','raticate','politoed','victreebel','accelgor','quagsire','donphan','hydreigon','ludicolo','poliwrath','chandelure','magcargo','haxorus','darmanitan','psyduck','doduo',
                                'gyarados','smeargle','weezing','braviary','jellicent-f','raichu','rapidash','gurdurr','grimer','bellsprout','metapod','scraggy','cubchoo','piloswine','krokorok','duskull','duosion', 'lanturn',
                                'marill','petilil','meditite','graveler','poliwhirl','luxio','shuppet','torkoal','haunter','marill','donphan','floatzel','floatzel','dugtrio'
                        ],
                        destacados:[{name: 'luvdisc', type: 'normal'},
                                    {name: 'farfetchd', type: 'secret'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/QAmOMaVAIsfyhe1qi1/giphy.gif']
        },
        KnowJiYong: {   name:'KnowJiYong',
                        rol: 'MaxiChad',
                        medallas:['m_gomed','m_guardian','m_secret','m_shunter','m_pescador','m_raceL','m_suertudo','m_huevo','m_mundo','m_raza','m_pecador','m_apostol','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['kakuna','tentacruel','tentacruel','tentacruel','tentacruel','slugma','banette','chandelure','camerupt','torkoal','claydol','smeargle','lanturn','gloom','bellossom','pikachu','minccino',
                                'sandshrew','psyduck','surskit','dewgong','beedrill','weezing','pelipper','krokorok','rapidash','durant','deino','glalie','abomasnow','accelgor','duskull','ditto','donphan','floatzel',
                                'zebstrika','magnemite','wingull','electabuzz','vulpix','haunter','luxio','psyduck','bronzong','slowbro','metapod','mankey','rhydon','sneasel'
                        ],
                        destacados:[{name: 'staryu', type: 'normal'},
                                {name: 'lumineon', type: 'normal'},
                                {name: 'breloom', type: 'normal'},
                                {name: 'sharpedo', type: 'normal'},
                                {name: 'mothim', type: 'egg'},
                                {name: 'tauros', type: 'secret'},
                                {name: 'pidgey', type: 'secret'},
                                {name: 'seedot', type: 'secret'},
                                {name:'squirtle', type:'egg'},
                                {name:'persian', type:'secret'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/WnUoZLB0Sa1LV9rel3/giphy.gif']
        },
        Maicol: {     name:'Maicol',
                        rol: 'Chad',
                        medallas:['m_pescador','m_dead','m_huevo','m_apostol','m_supremacy2'],
                        shinys:['chandelure','steelix','gyarados','tyranitar','scolipede','cubchoo','cacnea','ludicolo','alakazam','smeargle','parasect','dusclops','spinda','woobat'],
                        destacados:[{name: 'breloom', type: 'normal'},
                                {name: 'crawdaunt', type: 'normal'},
                                {name: 'venusaur', type: 'egg'},
                                 {name: 'feebas', type: 'normal'}
                                ],
                        perdidos: [{name: 'persian', type: 'normal'}],
                        vendidos: ['https://media.giphy.com/media/7uxLPTrZZAl2HjGG9y/giphy.gif',
                                'https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/bsxtXWvus1jvqHDZA7/giphy.gif'
                        ]
        },
        MarkosW: {      name:'MarkosW',
                        rol: 'Chad',
                        medallas:['m_dead','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['sunflora','litwick','cryogonal','beedrill','ponyta','smeargle','koffing','tentacruel','psyduck','golett','clefable','vanilluxe','woobat','woobat','axew','hoppip','gligar','floatzel','floatzel'],
                        destacados:[{name: 'togekiss', type: 'normal'}],
                        perdidos: [{name: 'ledyba', type: 'normal'}],
                        vendidos: []
        },
        MasterFox: {    name:'MasterFox',
                        rol: 'Chad',
                        medallas:['m_gomed','m_dead','m_secret','m_pescador','m_suertudo','m_huevo','m_pecador','m_apostol','m_supremacy2'],
                        shinys:['butterfree','raticate','parasect','venomoth','golem','rapidash','kingler','ditto','dunsparce','kingdra','exploud','altaria','lunatone','huntail','gigalith','leavanny','lilligant',
                                'crustle','cinccino','gothitelle','vanilluxe','sawsbuck','galvantula','haxorus','accelgor','golurk','bouffalant','durant','chandelure','tyranitar','sandslash','slowbro','sawsbuck-winter',
                                'ditto','escavalier','persian','marill'

                        ],
                        destacados:[{name: 'corsola', type: 'normal'},
                                {name: 'volcarona', type: 'egg'},
                                {name: 'raichu', type: 'secret'},
                                {name: 'beedrill', type: 'secret'}
                        ],
                        perdidos: [{name: 'karrablast', type: 'normal'}],
                        vendidos: []
        
        },
        Maxii: {        name:'Maxii',
                        rol: 'Chad',
                        medallas:['m_meditite','m_apostol','m_supremacy2'],
                        shinys:['aggron','eelektross','golduck','alakazam','weezing','grimer','magcargo','krabby','loudred','pidgey','parasect','larvitar','floatzel','lombre','stantler',
                                'nidorina','sandslash','rhyperior','petilil','joltik','meditite','machoke','psyduck','magnemite','roselia'
                        ],
                        destacados:[{name: 'heracross', type: 'normal'},
                                {name: 'exeggutor', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        MaxVerstappen: {name:'MaxVerstappen',
                        rol: 'Chad',
                        medallas:['m_elegido','m_huevo','m_raza','m_apostol'],
                        shinys:['zigzagoon','linoone','linoone','drifblim','deino','koffing','cryogonal','meowth','medicham','mienfoo','cubchoo','beartic','magnezone','accelgor','psyduck','galvantula','steelix','camerupt',
                                'poliwhirl','poliwhirl','poliwrath','politoed','bronzor','volbeat'
                        ],
                        destacados:[{name: 'milotic', type: 'normal'},
                                {name: 'chansey', type: ['alpha','egg']}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Mittoh: {       name:'Mittoh',
                        rol: 'GigaChad',
                        medallas:['m_gomed','m_pescador','m_racha','m_huevo','m_arbol','m_pecador','m_cardumen','m_apostol','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['litwick','meowth','deino','purugly','duosion','ninetales','bibarel','bibarel','petilil','donphan','golett','murkrow','ralts','wooper','poliwag',
                                'koffing','krabby','swadloon','tentacruel','amoonguss','machop','cubone'
                        ],
                        destacados:[{name: 'eevee', type: 'egg'},
                                    {name: 'combee', type: 'normal'},
                                    {name: 'corsola', type: 'normal'},
                                    {name: 'shellder', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/tFwiptIH8CEuYpg3UQ/giphy.gif',
                                'https://media.giphy.com/media/WBCKmSHx1P3rtJeWFe/giphy.gif',
                                'https://media.giphy.com/media/WBCKmSHx1P3rtJeWFe/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        MonkeyCake: {   name:'MonkeyCake',
                        rol: 'Chad',
                        medallas:['m_gomed','m_swarm','m_dead','m_abuelo','m_raceL','m_suertudo','m_huevo','m_shunter','m_pecador','m_apostol'],
                        shinys:['bibarel','bronzong','bronzong','bronzong','bronzong','chingling'],
                        destacados:[{name: 'arbok', type: 'swarm'},
                                {name: 'excadrill', type: 'egg'}
                        ],
                        perdidos: [{name: 'fearow', type: 'normal'}],
                        vendidos: ['https://media.giphy.com/media/gwavhTbufATct7EFs0/giphy.gif',
                                'https://media.giphy.com/media/v7BwuKEmsYbSzTXu2Z/giphy.gif',
                                'https://media.giphy.com/media/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media.giphy.com/media/D0VlsgLGW6enaA5m7m/giphy.gif',
                                'https://media.giphy.com/media/ABbHis5AHV4KFY18so/giphy.gif'
                        ]
        },
        Monozee: {      name:'Monozee',
                        rol: 'Chad',
                        medallas:['m_dead','m_suertudo','m_pecador'],
                        shinys:['watchog','dodrio','dodrio','donphan','donphan','horsea','purrloin','koffing','litwick','sneasel','smeargle','magikarp','duskull','vulpix','axew','banette','krokorok','misdreavus','poliwag',
                                'mienfoo','darumaka','wooper','electrike','slowbro','donphan'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        MUDKIIP: {      name:'MUDKIIP',
                        rol: 'Chad',
                        medallas:['m_pescador','m_goldenbox','m_raza'],
                        shinys:['marowak','magnezone','hydreigon','psyduck','camerupt','wooper','druddigon','rapidash','ninetales','arcanine','darmanitan','diglett','tentacool','slowbro',
                                'tangrowth','poliwag','poliwhirl','poliwrath','politoed','raticate','girafarig','hypno','machamp','goldeen','stantler','gyarados','magikarp','spinda','azumarill',
                                'manectric','tentacruel','linoone','exploud','pelipper','wingull','steelix','rhyperior','altaria','chatot','gastrodon','pachirisu','floatzel','weezing','accelgor',
                                'durant','chandelure','heatmor','zebstrika','mienshao','smeargle','quagsire','wobbuffet','nidoqueen','nidoking','gengar','crobat','hariyama','slowbro','walrein',
                                'vileplume','cacturne','liepard','muk','geodude','vanillish','dunsparce','budew','piloswine','voltorb','seel','arbok','shinx','klink'
                        ],
                        destacados:[{name: 'remoraid', type: 'normal'},
                                {name: 'carvanha', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Murkrow: {      name:'Murkrow', /* Restri */
                        rol: 'MegaChad',
                        medallas:['m_abuelo','m_pescador','m_suertudo','m_pecador','m_apostol','m_supremacy3'],
                        shinys:['litwick','koffing','golbat','misdreavus','murkrow','mienshao','whimsicott','banette','duskull','seedot','sneasel','zangoose','golett','murkrow',
                                'surskit','numel'
                        ],
                        destacados:[{name: 'relicanth', type: 'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        Mustam: {       name:'Mustam',
                        rol: 'MegaChad',
                        medallas:['m_safari','m_dead','m_secret','m_pescador','m_abuelo','m_huevo','m_raza','m_pecador'],
                        shinys:['pidgeot','persian','ludicolo','mantine','altaria','smeargle','hoothoot','poochyena','meowth','beautifly','wingull','jumpluff','poliwag','torkoal','dewgong','mareep','meowth'
                                ,'gligar','lanturn','pikachu','drowzee','rattata','raticate','parasect','phanpy','petilil','wingull','meowth','pidgey'
                        ],
                        destacados:[{name: 'furret', type: 'normal'},
                                {name: 'sceptile', type: 'normal'},
                                {name: 'kangaskhan', type: 'egg'},
                                {name: 'lapras', type: 'safari'},
                                {name: 'milotic', type: 'safari'},
                                {name: 'rattata', type: 'secret'}
                        ],
                        perdidos: [{name: 'abra', type: 'normal'},
                                {name: 'sunkern', type: 'safari'}
                        ],
                        vendidos: ['https://media.giphy.com/media/lAcpPVwrBgQfMfBHlD/giphy.gif',
                                'https://media.giphy.com/media/T2bUB6ZHTIO3fxlH11/giphy.gif',
                                'https://media.giphy.com/media/FF9MGEFeqTS4Mn2vAJ/giphy.gif',
                                'https://media.giphy.com/media/13ZtgbQM9NwuIjtoyN/giphy.gif',
                                'https://media.giphy.com/media/rAa3yXQEgFsN72fvoY/giphy.gif',
                                'https://media.giphy.com/media/rAa3yXQEgFsN72fvoY/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/EQIOBvPaS0RoyW6P2J/giphy.gif',
                                'https://media.giphy.com/media/vgltunPjQb3mMh3pYq/giphy.gif'
                        ]
        },
        Mxxarc: {       name:'Mxxarc',
                        rol: 'Chad',
                        medallas:['m_gomed','m_huevo','m_apostol','m_supremacy1','m_olimpiadas'],
                        shinys:['mienshao','flygon','nidoran-f','chandelure','ninetales','muk','lanturn','altaria','seismitoad','smeargle','druddigon','kingdra','gyarados','joltik','donphan'],
                        destacados:[{name: 'typhlosion', type: 'egg'}],
                        perdidos: [],
                        vendidos: []
        },
        nyumichaelis: {name:'nyumichaelis',
                        rol: 'Chad',
                        medallas:['m_gomed','m_pescador','m_secret','m_suertudo','m_abuelo','m_raza','m_pecador','m_apostol','m_olimpiadas','m_shinywar'],
                        shinys:['tentacruel','bouffalant','rapidash','ponyta','scolipede','slugma','lopunny','poochyena','weedle','steelix','cottonee','bibarel','silcoon','dustox','beautifly','graveler','golem'],
                        destacados:[{name: 'zorua', type: 'normal'},
                                {name: 'shroomish', type: 'normal'},
                                {name: 'carvanha', type: 'normal'},
                                {name: 'phanpy', type: 'secret'},
                                {name: 'fearow', type: 'secret'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif',
                                'https://media.giphy.com/media/Xp5TIjgmifuCgKtk8D/giphy.gif'
                        ]
        },
        OniED: {        name:'OniED',
                        rol: 'GigaChad',
                        medallas:['m_guardian','m_dead','m_secret','m_pescador','m_shunter','m_suertudo','m_racha','m_rare','m_abuelo','m_huevo','m_fosil','m_arbol','m_raza','m_pecador','m_apostol','m_shinywar','m_supremacy3'],
                        shinys:['weavile','tentacruel','amoonguss','sandslash','gligar','grimer','koffing','meowth','poochyena','zigzagoon','pelipper','wingull','mienshao','ditto','accelgor','ledyba','hoothoot',
                                'bellsprout','scolipede','sewaddle','lotad','golett','slugma','claydol','cryogonal','venipede','growlithe','growlithe','nidoran-f','pidgey','ninetales','vulpix','horsea','dustox','pidgey','smeargle'
                        ],
                        destacados:[{name: 'pansage', type: 'normal'},
                                {name: 'remoraid', type: 'normal'},
                                {name: 'slakoth', type: 'normal'},
                                {name: 'shroomish', type: 'normal'},
                                {name: 'pawniard', type: 'normal'},
                                {name: 'lileep', type: 'egg'},
                                {name: 'cranidos', type: 'egg'},
                                {name: 'volcarona', type: 'egg'},
                                {name: 'pelipper', type: 'secret'},
                                {name: 'zigzagoon', type: 'secret'},
                                {name: 'growlithe', type: 'secret'}
                        ],
                        perdidos: [{name: 'riolu', type: 'safari'},
                                {name: 'wooper', type: 'safari'}
                        ],
                        vendidos: ['https://media.giphy.com/media/3XWhYuF1IEcTsDBJXD/giphy.gif',
                                'https://media.giphy.com/media/tILTB4DTScZ7Sd5PIP/giphy.gif',
                                'https://media.giphy.com/media/7B05VelRsf0qfQptsT/giphy.gif',
                                'https://media.giphy.com/media/D3Lvv8nOqyVEkRFrWZ/giphy.gif',
                                'https://media.giphy.com/media/ofHxoizb5ZyN3uvFU6/giphy.gif',
                                'https://media.giphy.com/media/Lk4bupthAXzZiYNLPx/giphy.gif',
                                'https://media.giphy.com/media/juwTFb2dmySsKb2N3b/giphy.gif',
                                'https://media.giphy.com/media/juwTFb2dmySsKb2N3b/giphy.gif',
                                'https://media.giphy.com/media/25US6QyxVKt91tanHm/giphy.gif',
                                'https://media.giphy.com/media/25US6QyxVKt91tanHm/giphy.gif',
                                'https://media.giphy.com/media/DTGNzyLWgweQqRRGJ4/giphy.gif',
                                'https://media.giphy.com/media/DTGNzyLWgweQqRRGJ4/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3BlaHRvZm5ubGg1NWp5Y2VsMnNmZ2M0NXp6cHkwM29vYXVhdXQ4MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/oBe1LREMjvljQGVAgl/giphy.gif',
                                'https://media.giphy.com/media/jUZ6vbouEmCb3ZEKlA/giphy.gif',
                                'https://media.giphy.com/media/jLFYwkOfbOK6EYuImb/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif'
                        ]
        },
        Palafo: {       name:'Palafo',
                        rol: 'Chad',
                        medallas:['m_gomed','m_fundador','m_lider','m_guardian','m_meditite','m_pescador','m_raza','m_pecador','m_apostol','m_supremacy1','m_olimpiadas'],
                        shinys:['machop','spoink','hypno','meowth','hypno','meowth','ponyta','masquerain','gyarados','tangela','drowzee','victreebel','bellossom','jumpluff','beautifly','psyduck','mienfoo'],
                        destacados:[{name: 'whiscash', type: 'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        Pancho: {       name: 'Pancho',
                        rol: 'MaxiChad',
                        medallas: ['m_gomed','m_lider','m_guardian','m_raceW','m_abuelo','m_mundo','m_rare','m_raza','m_pecador','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys: ['nidoking','ninetales','ponyta','golem','vulpix','swellow','bouffalant','chandelure','purrloin','lickilicky','budew','pidgey','pidgeot','tangrowth','growlithe',
                                'jumpluff','solrock','vileplume','slugma','grimer','electrike','mandibuzz','whirlipede'],
                        destacados: [{name: 'riolu', type: 'normal'},
                                {name: 'furret', type: 'normal'},
                                {name: 'simisear', type: 'normal'},
                                {name: 'swampert', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/EaNDmWPv4U1x4Jy7tM/giphy.gif',
                                'https://media.giphy.com/media/ptSTYVxdNLH5oH4Siw/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        PierciLmL: {    name:'PierciLmL',
                        rol: 'Chad',
                        medallas:['m_apostol','m_olimpiadas','m_supremacy2'],
                        shinys:['tentacruel','gliscor','linoone','wooper','rattata','chandelure','lanturn','smeargle','poliwrath'],
                        destacados:[{name:'metagross', type:'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        pimientadaza: { name:'pimientadaza',
                        rol: 'Chad',
                        medallas:['m_pescador','m_pecador','m_apostol'],
                        shinys:['haxorus','muk','fearow'],
                        destacados:[{name: 'wailord', type: 'normal'}],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/AB2zHXNURMrFmsWTee/giphy.gif']
        },
        RagnarokBs: {   name:'RagnarokBs',
                        rol: 'Chad',
                        medallas:['m_gomed','m_olimpiadas'],
                        shinys:['azumarill','accelgor','gyarados','scrafty','politoed','krokorok','pidgey','watchog','chandelure','abra','slowbro','zubat','koffing','mienfoo','vanillite','smeargle','bibarel',
                                'durant','gurdurr','durant'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        rebukittheveil: {name:'rebukittheveil',
                        rol: 'Chad',
                        medallas:['m_pescador','m_suertudo','m_huevo','m_pecador','m_cardumen','m_olimpiadas','m_supremacy2','m_supremacy3'],
                        shinys:['haxorus','manectric','camerupt','nidoqueen','lickitung','lanturn','luxio','vulpix','horsea','dragonair','krokorok','mienfoo','lilligant','golbat','seadra','krabby','poliwhirl','gyarados',
                                'butterfree','duskull','arbok','jigglypuff','gyarados','gyarados'
                        ],
                        destacados:[{name:'barboach', type:'normal'},
                                    {name: 'charizard', type: 'egg'},
                                    {name:'sudowoodo', type:'normal'}                                    
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/0vF7t16ROOFeGekWcF/giphy.gif',
                                'https://media.giphy.com/media/0vF7t16ROOFeGekWcF/giphy.gif',
                                'https://media.giphy.com/media/qI0CeWonaxP7k6Y4Lx/giphy.gif'
                        ]
        },
        Reimy: {        name:'Reimy',
                        rol: 'Chad',
                        medallas:['m_dead','m_secret','m_pescador','m_suertudo','m_racha','m_pecador','m_apostol','m_shinywar'],
                        shinys:['gardevoir','haxorus','ninetales','torkoal','flygon','elgyem','clamperl','snorunt','dratini','glameow','lunatone','larvitar','ditto','jigglypuff'],
                        destacados:[{name:'luvdisc', type:'normal'},
                                {name:'octillery', type:'secret'},      
                        ],
                        perdidos: [{name: 'purugly', type: 'normal'},
                                {name: 'nidoran-f', type: 'safari'}
                                ],
                        vendidos: ['https://media.giphy.com/media/gSUVBePKqAbJpmfIoA/giphy.gif',
                                'https://media.giphy.com/media/UCSl0CT0X05tKQKvmv/giphy.gif',
                                'https://media.giphy.com/media/iaE6ItdRy56H79jQjg/giphy.gif',
                                'https://media.giphy.com/media/cZI8bvqidD7iphlbdH/giphy.gif',
                                'https://media.giphy.com/media/v7BwuKEmsYbSzTXu2Z/giphy.gif',
                                'https://media.giphy.com/media/QBMPSmPsPc2VXpWte4/giphy.gif',
                                'https://media.giphy.com/media/QBMPSmPsPc2VXpWte4/giphy.gif',
                                'https://media.giphy.com/media/maxPYO7zrPpNCFO0pV/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/lYWCqTbScj7X18ZGvJ/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/vq0NbSfgNAzU9n9HZN/giphy.gif',
                                'https://media.giphy.com/media/I3nMAb29UTofjDsWFg/giphy.gif',
                                'https://media.giphy.com/media/dIX281x6Etp6ekX4n7/giphy.gif',
                                'https://media.giphy.com/media/SMttCxbkrQWz8LNsx5/giphy.gif',
                                'https://media.giphy.com/media/olvnpZMLJ9Thfm9Vo7/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/IttNS3VLZryvvxmoL9/giphy.gif',
                                'https://media.giphy.com/media/822MTo2BKJqejpx8is/giphy.gif',
                                'https://media.giphy.com/media/822MTo2BKJqejpx8is/giphy.gif'
                        ]
        },
        Renz: {         name:'Renz',
                        rol: 'Chad',
                        medallas:['m_gomed','m_guardian','m_meditite','m_secret','m_raceW','m_pecador','m_apostol'],
                        shinys:['chandelure','camerupt','meowth','sneasel','seel','deino'],
                        destacados:[{name: 'whismur', type:'secret'}],
                        perdidos: [],
                        vendidos: []
        },
        reylegendarioK: {name:'reylegendarioK',
                        rol: 'Chad',
                        medallas:['m_shinywar'],
                        shinys:['scolipede','smeargle','mismagius','hydreigon','krokorok','rapidash','raticate','raticate','sawk','cryogonal'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        RIIW: {         name:'RIIW',
                        rol: 'Chad',
                        medallas:['m_dead'],
                        shinys:['gengar','graveler','chandelure','mienshao','mienfoo'],
                        destacados:[],
                        perdidos: [{name: 'hoothoot', type: 'safari'}],
                        vendidos: []
        },
        ritosenpai: {   name:'ritosenpai',
                        rol: 'MaxiChad',
                        medallas:['m_gomed','m_secret','m_shunter','m_raceL','m_suertudo','m_sequia','m_abuelo','m_mundo','m_goldenbox','m_raza','m_apostol','m_supremacy1','m_olimpiadas','m_supremacy2','m_shinywar'],
                        shinys:['slugma','mienfoo','mienfoo','mienfoo','mienfoo','volbeat','shelmet','voltorb','politoed','deino','bellsprout','linoone','weepinbell','drifblim','houndour','zigzagoon','zigzagoon','wynaut',
                                'larvitar','seviper','snorunt','geodude','cubchoo','cubchoo','cubchoo','ponyta','stantler','sableye','golduck','cottonee','sawsbuck','stunky','dratini','wooper','eelektross','jigglypuff',
                                'spinda','zangoose','swadloon','mawile','zubat','kingdra','psyduck','cryogonal','torkoal','poochyena','beartic','vanillish','victreebel','deerling','deerling-autumn','krokorok','weezing',
                                'fearow','fearow','fearow','jumpluff','flygon','shuppet','scraggy','darmanitan','herdier','jynx','pidgey','weepinbell','spearow','chandelure','bronzong','bronzong','lairon','gabite',
                                'surskit','pidove','clamperl','mightyena','golbat','lunatone','lunatone','ralts','zebstrika','quagsire'
                        ],
                        destacados:[{name: 'ninjask', type: 'normal'},
                                {name: 'swampert', type: 'normal'},
                                {name: 'jolteon', type: 'normal'},
                                {name: 'scizor', type: 'normal'},
                                {name: 'gulpin', type: 'secret'},
                                {name: 'zigzagoon', type: 'secret'},
                                {name: 'kecleon', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        sadending: {    name:'sadending',
                        rol: 'Chad',
                        medallas:['m_swarm','m_secret','m_shunter','m_raceW','m_abuelo','m_apostol'],
                        shinys:['poochyena','poochyena','zigzagoon','bidoof','ponyta','wurmple','magikarp','mienshao','onix','onix','gligar','graveler'],
                        destacados:[{name: 'shroomish', type: 'normal'},
                                {name: 'skarmory', type: 'normal'},
                                {name: 'gliscor', type: ['secret','swarm']},
                                {name: 'buneary', type: 'secret'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Scashh: {       name:'Scashh',
                        rol: 'Chad',
                        medallas:['m_huevo','m_apostol','m_pvp'],
                        shinys:['meowth','mightyena','poochyena','marill','banette','golurk','poliwrath','zigzagoon','nidoking','dusknoir','alakazam','smeargle'],
                        destacados:[{name: 'tropius', type: 'normal'},
                                    {name: 'sceptile', type: 'normal'},
                                    {name: 'swampert', type: 'egg'},
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Seaba: {        name:'Seaba',
                        rol: 'MegaChad',
                        medallas:['m_safari','m_swarm','m_raceL','m_suertudo','m_racha','m_sequia','m_abuelo','m_huevo','m_apostol','m_supremacy3'],
                        shinys:['gigalith','chandelure','solrock','jynx','crobat','dusknoir','haxorus','hydreigon','gyarados','smeargle','psyduck','gardevoir','liepard','gothitelle','cinccino','jumpluff','masquerain',
                                'accelgor','petilil','wingull','cacnea','darumaka','electrike','cubchoo','nidoran-m','shellos-east','shellos-east','quagsire','shellos-east','mienfoo','wooper','kricketune',
                                'pidove','karrablast','mienfoo','mienfoo','sawsbuck-spring'
                        ],
                        destacados:[{name: 'bisharp', type: 'normal'},
                                {name:'oshawott', type:'egg'},
                                {name: 'mime-jr', type: 'swarm'},
                                {name: 'porygon', type: 'swarm'},
                                {name: 'marill', type: 'safari'},
                                {name:'piplup', type:'egg'},
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Silvaryl: {     name:'Silvaryl',
                        rol: 'Chad',
                        medallas:['m_gomed','m_raceL','m_pecador','m_apostol','m_olimpiadas'],
                        shinys:['vanilluxe','haxorus','ledian','tyranitar'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        Snip: {         name:'Snip',
                        rol: 'Chad',
                        medallas:['m_secret','m_suertudo','m_abuelo','m_raza','m_apostol','m_olimpiadas'],
                        shinys:['reuniclus','nidorina','chandelure','smeargle','rapidash','woobat','haxorus','beautifly','muk','fraxure','magikarp','hydreigon','krokorok','swoobat','weezing','psyduck','steelix','amoonguss',
                                'bronzor','banette','onix','onix','timburr','tympole','tympole','timburr','seismitoad','pidove','miltank'
                        ],
                        destacados:[{name: 'woobat', type: 'secret'},
                                {name: 'rotom', type: 'egg'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/g6kCi54TtATJcjgnUj/giphy.gif']
        },
        SorlanNorfleet: {name:'SorlanNorfleet',
                        rol: 'Chad',
                        medallas:['m_elegido'],
                        shinys:['mienshao','liepard'],
                        destacados:[{name: 'gyarados', type: 'alpha'}],
                        perdidos: [],
                        vendidos: []
        },
        Souen: {        name:'Souen',
                        rol: 'Lider',
                        medallas:['m_gomed','m_lider','m_guardian','m_meditite','m_shunter','m_mundo','m_raceW','m_swarm','m_fosil','m_secret','m_pescador','m_cardumen','m_raceL','m_suertudo','m_racha','m_sequia','m_abuelo','m_huevo','m_raza','m_pecador','m_apostol','m_goldenbox','m_olimpiadas'],
                        shinys:['pidgeot','chandelure','ditto','amoonguss','scolipede','ninetales','crobat','arcanine','rapidash','golem','roserade','slugma','crobat','graveler','rapidash','weezing','tentacruel','ditto',
                                'shellos-east','bibarel','kricketune','oddish','bibarel','misdreavus','smeargle','woobat','mienshao','jellicent-f','nidoking','luxray','medicham','cubchoo','cryogonal','petilil','rapidash','starly',
                                'zubat','bibarel','starly','starly','zubat','bibarel','staraptor','bibarel','gallade','mankey','girafarig','primeape','misdreavus','ampharos','lopunny','camerupt','misdreavus','manectric','magnezone','misdreavus',
                                'golbat','honchkrow','krabby','arbok'
                        ],
                        destacados:[{name: 'toxicroak', type: 'egg'},
                                {name: 'octillery', type: 'normal'},
                                {name: 'dragonite', type: 'swarm'},
                                {name: 'breloom', type: 'egg'},
                                {name: 'gastrodon', type: 'secret'},
                                {name: 'graveler', type: 'secret'},
                                {name: 'yanmega', type: 'normal'},
                                {name: 'luvdisc', type: 'normal'},
                                {name: 'luvdisc', type: 'normal'},
                                {name: 'archen', type: 'egg'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        Suzuya:         {name:'Suzuya',
                        rol: 'Chad',
                        medallas:['m_suertudo','m_mundo','m_pecador'],
                        shinys:['cubchoo','alakazam','rhyhorn','torkoal','pikachu','stunky','lunatone','tyranitar','garchomp','phanpy','hoppip','krookodile','hydreigon','magmortar','koffing','honchkrow','nidoran-f','mawile',
                                'drifblim','fearow'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/TWlNAIDfpw23BhIogu/giphy.gif']
        },
        TheJesucristian: {name:'TheJesucristian',
                        rol: 'MegaChad',
                        medallas:['m_gomed','m_suertudo','m_sequia','m_rare','m_huevo','m_mundo','m_raza','m_apostol'],
                        shinys:['golbat','crobat','mienshao','manectric','magikarp','gyarados','tentacruel','swoobat','mamoswine','altaria','horsea','slugma','magcargo','duskull','lunatone','raticate','rattata',
                                'ditto','sandshrew','amoonguss','dodrio','mismagius','flygon','murkrow','tyranitar','hydreigon','chandelure','vanilluxe','whimsicott','smeargle','gliscor','spinda','krookodile','haxorus',
                                'zubat','graveler','golem','sableye','raichu','buizel','floatzel','garchomp','pikachu','dratini','durant','koffing','heatmor','duosion','shelmet'
                        ],
                        destacados:[{name: 'feraligatr', type: 'normal'},
                                {name: 'metagross', type: 'egg'},
                                {name: 'absol', type: 'egg'},
                                {name: 'charizard', type: 'egg'}
                        ],
                        perdidos: [],
                        vendidos: []
        },
        ToddGold: {   name:'ToddGold',
                        rol: 'Chad',
                        medallas:['m_raceW','m_arbol','m_apostol','m_supremacy3'],
                        shinys:['weavile','dragonair','kingdra','azumarill','ampharos','miltank','reuniclus','snover','nidorino','magcargo','deino','snorunt','graveler'
                        ],
                        destacados:[{name: 'aipom', type:'normal'}],
                        perdidos: [],
                        vendidos: []
        },
        ToxicPlumber: { name:'ToxicPlumber',
                        rol: 'GigaChad',
                        medallas:['m_gomed','m_guardian','m_meditite','m_safari','m_dead','m_secret','m_shunter','m_pescador','m_suertudo','m_huevo','m_arbol','m_raza','m_apostol','m_olimpiadas','m_aniMeD2025'],
                        shinys:['krookodile','raticate','venipede','weezing','nidoqueen','quagsire','altaria','kingdra','pichu','rattata','seaking','machamp','smeargle','gengar','chandelure','pidgey','ferrothorn','aggron',
                                'pelipper','scolipede','swellow','petilil','graveler','whismur','taillow','grimer','alakazam','crobat','marowak','noctowl','beautifly','reuniclus','rapidash','venonat','tentacruel','zubat',
                                'gigalith','vileplume','maractus','manectric','marowak','xatu','gyarados','baltoy','voltorb','lunatone','tyranitar','spinda','raticate','graveler','gloom','dodrio','slowbro','nidorina','phanpy','gligar'
                        ],
                        destacados:[{name: 'combee', type: 'normal'},
                                {name: 'corphish', type: 'normal'},
                                {name: 'metagross', type: 'normal'},
                                {name: 'starmie', type: 'egg'},
                                {name: 'swalot', type: 'egg'},
                                {name: 'marill', type: ['secret','safari']},
                        ],
                        perdidos: [{name: 'voltorb', type: 'normal'}],
                        vendidos: ['https://media.giphy.com/media/DzSVwMWmMHRiYqaLeC/giphy.gif']
        },
        UltimoMorador: {name:'UltimoMorador',
                        rol: 'Chad',
                        medallas:['m_shunter','m_suertudo','m_apostol'],
                        shinys:['bellossom','escavalier','litwick','donphan','machamp','graveler','graveler','weezing','dodrio','hariyama','masquerain','igglybuff','snubbull','mantyke','clamperl','marill','boldore','scraggy',
                                'tranquill','wobbuffet','smoochum','patrat','persian','sawk','xatu','makuhita','joltik','stoutland','cubchoo','donphan','hoppip','mankey','psyduck','claydol','poliwhirl','poliwhirl','swablu',
                                'spinda','marowak','zebstrika'
                        ],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        vitro: {        name:'vitro',
                        rol: 'Chad',
                        medallas:['m_dead','m_pecador','m_supremacy2','m_supremacy3'],
                        shinys:['magikarp','nidoking'],
                        destacados:[],
                        perdidos: [{name: 'druddigon', type: 'normal'},
                                {name: 'smeargle', type: 'normal'}
                        ],
                        vendidos: ['https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/apS40Kh2I8ZZiTD07i/giphy.gif',
                                'https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif'
                        ]
        },
        wallycbammo: {  name:'wallycbammo',
                        rol: 'Chad',
                        medallas:['m_dead','m_safari','m_suertudo','m_secret','m_huevo','m_apostol','m_shinywar','m_pecador'],
                        shinys:['pelipper','wurmple','wooper','venipede','tentacruel','raticate','magikarp','zigzagoon','ditto'],
                        destacados:[{name:'shedinja', type:'normal'},
                                {name:'poliwag', type:'safari'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/BC9Utvs1rCt1mS3uHy/giphy.gif']
        },
        xSorC: {        name:'xSorC',
                        rol: 'Chad',
                        medallas:['m_vacio'],
                        shinys:['duosion','bronzor','bibarel','graveler','smeargle','deino','woobat'],
                        destacados:[],
                        perdidos: [],
                        vendidos: []
        },
        YuukiTwo: {     name:'YuukiTwo',
                        rol: 'MaxiChad',
                        medallas:['m_gomed','m_cambio','m_guardian','m_pescador','m_huevo','m_pecador','m_apostol','m_supremacy3'],
                        shinys:['beedrill','sawsbuck','vileplume','nidoking','rhyperior','ninetales','kingdra'],
                        destacados:[{name: 'crawdaunt', type: 'normal'},
                                {name: 'skorupi', type: 'egg'},
                                {name: 'carvanha', type: 'normal'}
                        ],
                        perdidos: [],
                        vendidos: ['https://media.giphy.com/media/zs883L4G0LcaWp62Iv/giphy.gif',
                                'https://media.giphy.com/media/ofHxoizb5ZyN3uvFU6/giphy.gif',
                                'https://media.giphy.com/media/sugYeQQ0BUa6GUPdY2/giphy.gif',
                                'https://media.giphy.com/media/LWm8fjHUKxqb0qyZpD/giphy.gif'
                        ]
        },
        Zeurir: {       name:'Zeurir',
                        rol: 'Chad',
                        medallas:['m_dead','m_misterio','m_pecador'],
                        shinys:['ninetales','pelipper','quagsire','murkrow','ditto'],
                        destacados:[],
                        perdidos: [{name: 'smeargle', type: 'normal'}],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif',
                                'https://media.giphy.com/media/7eBAfbvAahCmhTreRI/giphy.gif',
                                'https://media.giphy.com/media/joRe8SDxlxpAZOQ8VQ/giphy.gif'
                        ]
        },
        zShilphye: {    name:'zShilphye',
                        rol: 'Chad',
                        medallas:['m_pecador','m_supremacy3'],
                        shinys:['mienfoo','mienfoo','golbat','duskull','onix','tentacruel','stantler','mamoswine','reuniclus','dodrio','durant','rapidash','ponyta'],
                        destacados:[],
                        perdidos:[],
                        vendidos: ['https://media.giphy.com/media/gYfpfKjVkjlLsJmKhF/giphy.gif']
        },
        Zulh: {         name:'Zulh',
                        rol: 'Chad',
                        medallas:['m_secret','m_suertudo','m_rare','m_huevo','m_goldenbox','m_raza','m_apostol','m_supremacy2','m_aniMeD2025'],
                        shinys:['golurk','tyranitar','lanturn','haxorus','aggron','pidove','haunter','steelix','darmanitan','magikarp','gyarados','gyarados','gorebyss','altaria','ferrothorn','grimer','grimer','muk',
                                'chandelure','wooper','quagsire','accelgor','torkoal','geodude','tentacool','duskull','dusclops','marill','camerupt','vanillite','vanilluxe','poliwrath','politoed','miltank','ponyta',
                                'ponyta','rapidash','kingdra','ludicolo','druddigon','weavile','krokorok','psyduck','gigalith','electrike','hydreigon','mienshao','ampharos','wingull','weezing','smeargle','banette',
                                'spinda','braviary','magneton','pikachu','whismur','raticate','ariados','nidorino','miltank','miltank','golbat','loudred','floatzel','gabite','dratini','sandshrew','electrike','cofagrigus',
                                'piloswine','pelipper','slowbro','diglett'
                        ],
                        destacados:[{name: 'charizard', type: 'egg'},
                                {name: 'breloom', type: 'egg'},
                                {name: 'pinsir', type: 'normal'},
                                {name: 'metagross', type: 'egg'},
                                {name: 'victreebel', type: 'secret'},
                                {name: 'spheal', type: ['secret','swarm']},
                                {name: 'bulbasaur', type: 'egg'},
                                {name: 'tropius', type: 'normal'},
                                {name: 'corphish', type: 'normal'},
                                {name: 'whismur', type: 'secret'}
                        ],
                        perdidos: [],
                        vendidos: []
        }
        
    };

function capitalize(str) {
        return str.charAt(0).toUpperCase() + str.slice(1);
}