const generations = {
  "Gen 1": ["bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon", "charizard",
  "squirtle", "wartortle", "blastoise", "caterpie", "metapod", "butterfree",
  "weedle", "kakuna", "beedrill", "pidgey", "pidgeotto", "pidgeot", "rattata",
  "raticate", "spearow", "fearow", "ekans", "arbok", "pikachu", "raichu",
  "sandshrew", "sandslash", "nidoran-f", "nidorina", "nidoqueen", "nidoran-m",
  "nidorino", "nidoking", "clefairy", "clefable", "vulpix", "ninetales",
  "jigglypuff", "wigglytuff", "zubat", "golbat", "oddish", "gloom", "vileplume",
  "paras", "parasect", "venonat", "venomoth", "diglett", "dugtrio", "meowth",
  "persian", "psyduck", "golduck", "mankey", "primeape", "growlithe", "arcanine",
  "poliwag", "poliwhirl", "poliwrath", "abra", "kadabra", "alakazam", "machop",
  "machoke", "machamp", "bellsprout", "weepinbell", "victreebel", "tentacool",
  "tentacruel", "geodude", "graveler", "golem", "ponyta", "rapidash", "slowpoke",
  "slowbro", "magnemite", "magneton", "farfetchd", "doduo", "dodrio", "seel",
  "dewgong", "grimer", "muk", "shellder", "cloyster", "gastly", "haunter",
  "gengar", "onix", "drowzee", "hypno", "krabby", "kingler", "voltorb",
  "electrode", "exeggcute", "exeggutor", "cubone", "marowak", "hitmonlee",
  "hitmonchan", "lickitung", "koffing", "weezing", "rhyhorn", "rhydon",
  "chansey", "tangela", "kangaskhan", "horsea", "seadra", "goldeen", "seaking",
  "staryu", "starmie", "mr-mime", "scyther", "jynx", "electabuzz", "magmar",
  "pinsir", "tauros", "magikarp", "gyarados", "lapras", "ditto", "eevee",
  "vaporeon", "jolteon", "flareon", "porygon", "omanyte", "omastar", "kabuto",
  "kabutops", "aerodactyl", "snorlax",/* "articuno", "zapdos", "moltres",*/
  "dratini", "dragonair", "dragonite"],

  "Gen 2": ["chikorita", "bayleef", "meganium", "cyndaquil", "quilava", "typhlosion",
  "totodile", "croconaw", "feraligatr", "sentret", "furret", "hoothoot",
  "noctowl", "ledyba", "ledian", "spinarak", "ariados", "crobat", "chinchou",
  "lanturn", "pichu", "cleffa", "igglybuff", "togepi", "togetic", "natu",
  "xatu", "mareep", "flaaffy", "ampharos", "bellossom", "marill", "azumarill",
  "sudowoodo", "politoed", "hoppip", "skiploom", "jumpluff", "aipom", "sunkern",
  "sunflora", "yanma", "wooper", "quagsire", "espeon", "umbreon", "murkrow",
  "slowking", "misdreavus", "unown", "wobbuffet", "girafarig", "pineco",
  "forretress", "dunsparce", "gligar", "steelix", "snubbull", "granbull",
  "qwilfish", "scizor", "shuckle", "heracross", "sneasel", "teddiursa",
  "ursaring", "slugma", "magcargo", "swinub", "piloswine", "corsola",
  "remoraid", "octillery", "delibird", "mantine", "skarmory", "houndour",
  "houndoom", "kingdra", "phanpy", "donphan", "porygon2", "stantler",
  "smeargle", "tyrogue", "hitmontop", "smoochum", "elekid", "magby",
  "miltank", "blissey",/* "raikou", "entei", "suicune", */"larvitar", "pupitar",
  "tyranitar"],

  "Gen 3": ["treecko", "grovyle", "sceptile", "torchic", "combusken", "blaziken",
  "mudkip", "marshtomp", "swampert", "poochyena", "mightyena", "zigzagoon",
  "linoone", "wurmple", "silcoon", "beautifly", "cascoon", "dustox", "lotad",
  "lombre", "ludicolo", "seedot", "nuzleaf", "shiftry", "taillow", "swellow",
  "wingull", "pelipper", "ralts", "kirlia", "gardevoir", "surskit",
  "masquerain", "shroomish", "breloom", "slakoth", "vigoroth", "slaking",
  "nincada", "ninjask", "shedinja", "whismur", "loudred", "exploud",
  "makuhita", "hariyama", "azurill", "nosepass", "skitty", "delcatty",
  "sableye", "mawile", "aron", "lairon", "aggron", "meditite", "medicham",
  "electrike", "manectric", "plusle", "minun", "volbeat", "illumise",
  "roselia", "gulpin", "swalot", "carvanha", "sharpedo", "wailmer",
  "wailord", "numel", "camerupt", "torkoal", "spoink", "grumpig",
  "spinda", "trapinch", "vibrava", "flygon", "cacnea", "cacturne",
  "swablu", "altaria", "zangoose", "seviper", "lunatone", "solrock",
  "barboach", "whiscash", "corphish", "crawdaunt", "baltoy", "claydol",
  "lileep", "cradily", "anorith", "armaldo", "feebas", "milotic",
  "castform", "kecleon", "shuppet", "banette", "duskull", "dusclops",
  "tropius", "chimecho", "absol", "wynaut", "snorunt", "glalie",
  "spheal", "sealeo", "walrein", "clamperl", "huntail", "gorebyss",
  "relicanth", "luvdisc", "bagon", "shelgon", "salamence",
  "beldum", "metang", "metagross",/*"jirachi"*/],

  "Gen 4": [ "turtwig", "grotle", "torterra", "chimchar", "monferno", "infernape",
  "piplup", "prinplup", "empoleon", "starly", "staravia", "staraptor",
  "bidoof", "bibarel", "kricketot", "kricketune", "shinx", "luxio", "luxray",
  "budew", "roserade", "cranidos", "rampardos", "shieldon", "bastiodon",
  "burmy", "wormadam", "mothim", "combee", "vespiquen", "pachirisu",
  "buizel", "floatzel", "cherubi", "cherrim", "shellos", "gastrodon",
  "ambipom", "drifloon", "drifblim", "buneary", "lopunny", "mismagius",
  "honchkrow", "glameow", "purugly", "chingling", "stunky", "skuntank",
  "bronzor", "bronzong", "bonsly", "mime-jr", "happiny", "chatot",
  "spiritomb", "gible", "gabite", "garchomp", "munchlax", "riolu", "lucario",
  "hippopotas", "hippowdon", "skorupi", "drapion", "croagunk", "toxicroak",
  "carnivine", "finneon", "lumineon", "mantyke", "snover", "abomasnow",
  "weavile", "magnezone", "lickilicky", "rhyperior", "tangrowth",
  "electivire", "magmortar", "togekiss", "yanmega", "leafeon", "glaceon",
  "gliscor", "mamoswine", "porygon-z", "gallade", "probopass", "dusknoir",
  "froslass", "rotom"/*,"heatran","darkrai", "shaymin",*/],

  "Gen 5": ["snivy", "servine", "serperior", "tepig", "pignite", "emboar",
  "oshawott", "dewott", "samurott", "patrat", "watchog", "lillipup", "herdier",
  "stoutland", "purrloin", "liepard", "pansage", "simisage", "pansear", "simisear",
  "panpour", "simipour", "munna", "musharna", "pidove", "tranquill", "unfezant",
  "blitzle", "zebstrika", "roggenrola", "boldore", "gigalith", "woobat",
  "swoobat", "drilbur", "excadrill", "audino", "timburr", "gurdurr", "conkeldurr",
  "tympole", "palpitoad", "seismitoad", "throh", "sawk", "sewaddle", "swadloon",
  "leavanny", "venipede", "whirlipede", "scolipede", "cottonee", "whimsicott",
  "petilil", "lilligant", "basculin", "sandile", "krokorok", "krookodile",
  "darumaka", "darmanitan", "maractus", "dwebble", "crustle", "scraggy",
  "scrafty", "sigilyph", "yamask", "cofagrigus", "tirtouga", "carracosta",
  "archen", "archeops", "trubbish", "garbodor", "zorua", "zoroark", "minccino",
  "cinccino", "gothita", "gothorita", "gothitelle", "solosis", "duosion",
  "reuniclus", "ducklett", "swanna", "vanillite", "vanillish", "vanilluxe",
  "deerling", "sawsbuck", "emolga", "karrablast", "escavalier", "foongus",
  "amoonguss", "frillish", "jellicent", "alomomola", "joltik", "galvantula",
  "ferroseed", "ferrothorn", "klink", "klang", "klinklang", "tynamo",
  "eelektrik", "eelektross", "elgyem", "beheeyem", "litwick", "lampent",
  "chandelure", "axew", "fraxure", "haxorus", "cubchoo", "beartic", "cryogonal",
  "shelmet", "accelgor", "stunfisk", "mienfoo", "mienshao", "druddigon",
  "golett", "golurk", "pawniard", "bisharp", "bouffalant", "rufflet",
  "braviary", "vullaby", "mandibuzz", "heatmor", "durant", "deino",
  "zweilous", "hydreigon", "larvesta", "volcarona"],
};

const otherdex = {
  /*"Burmy": ["burmy-plant","burmy-sandy","burmy-trash"],

  "Wormadam": ["wormadam-plant","wormadam-sandy","wormadam-trash"],*/

  "Shellos": ["shellos-west",'shellos-east'],

  "Gastrodon": ["gastrodon-west",'gastrodon-east'],

  "Deerling": ["deerling-summer",'deerling-autumn','deerling-winter','deerling-spring'],

  "Sawsbuck": ["sawsbuck-summer",'sawsbuck-autumn','sawsbuck-winter','sawsbuck-spring'],

  "Basculin": ["basculin-red-striped","basculin-blue-striped"],
};

const unowndex = {
  "Unown": ["unown-a","unown-b","unown-c","unown-d","unown-e","unown-f","unown-g","unown-h","unown-i","unown-j","unown-k","unown-l",
            "unown-m","unown-n","unown-o","unown-p","unown-q","unown-r","unown-s","unown-t","unown-u","unown-v","unown-w","unown-x",
            "unown-y","unown-z","unown-em","unown-qm"
  ],
};

const capturedBy = {
  bulbasaur: [ "Maicol","Maicol"],
  ivysaur: [ "Maicol","Maicol"],
  venusaur: [ "Maicol","Maicol"],
  charmander: [ "Tokyopp","Tokyopp"],
  charmeleon: [ "Tokyopp","Tokyopp"],
  charizard: [ "Tokyopp","Tokyopp"],
  squirtle: [ "Azathotx","Azathotx"],
  wartortle: [ "Azathotx","Azathotx"],
  blastoise: [ "Azathotx","Azathotx"],
  caterpie: [ "Moonlyze","Moonlyze"],
  metapod: [ "YuukiTwo","YuukiTwo"],
  butterfree: [ "LifeTown","LifeTown"],
  weedle: [ "nyumichaelis","nyumichaelis"],
  kakuna: [ "MangoOscuro","MangoOscuro"],
  beedrill: [ "ISilverJR","ISilverJR"],
  pidgey: [ "Pancho","Pancho"],
  pidgeotto: [ "Pancho","SantiagoYTGamer"],
  pidgeot: [ "Pancho","Pancho"],
  rattata: [ "ToxicPlumber","ToxicPlumber"],
  raticate: [ "MangoOscuro","MangoOscuro"],
  spearow: [ "AlexisBlu","AlexisBlu"],
  fearow: [ "DavidCitos","faulheitt"],
  ekans: [ "PierciLmL","PierciLmL"],
  arbok: [ "MonkeyCake","MonkeyCake"],
  pikachu: [ "DavidCitos","DavidCitos"],
  raichu: [ "Krampus","Krampus"],
  sandshrew: [ "TheJesucristian","TheJesucristian"],
  sandslash: [ "aeamanh","aeamanh"],
  "nidoran-f": [ "ToxicPlumber","ToxicPlumber"],
  nidorina: [ "MonkeyCake","MonkeyCake"],
  nidoqueen: [ "ToxicPlumber","ToxicPlumber"],
  "nidoran-m": [ "ToxicPlumber","ToxicPlumber"],
  nidorino: [ "Alicia","Infergenico"],
  nidoking: [ "OreganoPVP","OreganoPVP"],
  clefairy: [ "MarkosW","MarkosW"],
  clefable: [ "MarkosW","MarkosW"],
  vulpix: [ "Renz","Renz"],
  ninetales: [ "Renz","Renz"],
  jigglypuff: [ "DavidCitos","DavidCitos"],
  wigglytuff: [ "Moonlyze","Moonlyze"],
  zubat: [ "TheJesucristian","emmawa"],
  golbat: [ "Souen","chunchumaru"],
  oddish: [ "FranCRLZ","Yupixz"],
  gloom: [ "KnowJiYong","chunchumaru"],
  vileplume: [ "Pancho","Pancho"],
  paras: [ "Alicia","Alicia"],
  parasect: [ "UltimoMorador","UltimoMorador"],
  venonat: [ "Azathotx","Azathotx"],
  venomoth: [ "Azathotx","Azathotx"],
  diglett: [ "Azathotx","chunchumaru"],
  dugtrio: [ "Azathotx","Azathotx"],
  meowth: [ "DavidCitos","Palafo"],
  persian: [ "UltimoMorador","BlueKahil"],
  psyduck: [ "MonkeyCake","MonkeyCake"],
  golduck: [ "ritosenpai","ritosenpai"],
  mankey: [ "Krackon","Krackon"],
  primeape: [ "aeamanh","aeamanh"],
  growlithe: [ "Pancho","NicolaxYTxD"],
  arcanine: [ "Souen","Souen"],
  poliwag: [ "DavidCitos","Zophine"],
  poliwhirl: [ "DavidCitos","ElConejoLoco"],
  poliwrath: [ "Lirio","GamerManco"],
  abra: [ "LifeTown","LifeTown"],
  kadabra: [ "Maxii","LifeTown"],
  alakazam: [ "ToxicPlumber","ToxicPlumber"],
  machop: [ "Palafo","Palafo"],
  machoke: [ "ToxicPlumber","ToxicPlumber"],
  machamp: [ "ToxicPlumber","ToxicPlumber"],
  bellsprout: [ "ElMiga","ElMiga"],
  weepinbell: [ "JJean","Palafo"],
  victreebel: [ "Palafo","Palafo"],
  tentacool: [ "ToxicPlumber","shubhom"],
  tentacruel: [ "ToxicPlumber","ToxicPlumber"],
  geodude: [ "ritosenpai","ritosenpai"],
  graveler: [ "DavidCitos","Menetreitor"],
  golem: [ "Pancho","INotAaron"],
  ponyta: [ "Krackon","Palafo"],
  rapidash: [ "Renz","Renz"],
  slowpoke: [ "Jabubuu","Portapapel"],
  slowbro: [ "Lirio","cqm1lo"],
  magnemite: [ "DavidCitos","DavidCitos"],
  magneton: [ "aeamanh","aeamanh"],
  farfetchd: [ "AdrixJK","AdrixJK"],
  doduo: [ "Krampus","Krampus"],
  dodrio: [ "Krackon","Krackon"],
  seel: [ "KnowJiYong","KnowJiYong"],
  dewgong: [ "KnowJiYong","KnowJiYong"],
  grimer: [ "DavidCitos","DavidCitos"],
  muk: [ "Snip","Snip"],
  shellder: [ "JuniorJMx","JuniorJMx"],
  cloyster: [ "XxsvrgioxX","XxsvrgioxX"],
  gastly: [ "ToxicPlumber","ToxicPlumber"],
  haunter: [ "RIIW","honesto"],
  gengar: [ "ToxicPlumber","ToxicPlumber"],
  onix: [ "DavidCitos","DavidCitos"],
  drowzee: [ "Krackon","Palafo"],
  hypno: [ "DavidCitos","Palafo"],
  krabby: [ "MasterFox","MasterFox"],
  kingler: [ "Maxii","Maxii"],
  voltorb: [ "DavidCitos","Pastruki"],
  electrode: [ "Salva","Salva"],
  cubone: [ "AlexisBlu","AlexisBlu"],
  marowak: [ "ToxicPlumber","ToxicPlumber"],
  lickitung: [ "Pancho","Pancho"],
  koffing: [ "ToxicPlumber","ToxicPlumber"],
  weezing: [ "DavidCitos","DavidCitos"],
  rhyhorn: [ "YuukiTwo","YuukiTwo"],
  rhydon: [ "DavidCitos","DavidCitos"],
  chansey: [ "Krackon","Krackon"],
  tangela: [ "Pancho","Palafo"],
  horsea: [ "Renz","Renz"],
  seadra: [ "Renz","Renz"],
  goldeen: [ "chunchumaru","chunchumaru"],
  seaking: [ "ToxicPlumber","ToxicPlumber"],
  staryu: [ "ToddGold","ToddGold"],
  starmie: [ "ToddGold","ToddGold"],
  scyther: [ "ritosenpai","ritosenpai"],
  jynx: [ "JuniorJMx","JuniorJMx"],
  electabuzz: [ "DavidCitos","DavidCitos"],
  magmar: [ "DavidCitos","DavidCitos"],
  pinsir: [ "JJean","JJean"],
  tauros: [ "KnowJiYong","KnowJiYong"],
  magikarp: [ "DavidCitos","Palafo"],
  gyarados: [ "ToxicPlumber","ToxicPlumber"],
  lapras: [ "AshFifero","AshFifero"],
  ditto: [ "Silvaryl","INotAaron"],
  eevee: [ "Alicia","Alicia"],
  vaporeon: [ "Jabubuu","Jabubuu"],
  jolteon: [ "ritosenpai","ritosenpai"],
  flareon: [ "Jabubuu","Jabubuu"],
  porygon: [ "Alicia","Alicia"],
  kabuto: [ "chunchumaru","chunchumaru"],
  kabutops: [ "chunchumaru","chunchumaru"],
  snorlax: [ "DiGoMo","XxsvrgioxX"],
  dratini: [ "KilluaZoldyck","attomico"],
  dragonair: [ "rebukittheveil","rebukittheveil"],
  dragonite: [ "Souen","siriussan"],
  cyndaquil: [ "Mxxarc","Mxxarc"],
  quilava: [ "Mxxarc","Mxxarc"],
  typhlosion: [ "Mxxarc","Mxxarc"],
  totodile: [ "TheJesucristian","TheJesucristian"],
  croconaw: [ "TheJesucristian","TheJesucristian"],
  feraligatr: [ "TheJesucristian","TheJesucristian"],
  sentret: [ "Pancho","Pancho"],
  furret: [ "Doce","Doce"],
  hoothoot: [ "Krackon","Krackon"],
  noctowl: [ "ToxicPlumber","ToxicPlumber"],
  ledyba: [ "Silvaryl","Silvaryl"],
  ledian: [ "Silvaryl","Silvaryl"],
  spinarak: [ "Hectoralberto","Hectoralberto"],
  ariados: [ "Hectoralberto","Hectoralberto"],
  crobat: [ "ToxicPlumber","ToxicPlumber"],
  chinchou: [ "Cypher","Cypher"],
  lanturn: [ "Akalii","Akalii"],
  pichu: [ "ToxicPlumber","ToxicPlumber"],
  cleffa: [ "MarkosW","MarkosW"],
  igglybuff: [ "UltimoMorador","UltimoMorador"],
  natu: [ "ToxicPlumber","ToxicPlumber"],
  xatu: [ "ToxicPlumber","ToxicPlumber"],
  mareep: [ "Silvaryl","Silvaryl"],
  flaaffy: [ "attomico","attomico"],
  ampharos: [ "Lirio","JerichoKenobii"],
  bellossom: [ "Jabubuu","Palafo"],
  marill: [ "DavidCitos","DavidCitos"],
  azumarill: [ "MonkeyCake","MonkeyCake"],
  sudowoodo: [ "Tyrantrum","Tyrantrum"],
  politoed: [ "Ingrid","ElConejoLoco"],
  hoppip: [ "Doce","Doce"],
  skiploom: [ "Doce","Doce"],
  jumpluff: [ "Akalii","Akalii"],
  sunkern: [ "MarkosW","MarkosW"],
  sunflora: [ "MarkosW","MarkosW"],
  wooper: [ "Renz","Renz"],
  quagsire: [ "Renz","Renz"],
  espeon: [ "Alicia","Alicia"],
  umbreon: [ "Jabubuu","Jabubuu"],
  murkrow: [ "XIGoroxlX","Wildfredo"],
  slowking: [ "Jabubuu","Portapapel"],
  misdreavus: [ "Renz","Renz"],
  unown: [ "vitro","vitro"],
  wobbuffet: [ "DavidCitos","DavidCitos"],
  girafarig: [ "Mikuwuu","Mikuwuu"],
  dunsparce: [ "Iucifer","Kennrykake"],
  gligar: [ "DavidCitos","Wildfredo"],
  steelix: [ "nyumichaelis","nyumichaelis"],
  snubbull: [ "UltimoMorador","UltimoMorador"],
  granbull: [ "UltimoMorador","UltimoMorador"],
  scizor: [ "ritosenpai","ritosenpai"],
  heracross: [ "OreganoPVP","OreganoPVP"],
  sneasel: [ "DavidCitos","DavidCitos"],
  teddiursa: [ "MixZeppeli","MixZeppeli"],
  ursaring: [ "DavidCitos","IagoMLS"],
  slugma: [ "Doce","chunchumaru"],
  magcargo: [ "TheJesucristian","TheJesucristian"],
  swinub: [ "AdrixJK","AdrixJK"],
  piloswine: [ "YuukiTwo","ssKaori"],
  corsola: [ "MasterFox","MasterFox"],
  remoraid: [ "Souen","Souen"],
  octillery: [ "Souen","Souen"],
  delibird: [ "Lirio","Lirio"],
  mantine: [ "OreganoPVP","OreganoPVP"],
  skarmory: [ "sadending","sadending"],
  houndour: [ "ritosenpai","ritosenpai"],
  houndoom: [ "ritosenpai","ritosenpai"],
  kingdra: [ "Renz","Renz"],
  phanpy: [ "nyumichaelis","nyumichaelis"],
  donphan: [ "Krackon","Wildfredo"],
  porygon2: [ "Alicia","Alicia"],
  stantler: [ "Moonlyze","Moonlyze"],
  smeargle: [ "ToxicPlumber","ToxicPlumber"],
  smoochum: [ "UltimoMorador","UltimoMorador"],
  magby: [ "DiGoMo","DiGoMo"],
  miltank: [ "DavidCitos","DavidCitos"],
  larvitar: [ "ToxicPlumber","Treeecko"],
  pupitar: [ "ToxicPlumber","ToxicPlumber"],
  tyranitar: [ "ToxicPlumber","ToxicPlumber"],
  treecko: [ "DavidCitos","IagoMLS"],
  grovyle: [ "Misaki","Misaki"],
  sceptile: [ "Misaki","Misaki"],
  mudkip: [ "ritosenpai","ritosenpai"],
  marshtomp: [ "ritosenpai","ritosenpai"],
  swampert: [ "ritosenpai","ritosenpai"],
  poochyena: [ "Akalii","Akalii"],
  mightyena: [ "MangoOscuro","MangoOscuro"],
  zigzagoon: [ "Krackon","Krackon"],
  linoone: [ "ritosenpai","ritosenpai"],
  wurmple: [ "nyumichaelis","nyumichaelis"],
  silcoon: [ "nyumichaelis","nyumichaelis"],
  beautifly: [ "ToxicPlumber","ToxicPlumber"],
  cascoon: [ "nyumichaelis","nyumichaelis"],
  dustox: [ "nyumichaelis","nyumichaelis"],
  lotad: [ "Azathotx","Azathotx"],
  lombre: [ "UltimoMorador","UltimoMorador"],
  ludicolo: [ "MonkeyCake","MonkeyCake"],
  seedot: [ "Guabixd","Guabixd"],
  nuzleaf: [ "Guabixd","Guabixd"],
  shiftry: [ "Guabixd","Guabixd"],
  taillow: [ "ToxicPlumber","ToxicPlumber"],
  swellow: [ "ToxicPlumber","ToxicPlumber"],
  wingull: [ "ToxicPlumber","ToxicPlumber"],
  pelipper: [ "XIGoroxlX","XIGoroxlX"],
  ralts: [ "Akalii","Akalii"],
  kirlia: [ "IxGab","IxGab"],
  gardevoir: [ "DavidCitos","elKiwiz"],
  surskit: [ "KnowJiYong","Palafo"],
  masquerain: [ "Palafo","Palafo"],
  shroomish: [ "KnowJiYong","KnowJiYong"],
  breloom: [ "KnowJiYong","KnowJiYong"],
  slakoth: [ "Estorbiito","Estorbiito"],
  vigoroth: [ "Estorbiito","Estorbiito"],
  slaking: [ "Estorbiito","Estorbiito"],
  nincada: [ "ritosenpai","ritosenpai"],
  ninjask: [ "ritosenpai","ritosenpai"],
  shedinja: [ "wallycbammo","wallycbammo"],
  whismur: [ "Hectoralberto","MixZeppeli"],
  loudred: [ "Akalii","lMatzu"],
  exploud: [ "Martxn","Martxn"],
  makuhita: [ "UltimoMorador","UltimoMorador"],
  hariyama: [ "DavidCitos","DavidCitos"],
  azurill: [ "Jabubuu","Jabubuu"],
  skitty: [ "Mikuwuu","Mikuwuu"],
  delcatty: [ "Mikuwuu","Mikuwuu"],
  sableye: [ "ritosenpai","ritosenpai"],
  mawile: [ "ritosenpai","ritosenpai"],
  aron: [ "ToxicPlumber","ToxicPlumber"],
  lairon: [ "ToxicPlumber","ToxicPlumber"],
  aggron: [ "ToxicPlumber","ToxicPlumber"],
  meditite: [ "Renz","Renz"],
  medicham: [ "ToxicPlumber","ToxicPlumber"],
  electrike: [ "DavidCitos","chunchumaru"],
  manectric: [ "ToxicPlumber","ToxicPlumber"],
  volbeat: [ "ritosenpai","ritosenpai"],
  illumise: [ "aeamanh","aeamanh"],
  roselia: [ "DavidCitos","DavidCitos"],
  gulpin: [ "ToxicPlumber","ToxicPlumber"],
  swalot: [ "ToxicPlumber","ToxicPlumber"],
  carvanha: [ "JuniorJMx","JuniorJMx"],
  sharpedo: [ "Akalii","Akalii"],
  wailmer: [ "AshFifero","AshFifero"],
  wailord: [ "ErnestoSwampert","ErnestoSwampert"],
  numel: [ "Alicia","Alicia"],
  camerupt: [ "KnowJiYong","KnowJiYong"],
  torkoal: [ "Moonlyze","chunchumaru"],
  spoink: [ "Palafo","Palafo"],
  spinda: [ "Krackon","IIHeartDragonsII"],
  trapinch: [ "DavidCitos","DavidCitos"],
  vibrava: [ "TheJesucristian","TheJesucristian"],
  flygon: [ "ritosenpai","ritosenpai"],
  cacnea: [ "JUANKAXGARCIA","jerryeric"],
  cacturne: [ "JuniorJMx","jerryeric"],
  swablu: [ "DavidCitos","DavidCitos"],
  altaria: [ "Krackon","Domotwo"],
  zangoose: [ "Ashy","XxsvrgioxX"],
  seviper: [ "ritosenpai","ritosenpai"],
  lunatone: [ "ToxicPlumber","ToxicPlumber"],
  solrock: [ "DavidCitos","DavidCitos"],
  barboach: [ "Palafo","Palafo"],
  whiscash: [ "Palafo","Palafo"],
  corphish: [ "ToxicPlumber","ToxicPlumber"],
  crawdaunt: [ "YuukiTwo","YuukiTwo"],
  baltoy: [ "ToxicPlumber","ToxicPlumber"],
  claydol: [ "KnowJiYong","KnowJiYong"],
  feebas: [ "MrCartago","MrCartago"],
  milotic: [ "MrCartago","MrCartago"],
  kecleon: [ "Azathotx","Azathotx"],
  shuppet: [ "KnowJiYong","KnowJiYong"],
  banette: [ "DavidCitos","DavidCitos"],
  duskull: [ "DavidCitos","DavidCitos"],
  dusclops: [ "Maxii","Maxii"],
  absol: [ "TheJesucristian","MixZeppeli"],
  wynaut: [ "ritosenpai","ritosenpai"],
  snorunt: [ "Akalii","Akalii"],
  glalie: [ "KnowJiYong","KnowJiYong"],
  spheal: [ "JJean","JJean"],
  sealeo: [ "DavidCitos","DavidCitos"],
  walrein: [ "xDerxx","xDerxx"],
  clamperl: [ "Iucifer","Iucifer"],
  huntail: [ "Iucifer","Iucifer"],
  gorebyss: [ "Jabubuu","Jabubuu"],
  luvdisc: [ "Martxn","Martxn"],
  bagon: [ "chunchumaru","chunchumaru"],
  salamence: [ "chunchumaru","chunchumaru"],
  beldum: [ "ToxicPlumber","ToxicPlumber"],
  metang: [ "ToxicPlumber","ToxicPlumber"],
  metagross: [ "ToxicPlumber","ToxicPlumber"],
  turtwig: [ "Gusteiv","Gusteiv"],
  grotle: [ "Gusteiv","Gusteiv"],
  torterra: [ "Gusteiv","Gusteiv"],
  chimchar: [ "Akalii","Akalii"],
  monferno: [ "Akalii","Akalii"],
  infernape: [ "Akalii","Akalii"],
  starly: [ "ElMiga","ElMiga"],
  staravia: [ "JuniorJMx","JuniorJMx"],
  staraptor: [ "ElMiga","ElMiga"],
  bidoof: [ "XxsvrgioxX","XxsvrgioxX"],
  bibarel: [ "Moonlyze","Moonlyze"],
  kricketot: [ "Souen","Souen"],
  kricketune: [ "JuniorJMx","JuniorJMx"],
  shinx: [ "Akalii","Akalii"],
  luxio: [ "Cece","Cece"],
  luxray: [ "Krackon","Krackon"],
  budew: [ "Pancho","iYerson"],
  roserade: [ "DavidCitos","DavidCitos"],
  cranidos: [ "OniED","OniED"],
  shieldon: [ "chunchumaru","chunchumaru"],
  bastiodon: [ "chunchumaru","chunchumaru"],
  burmy: [ "KnowJiYong","KnowJiYong"],
  wormadam: [ "KnowJiYong","KnowJiYong"],
  mothim: [ "KnowJiYong","KnowJiYong"],
  combee: [ "ToxicPlumber","ToxicPlumber"],
  pachirisu: [ "Akalii","Akalii"],
  buizel: [ "MangoOscuro","MangoOscuro"],
  floatzel: [ "Gusteiv","Gusteiv"],
  shellos: [ "Souen","Souen"],
  gastrodon: [ "Azathotx","Azathotx"],
  drifblim: [ "ritosenpai","ritosenpai"],
  buneary: [ "DavidCitos","DavidCitos"],
  lopunny: [ "DavidCitos","DavidCitos"],
  mismagius: [ "Renz","Renz"],
  honchkrow: [ "Lirio","Lirio"],
  glameow: [ "Reimy","Reimy"],
  purugly: [ "XIGoroxlX","XIGoroxlX"],
  stunky: [ "ritosenpai","ritosenpai"],
  skuntank: [ "JuniorJMx","JuniorJMx"],
  bronzor: [ "Akalii","Akalii"],
  bronzong: [ "DavidCitos","DavidCitos"],
  "mime-jr": [ "Seaba","Seaba"],
  chatot: [ "Ingrid","Veilia"],
  gible: [ "Akalii","lMatzu"],
  gabite: [ "Gusteiv","Gusteiv"],
  garchomp: [ "Lirio","Lirio"],
  munchlax: [ "Gamermanco","Gamermanco"],
  riolu: [ "Pancho","Pancho"],
  lucario: [ "Pancho","Pancho"],
  hippopotas: [ "aeamanh","aeamanh"],
  hippowdon: [ "aeamanh","aeamanh"],
  skorupi: [ "YuukiTwo","YuukiTwo"],
  drapion: [ "YuukiTwo","YuukiTwo"],
  finneon: [ "KnowJiYong","KnowJiYong"],
  lumineon: [ "KnowJiYong","KnowJiYong"],
  mantyke: [ "UltimoMorador","UltimoMorador"],
  snover: [ "DavidCitos","DavidCitos"],
  abomasnow: [ "KnowJiYong","KnowJiYong"],
  weavile: [ "DavidCitos","iYerson"],
  magnezone: [ "DavidCitos","DavidCitos"],
  lickilicky: [ "Pancho","Pancho"],
  rhyperior: [ "YuukiTwo","YuukiTwo"],
  tangrowth: [ "Pancho","Pancho"],
  electivire: [ "iYerson","iYerson"],
  magmortar: [ "DiGoMo","DiGoMo"],
  leafeon: [ "Mittoh","Mittoh"],
  gliscor: [ "TheJesucristian","Wildfredo"],
  mamoswine: [ "TheJesucristian","TheJesucristian"],
  "porygon-z": [ "Alicia","Alicia"],
  gallade: [ "Mexb","Mexb"],
  probopass: [ "JuniorJMx","JuniorJMx"],
  dusknoir: [ "Seaba","Seaba"],
  froslass: [ "Lirio","Lirio"],
  rotom: [ "Alicia","Alicia"],
  snivy: [ "Krackon","Krackon"],
  servine: [ "Krackon","Krackon"],
  serperior: [ "Krackon","Krackon"],
  tepig: [ "Xiopand","Xiopand"],
  pignite: [ "Xiopand","Xiopand"],
  emboar: [ "Xiopand","Xiopand"],
  oshawott: [ "Seaba","Seaba"],
  dewott: [ "Seaba","Seaba"],
  samurott: [ "Seaba","Seaba"],
  patrat: [ "UltimoMorador","UltimoMorador"],
  watchog: [ "Krackon","watchog"],
  lillipup: [ "UltimoMorador","UltimoMorador"],
  herdier: [ "ritosenpai","ritosenpai"],
  stoutland: [ "UltimoMorador","UltimoMorador"],
  purrloin: [ "Pancho","Pancho"],
  liepard: [ "Seaba","Wildfredo"],
  pansage: [ "aeamanh","aeamanh"],
  simisage: [ "Muertexx","Muertexx"],
  pansear: [ "Pancho","Pancho"],
  simisear: [ "Pancho","Pancho"],
  munna: [ "Jabubuu","Jabubuu"],
  pidove: [ "ritosenpai","FGMarck"],
  tranquill: [ "DavidCitos","DavidCitos"],
  unfezant: [ "UltimoMorador","UltimoMorador"],
  blitzle: [ "Guabixd","Guabixd"],
  zebstrika: [ "Guabixd","Guabixd"],
  roggenrola: [ "UltimoMorador","UltimoMorador"],
  boldore: [ "Salva","Salva"],
  gigalith: [ "ToxicPlumber","ToxicPlumber"],
  woobat: [ "DavidCitos","chunchumaru"],
  swoobat: [ "Iucifer","Iucifer"],
  timburr: [ "Krackon","Krackon"],
  gurdurr: [ "DavidCitos","DavidCitos"],
  conkeldurr: [ "Lirio","Lirio"],
  tympole: [ "pimientadaza","pimientadaza"],
  palpitoad: [ "DavidCitos","DavidCitos"],
  seismitoad: [ "pimientadaza","pimientadaza"],
  sawk: [ "UltimoMorador","UltimoMorador"],
  sewaddle: [ "ermifeNoPremium","ermifeNoPremium"],
  swadloon: [ "UltimoMorador","UltimoMorador"],
  leavanny: [ "UltimoMorador","UltimoMorador"],
  venipede: [ "YuukiTwo","YuukiTwo"],
  whirlipede: [ "ToxicPlumber","emmawa"],
  scolipede: [ "Doce","emmawa"],
  cottonee: [ "Akalii","Akalii"],
  whimsicott: [ "XIGoroxlX","XIGoroxlX"],
  petilil: [ "Spirati","chunchumaru"],
  lilligant: [ "JuniorJMx","Wildfredo"],
  basculin: [ "DavidCitos","DavidCitos"],
  sandile: [ "Cypher","Cypher"],
  krokorok: [ "Snip","chunchumaru"],
  krookodile: [ "ToxicPlumber","ToxicPlumber"],
  darumaka: [ "ritosenpai","ritosenpai"],
  darmanitan: [ "Krampus","Krampus"],
  maractus: [ "ToxicPlumber","ToxicPlumber"],
  dwebble: [ "MasterFox","MasterFox"],
  crustle: [ "MasterFox","MasterFox"],
  scraggy: [ "Mittoh","Mittoh"],
  scrafty: [ "Silvaryl","Silvaryl"],
  sigilyph: [ "LauraSkylar","LauraSkylar"],
  yamask: [ "JUANKAXGARCIA","JUANKAXGARCIA"],
  cofagrigus: [ "DavidCitos","DavidCitos"],
  tirtouga: [ "AlexisBlu","AlexisBlu"],
  trubbish: [ "JuniorJMx","JuniorJMx"],
  garbodor: [ "JuniorJMx","JuniorJMx"],
  zorua: [ "nyumichaelis","shubhom"],
  zoroark: [ "chunchumaru","chunchumaru"],
  minccino: [ "KnowJiYong","KnowJiYong"],
  cinccino: [ "KnowJiYong","KnowJiYong"],
  gothita: [ "AdrixJK","AdrixJK"],
  gothorita: [ "MasterFox","MasterFox"],
  gothitelle: [ "MasterFox","MasterFox"],
  duosion: [ "Renz","Renz"],
  reuniclus: [ "Krackon","Krackon"],
  vanillite: [ "Krackon","Krackon"],
  vanillish: [ "DavidCitos","DavidCitos"],
  vanilluxe: [ "YuukiTwo","YuukiTwo"],
  deerling: [ "YuukiTwo","YuukiTwo"],
  sawsbuck: [ "YuukiTwo","YuukiTwo"],
  karrablast: [ "Jabubuu","Jabubuu"],
  escavalier: [ "Jabubuu","Jabubuu"],
  foongus: [ "JuniorJMx","JuniorJMx"],
  amoonguss: [ "XIGoroxlX","chunchumaru"],
  frillish: [ "Souen","Souen"],
  jellicent: [ "Souen","Souen"],
  joltik: [ "Mxxarc","Mxxarc"],
  galvantula: [ "Cypher","Cypher"],
  ferroseed: [ "DavidCitos","DavidCitos"],
  ferrothorn: [ "ToxicPlumber","ToxicPlumber"],
  klink: [ "IgnacioCZ","IgnacioCZ"],
  klang: [ "IgnacioCZ","IgnacioCZ"],
  klinklang: [ "IgnacioCZ","IgnacioCZ"],
  tynamo: [ "ritosenpai","ritosenpai"],
  eelektrik: [ "ritosenpai","ritosenpai"],
  eelektross: [ "ritosenpai","ritosenpai"],
  elgyem: [ "Salva","Salva"],
  beheeyem: [ "OreganoPVP","OreganoPVP"],
  litwick: [ "DavidCitos","iYerson"],
  lampent: [ "KnowJiYong","iYerson"],
  chandelure: [ "Moonlyze","iYerson"],
  axew: [ "Silvaryl","Silvaryl"],
  fraxure: [ "Krampus","Krampus"],
  haxorus: [ "UltimoMorador","Wildfredo"],
  cubchoo: [ "DavidCitos","INotAaron"],
  beartic: [ "ritosenpai","ritosenpai"],
  cryogonal: [ "aeamanh","aeamanh"],
  shelmet: [ "DavidCitos","DavidCitos"],
  accelgor: [ "DavidCitos","DavidCitos"],
  stunfisk: [ "Renz","Renz"],
  mienfoo: [ "Renz","Renz"],
  mienshao: [ "Akalii","Akalii"],
  druddigon: [ "AdrixJK","Pastruki"],
  golett: [ "JJean","JJean"],
  golurk: [ "JJean","JJean"],
  pawniard: [ "Seaba","INotAaron"],
  bisharp: [ "Seaba","INotAaron"],
  bouffalant: [ "Renz","Renz"],
  rufflet: [ "Krampus","chunchumaru"],
  braviary: [ "LauraSkylar","LauraSkylar"],
  vullaby: [ "Pancho","Pancho"],
  mandibuzz: [ "Pancho","Pancho"],
  heatmor: [ "Guabixd","Guabixd"],
  durant: [ "ToxicPlumber","ToxicPlumber"],
  deino: [ "ToxicPlumber","ToxicPlumber"],
  zweilous: [ "DavidCitos","DavidCitos"],
  hydreigon: [ "MrCartago","iYerson"],
  larvesta: [ "MasterFox","MasterFox"],
  volcarona: [ "MasterFox","MasterFox"],
};
 
const captured_unown = {
  "unown-p": ["vitro","vitro"],
  "unown-em": ["Lirio","Lirio"],
}

const captured_other = {
  /*"burmy-plant": ["KnowJiYong","KnowJiYong"],
  "wormadam-plant": ["KnowJiYong","KnowJiYong"],*/
  "shellos-east": ["Souen","Souen"],
  "gastrodon-west": ["Azathotx","Azathotx"],
  "gastrodon-east": ["Souen","Souen"],
  "deerling-summer": ["YuukiTwo","YuukiTwo"],
  "sawsbuck-autumn": ["YuukiTwo","YuukiTwo"],
  "basculin-red-striped": ["DavidCitos","DavidCitos"],
}

// Mejor Apostol
function getTop(capturedBy) {
  const counts = {};

  for (const name in capturedBy) {
      const trainer = capturedBy[name][1];
      counts[trainer] = (counts[trainer] || 0) + 1;
  }

  let maxCount = 0;
  let topTrainer = "";

  for (const trainer in counts) {
      if (counts[trainer] > maxCount) {
          maxCount = counts[trainer];
          topTrainer = trainer;
      }
  }

  return { trainer: topTrainer, count: maxCount };
}

const topData = getTop(capturedBy);