const generations = {
  "Gen 1": ["bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon", "charizard",
  "squirtle", "wartortle", "blastoise", "caterpie", "metapod", "butterfree",
  "weedle", "kakuna", "beedrill", "pidgey", "pidgeotto", "pidgeot", "rattata",
  "raticate", "spearow", "fearow", "ekans", "arbok", "pikachu", "raichu",
  "sandshrew", "sandslash", "nidoran-f", "nidorina", "nidoqueen", "nidoran-m",
  "nidorino", "nidoking", "clefairy", "clefable", "vulpix", "ninetales",
  "jigglypuff", "wigglytuff", "zubat", "golbat", "oddish", "gloom", "vileplume",
  "paras", "parasect", "venonat", "venomoth", "diglett", "dugtrio", "meowth",
  "persian", "psyduck", "golduck", "mankey", "primeape", "growlithe", "arcanine",
  "poliwag", "poliwhirl", "poliwrath", "abra", "kadabra", "alakazam", "machop",
  "machoke", "machamp", "bellsprout", "weepinbell", "victreebel", "tentacool",
  "tentacruel", "geodude", "graveler", "golem", "ponyta", "rapidash", "slowpoke",
  "slowbro", "magnemite", "magneton", "farfetchd", "doduo", "dodrio", "seel",
  "dewgong", "grimer", "muk", "shellder", "cloyster", "gastly", "haunter",
  "gengar", "onix", "drowzee", "hypno", "krabby", "kingler", "voltorb",
  "electrode", "exeggcute", "exeggutor", "cubone", "marowak", "hitmonlee",
  "hitmonchan", "lickitung", "koffing", "weezing", "rhyhorn", "rhydon",
  "chansey", "tangela", "kangaskhan", "horsea", "seadra", "goldeen", "seaking",
  "staryu", "starmie", "mr-mime", "scyther", "jynx", "electabuzz", "magmar",
  "pinsir", "tauros", "magikarp", "gyarados", "lapras", "ditto", "eevee",
  "vaporeon", "jolteon", "flareon", "porygon", "omanyte", "omastar", "kabuto",
  "kabutops", "aerodactyl", "snorlax", "articuno", "zapdos", "moltres",
  "dratini", "dragonair", "dragonite"],

  "Gen 2": ["chikorita", "bayleef", "meganium", "cyndaquil", "quilava", "typhlosion",
  "totodile", "croconaw", "feraligatr", "sentret", "furret", "hoothoot",
  "noctowl", "ledyba", "ledian", "spinarak", "ariados", "crobat", "chinchou",
  "lanturn", "pichu", "cleffa", "igglybuff", "togepi", "togetic", "natu",
  "xatu", "mareep", "flaaffy", "ampharos", "bellossom", "marill", "azumarill",
  "sudowoodo", "politoed", "hoppip", "skiploom", "jumpluff", "aipom", "sunkern",
  "sunflora", "yanma", "wooper", "quagsire", "espeon", "umbreon", "murkrow",
  "slowking", "misdreavus", "unown", "wobbuffet", "girafarig", "pineco",
  "forretress", "dunsparce", "gligar", "steelix", "snubbull", "granbull",
  "qwilfish", "scizor", "shuckle", "heracross", "sneasel", "teddiursa",
  "ursaring", "slugma", "magcargo", "swinub", "piloswine", "corsola",
  "remoraid", "octillery", "delibird", "mantine", "skarmory", "houndour",
  "houndoom", "kingdra", "phanpy", "donphan", "porygon2", "stantler",
  "smeargle", "tyrogue", "hitmontop", "smoochum", "elekid", "magby",
  "miltank", "blissey", "raikou", "entei", "suicune", "larvitar", "pupitar",
  "tyranitar"],

  "Gen 3": ["treecko", "grovyle", "sceptile", "torchic", "combusken", "blaziken",
  "mudkip", "marshtomp", "swampert", "poochyena", "mightyena", "zigzagoon",
  "linoone", "wurmple", "silcoon", "beautifly", "cascoon", "dustox", "lotad",
  "lombre", "ludicolo", "seedot", "nuzleaf", "shiftry", "taillow", "swellow",
  "wingull", "pelipper", "ralts", "kirlia", "gardevoir", "surskit",
  "masquerain", "shroomish", "breloom", "slakoth", "vigoroth", "slaking",
  "nincada", "ninjask", "shedinja", "whismur", "loudred", "exploud",
  "makuhita", "hariyama", "azurill", "nosepass", "skitty", "delcatty",
  "sableye", "mawile", "aron", "lairon", "aggron", "meditite", "medicham",
  "electrike", "manectric", "plusle", "minun", "volbeat", "illumise",
  "roselia", "gulpin", "swalot", "carvanha", "sharpedo", "wailmer",
  "wailord", "numel", "camerupt", "torkoal", "spoink", "grumpig",
  "spinda", "trapinch", "vibrava", "flygon", "cacnea", "cacturne",
  "swablu", "altaria", "zangoose", "seviper", "lunatone", "solrock",
  "barboach", "whiscash", "corphish", "crawdaunt", "baltoy", "claydol",
  "lileep", "cradily", "anorith", "armaldo", "feebas", "milotic",
  "castform", "kecleon", "shuppet", "banette", "duskull", "dusclops",
  "tropius", "chimecho", "absol", "wynaut", "snorunt", "glalie",
  "spheal", "sealeo", "walrein", "clamperl", "huntail", "gorebyss",
  "relicanth", "luvdisc", "bagon", "shelgon", "salamence",
  "beldum", "metang", "metagross","jirachi"],

  "Gen 4": [ "turtwig", "grotle", "torterra", "chimchar", "monferno", "infernape",
  "piplup", "prinplup", "empoleon", "starly", "staravia", "staraptor",
  "bidoof", "bibarel", "kricketot", "kricketune", "shinx", "luxio", "luxray",
  "budew", "roserade", "cranidos", "rampardos", "shieldon", "bastiodon",
  "burmy", "wormadam", "mothim", "combee", "vespiquen", "pachirisu",
  "buizel", "floatzel", "cherubi", "cherrim", "shellos", "gastrodon",
  "ambipom", "drifloon", "drifblim", "buneary", "lopunny", "mismagius",
  "honchkrow", "glameow", "purugly", "chingling", "stunky", "skuntank",
  "bronzor", "bronzong", "bonsly", "mime-jr", "happiny", "chatot",
  "spiritomb", "gible", "gabite", "garchomp", "munchlax", "riolu", "lucario",
  "hippopotas", "hippowdon", "skorupi", "drapion", "croagunk", "toxicroak",
  "carnivine", "finneon", "lumineon", "mantyke", "snover", "abomasnow",
  "weavile", "magnezone", "lickilicky", "rhyperior", "tangrowth",
  "electivire", "magmortar", "togekiss", "yanmega", "leafeon", "glaceon",
  "gliscor", "mamoswine", "porygon-z", "gallade", "probopass", "dusknoir",
  "froslass", "rotom","heatran","darkrai", "shaymin",],

  "Gen 5": ["snivy", "servine", "serperior", "tepig", "pignite", "emboar",
  "oshawott", "dewott", "samurott", "patrat", "watchog", "lillipup", "herdier",
  "stoutland", "purrloin", "liepard", "pansage", "simisage", "pansear", "simisear",
  "panpour", "simipour", "munna", "musharna", "pidove", "tranquill", "unfezant",
  "blitzle", "zebstrika", "roggenrola", "boldore", "gigalith", "woobat",
  "swoobat", "drilbur", "excadrill", "audino", "timburr", "gurdurr", "conkeldurr",
  "tympole", "palpitoad", "seismitoad", "throh", "sawk", "sewaddle", "swadloon",
  "leavanny", "venipede", "whirlipede", "scolipede", "cottonee", "whimsicott",
  "petilil", "lilligant", "basculin", "sandile", "krokorok", "krookodile",
  "darumaka", "darmanitan", "maractus", "dwebble", "crustle", "scraggy",
  "scrafty", "sigilyph", "yamask", "cofagrigus", "tirtouga", "carracosta",
  "archen", "archeops", "trubbish", "garbodor", "zorua", "zoroark", "minccino",
  "cinccino", "gothita", "gothorita", "gothitelle", "solosis", "duosion",
  "reuniclus", "ducklett", "swanna", "vanillite", "vanillish", "vanilluxe",
  "deerling", "sawsbuck", "emolga", "karrablast", "escavalier", "foongus",
  "amoonguss", "frillish", "jellicent", "alomomola", "joltik", "galvantula",
  "ferroseed", "ferrothorn", "klink", "klang", "klinklang", "tynamo",
  "eelektrik", "eelektross", "elgyem", "beheeyem", "litwick", "lampent",
  "chandelure", "axew", "fraxure", "haxorus", "cubchoo", "beartic", "cryogonal",
  "shelmet", "accelgor", "stunfisk", "mienfoo", "mienshao", "druddigon",
  "golett", "golurk", "pawniard", "bisharp", "bouffalant", "rufflet",
  "braviary", "vullaby", "mandibuzz", "heatmor", "durant", "deino",
  "zweilous", "hydreigon", "larvesta", "volcarona"],
};

const capturedBy = {
  bulbasaur: "Maicol",
  ivysaur: "Maicol",
  venusaur: "Maicol",
  charmander: "Tokyopp",
  charmeleon: "Tokyopp",
  charizard: "Tokyopp",
  caterpie: "Moonlyze",
  metapod: "YuukiTwo",
  butterfree: "LifeTown",
  weedle: "nyumichaelis",
  kakuna: "MangoOscuro",
  beedrill: "ISilverJr",
  pidgey: "Pancho",
  pidgeotto: "Pancho",
  pidgeot: "Pancho",
  rattata: "ToxicPlumber",
  raticate: "MangoOscuro",
  spearow: "AlexisBlu",
  fearow: "DavidCitos",
  ekans: "PierciLmL",
  arbok: "MonkeyCake",
  pikachu: "DavidCitos",
  raichu: "Krampus",
  sandshrew: "TheJesucristian",
  sandslash: "aeamanh",
  "nidoran-f":"ToxicPlumber",
  nidorina: "MonkeyCake",
  nidoqueen: "ToxicPlumber",
  "nidoran-m":"ToxicPlumber",
  nidorino: "Alicia",
  nidoking: "OreganoPVP",
  vulpix: "Renz",
  ninetales: "Renz",
  jigglypuff: "Moonlyze",
  wigglytuff: "Moonlyze",
  zubat: "TheJesucristian",
  golbat: "MixZeppeli",
  oddish: "FranCRLZ",
  gloom: "Palafo",
  vileplume: "Pancho",
  paras: "Alicia",
  parasect: "UltimoMorador",
  venonat: "Azathotx",
  venomoth: "Azathotx",
  diglett: "Azathotx",
  dugtrio: "Azathotx",
  meowth: "Palafo",
  persian: "UltimoMorador",
  psyduck: "MonkeyCake",
  golduck: "ritosenpai",
  mankey: "Krackon",
  primeape: "aeamanh",
  growlithe: "Pancho",
  arcanine: "Souen",
  poliwag: "DavidCitos",
  poliwhirl: "DavidCitos",
  poliwrath: "gamermanco",
  abra: "LifeTown",
  kadabra: "Maxii",
  alakazam: "ToxicPlumber",
  machop: "Palafo",
  machoke: "ToxicPlumber",
  machamp: "ToxicPlumber",
  bellsprout: "ElMiga",
  weepinbell: "Palafo",
  victreebel: "Palafo",
  tentacool: "ToxicPlumber",
  tentacruel: "ToxicPlumber",
  geodude: "ritosenpai",
  graveler: "DavidCitos",
  golem: "Pancho",
  ponyta: "Palafo",
  rapidash: "Renz",
  slowpoke: "XlDarcklX",
  slowbro: "cqmilo",
  magnemite: "DavidCitos",
  magneton: "aeamanh",
  farfetchd: "AdrixJK",
  doduo: "Krampus",
  dodrio: "Krackon",
  seel: "KnowJiYong",
  dewgong: "KnowJiYong",
  grimer: "DavidCitos",
  muk: "Snip",
  shellder: "JuniorJMx",
  cloyster: "XxsvrgioxX",
  gastly: "ToxicPlumber",
  haunter: "RIIW",
  gengar: "ToxicPlumber",
  onix: "DavidCitos",
  drowzee: "Palafo",
  hypno: "Palafo",
  krabby: "MasterFox",
  kingler: "Maxii",
  voltorb: "DavidCitos",
  electrode: "Salva",
  cubone: 'AlexisBlu', 
  marowak: 'ToxicPlumber', 
  lickitung: 'Pancho', 
  koffing: 'ToxicPlumber', 
  weezing: 'DavidCitos', 
  rhyhorn: 'YuukiTwo', 
  rhydon: 'DavidCitos', 
  chansey: 'Krackon', 
  tangela: 'Palafo', 
  horsea: 'Renz', 
  seadra: 'Renz', 
  goldeen: 'chunchumaru', 
  seaking: 'ToxicPlumber', 
  staryu: 'ToxicPlumber', 
  starmie: 'ToxicPlumber', 
  scyther: 'ritosenpai', 
  jynx: 'JuniorJMx', 
  electabuzz: 'DavidCitos', 
  magmar: 'DavidCitos', 
  pinsir: 'JJean', 
  tauros: 'KnowJiYong', 
  magikarp: 'Palafo', 
  gyarados: 'ToxicPlumber', 
  lapras: 'AshFifero', 
  ditto: 'Silvaryl', 
  eevee: 'Alicia', 
  vaporeon: 'Jabubuu', 
  jolteon: 'ritosenpai', 
  porygon: 'Alicia', 
  kabuto: 'chunchumaru', 
  kabutops: 'chunchumaru', 
  snorlax: 'XxsvrgioxX', 
  dratini: 'KilluaZoldyck', 
  dragonair: 'rebukittheveil', 
  dragonite: 'Souen', 
  cyndaquil: 'Mxxarc', 
  quilava: 'Mxxarc', 
  typhlosion: 'Mxxarc', 
  totodile: 'TheJesucristian', 
  croconaw: 'TheJesucristian', 
  feraligatr: 'TheJesucristian', 
  sentret: 'Pancho', 
  furret: 'chris', 
  hoothoot: 'Krackon', 
  noctowl: 'ToxicPlumber', 
  ledyba: 'Silvaryl', 
  ledian: 'Silvaryl', 
  spinarak: 'hectoralberto', 
  ariados: 'hectoralberto', 
  crobat: 'ToxicPlumber', 
  chinchou: 'Cypher', 
  lanturn: 'Akalii', 
  pichu: 'ToxicPlumber', 
  igglybuff: 'UltimoMorador', 
  natu: 'ToxicPlumber', 
  xatu: 'ToxicPlumber', 
  mareep: 'Silvaryl', 
  flaaffy: 'attomico', 
  ampharos: 'JerichoKenobi', 
  bellossom: 'Palafo', 
  marill: 'DavidCitos', 
  azumarill: 'MonkeyCake', 
  sudowoodo: 'Tyrantrum', 
  politoed: 'Domotwo', 
  hoppip: 'chris', 
  skiploom: 'chris', 
  jumpluff: 'Akalii',
  sunkern: "MarkosW",
  sunflora: "MarkosW",
  wooper: 'Renz', 
  quagsire: 'Renz', 
  espeon: 'Alicia', 
  umbreon: 'Jabubuu', 
  murkrow: 'WILDfredo', 
  slowking: 'Portapapel', 
  misdreavus: 'Renz', 
  unown: 'vitro', 
  wobbuffet: 'DavidCitos', 
  girafarig: 'Mikuuwu', 
  dunsparce: 'Iucifer', 
  gligar: 'DavidCitos', 
  steelix: 'nyumichaelis', 
  snubbull: 'UltimoMorador', 
  granbull: 'UltimoMorador', 
  scizor: 'ritosenpai', 
  heracross: 'OreganoPvP', 
  sneasel: 'DavidCitos', 
  teddiursa: 'MixZeppeli', 
  ursaring: 'DavidCitos', 
  slugma: 'chris', 
  magcargo: 'TheJesucristian', 
  swinub: 'AdrixJK', 
  piloswine: 'YuukiTwo', 
  corsola: 'MasterFox', 
  remoraid: 'Souen', 
  octillery: 'Souen', 
  delibird: 'Lirio',
  skarmory: 'sadending',
  mantine: 'OreganoPvP', 
  houndour: 'ritosenpai', 
  houndoom: 'ritosenpai', 
  kingdra: 'Renz', 
  phanpy: 'nyumichaelis', 
  donphan: 'Krackon', 
  porygon2: 'Alicia', 
  stantler: 'Moonlyze', 
  smeargle: 'ToxicPlumber',
  smoochum: 'UltimoMorador',
  magby: 'DiGoMo', 
  miltank: 'DavidCitos', 
  larvitar: 'ToxicPlumber', 
  pupitar: 'ToxicPlumber', 
  tyranitar: 'ToxicPlumber', 
  treecko: 'DavidCitos', 
  grovyle: 'MisakiUwUr', 
  sceptile: 'MisakiUwUr', 
  mudkip: 'ritosenpai', 
  marshtomp: 'ritosenpai',
  sewaddle: "emirfeNoPremium",
  swampert: 'ritosenpai', 
  poochyena: 'Akalii', 
  mightyena: 'MangoOscuro', 
  zigzagoon: 'Krackon', 
  linoone: 'ritosenpai', 
  wurmple: 'nyumichaelis', 
  silcoon: 'nyumichaelis', 
  beautifly: 'ToxicPlumber', 
  cascoon: 'nyumichaelis', 
  dustox: 'nyumichaelis', 
  lotad: 'Azathotx', 
  lombre: 'UltimoMorador', 
  ludicolo: 'MonkeyCake', 
  shiftry: 'AndresUY', 
  taillow: 'ToxicPlumber', 
  swellow: 'ToxicPlumber', 
  wingull: 'ToxicPlumber', 
  pelipper: 'Moonlyze', 
  ralts: 'Akalii',
  kirlia: 'IxGab', 
  gardevoir: 'DavidCitos', 
  surskit: 'Palafo', 
  masquerain: 'alexisxoa', 
  shroomish: 'KnowJiYong', 
  breloom: 'KnowJiYong',
  slakoth: 'Estorbiito',
  vigoroth: 'Estorbiito',
  slaking: 'Estorbiito',
  nincada: 'ritosenpai', 
  whismur: 'MixZeppeli', 
  loudred: 'MixZeppeli', 
  exploud: 'Mdbzp',
  makuhita: 'UltimoMorador',
  hariyama: 'DavidCitos', 
  azurill: 'Jabubuu', 
  skitty: 'Mikuuwu', 
  delcatty: 'Mikuuwu', 
  sableye: 'ritosenpai', 
  mawile: 'ritosenpai', 
  aron: 'ToxicPlumber', 
  lairon: 'ToxicPlumber', 
  aggron: 'ToxicPlumber', 
  meditite: 'Renz', 
  medicham: 'ToxicPlumber', 
  electrike: 'DavidCitos', 
  manectric: 'ToxicPlumber', 
  volbeat: 'ritosenpai', 
  roselia: 'DavidCitos', 
  gulpin: 'ToxicPlumber', 
  swalot: 'ToxicPlumber', 
  carvanha: 'JuniorJMx', 
  sharpedo: 'Akalii', 
  numel: 'Alicia', 
  camerupt: 'KnowJiYong', 
  torkoal: 'Moonlyze', 
  spoink: 'Palafo', 
  spinda: 'Krackon', 
  trapinch: 'DavidCitos', 
  vibrava: 'TheJesucristian', 
  flygon: 'ritosenpai', 
  cacnea: 'JUANKAXGARCIA',
  cacturne: 'jerryeric', 
  swablu: 'DavidCitos', 
  altaria: 'Krackon', 
  zangoose: 'Ashy', 
  seviper: 'ritosenpai', 
  lunatone: 'ToxicPlumber', 
  solrock: 'DavidCitos', 
  barboach: 'Palafo', 
  corphish: 'ToxicPlumber', 
  crawdaunt: 'YuukiTwo', 
  baltoy: 'ToxicPlumber', 
  claydol: 'KnowJiYong', 
  feebas: 'MrCartago', 
  milotic: 'MrCartago', 
  kecleon: 'Azathotx', 
  shuppet: 'KnowJiYong', 
  banette: 'DavidCitos', 
  duskull: 'DavidCitos', 
  dusclops: 'Maxii', 
  absol: 'MixZeppeli', 
  wynaut: 'ritosenpai', 
  snorunt: 'Akalii', 
  glalie: 'KnowJiYong', 
  spheal: 'IagoMLS', 
  sealeo: 'DavidCitos', 
  walrein: 'xDerx', 
  clamperl: 'Iucifer', 
  huntail: 'Iucifer', 
  gorebyss: 'Jabubuu', 
  luvdisc: 'Mdbzp', 
  bagon: 'chunchumaru', 
  salamence: 'chunchumaru', 
  beldum: 'ToxicPlumber', 
  metang: 'ToxicPlumber', 
  metagross: 'ToxicPlumber', 
  turtwig: 'Gusteiv', 
  grotle: 'Gusteiv', 
  torterra: 'Gusteiv', 
  starly: 'ElMiga', 
  staravia: 'chunchumaru', 
  staraptor: 'ElMiga', 
  bidoof: 'XxsvrgioxX', 
  bibarel: 'Moonlyze', 
  kricketune: 'JuniorJMx', 
  shinx: 'Akalii', 
  luxio: 'Cece', 
  luxray: 'Krackon', 
  budew: 'Pancho', 
  roserade: 'DavidCitos', 
  shieldon: 'chunchumaru', 
  bastiodon: 'chunchumaru', 
  burmy: 'KnowJiYong', 
  wormadam: 'KnowJiYong', 
  mothim: 'KnowJiYong', 
  combee: 'ToxicPlumber', 
  pachirisu: 'Akalii', 
  buizel: 'MangoOscuro', 
  floatzel: 'Gusteiv', 
  shellos: 'Souen', 
  gastrodon: 'Azathotx', 
  drifblim: 'ritosenpai', 
  buneary: 'DavidCitos', 
  lopunny: 'DavidCitos', 
  mismagius: 'Renz', 
  honchkrow: 'Lirio', 
  purugly: 'Mittoh', 
  stunky: 'ritosenpai', 
  skuntank: 'JuniorJMx', 
  bronzor: 'Akalii', 
  bronzong: 'DavidCitos', 
  "mime-jr": 'Seaba', 
  chatot: 'Veilia', 
  gible: 'Akalii', 
  gabite: 'Gusteiv', 
  garchomp: 'Lirio', 
  munchlax: 'Gamermanco',
  riolu: "Pancho",
  lucario: "Pancho",
  hippopotas: "aeamanh",
  hippowdon: "aeamanh",
  skorupi: 'YuukiTwo', 
  drapion: 'YuukiTwo', 
  finneon: 'KnowJiYong', 
  lumineon: 'KnowJiYong', 
  mantyke: 'UltimoMorador', 
  snover: 'DavidCitos', 
  abomasnow: 'KnowJiYong', 
  weavile: 'DavidCitos', 
  magnezone: 'DavidCitos', 
  lickilicky: 'Pancho', 
  rhyperior: 'YuukiTwo', 
  tangrowth: 'Pancho', 
  electivire: 'iYerson',
  magmortar: 'DiGoMo',
  gliscor: 'TheJesucristian', 
  mamoswine: 'TheJesucristian', 
  "porygon-z": 'Alicia',
  gallade: 'Mexb', 
  probopass: 'JuniorJMx', 
  dusknoir: 'Seaba', 
  froslass: 'Lirio', 
  rotom: 'Alicia', 
  snivy: 'Krackon', 
  servine: 'Krackon', 
  serperior: 'Krackon', 
  tepig: 'Xiopand', 
  pignite: 'Xiopand', 
  emboar: 'Xiopand',
  patrat: 'UltimoMorador',
  watchog: 'Krackon', 
  herdier: 'ritosenpai', 
  purrloin: 'Pancho', 
  liepard: 'WILDfredo', 
  pansage: 'aeamanh', 
  simisage: 'Muertexx', 
  pansear: 'Pancho', 
  simisear: 'Pancho', 
  munna: 'Jabubuu', 
  pidove: 'ritosenpai', 
  tranquill: 'DavidCitos', 
  unfezant: 'UltimoMorador', 
  blitzle: 'Guabixd', 
  zebstrika: 'Guabixd', 
  roggenrola: 'UltimoMorador', 
  boldore: 'Salva', 
  gigalith: 'ToxicPlumber', 
  woobat: 'DavidCitos', 
  swoobat: 'Iucifer', 
  timburr: 'Krackon', 
  gurdurr: 'DavidCitos', 
  conkeldurr: 'Lirio', 
  tympole: 'pimientadaza', 
  palpitoad: 'DavidCitos', 
  seismitoad: 'pimientadaza', 
  sawk: 'UltimoMorador', 
  swadloon: 'UltimoMorador', 
  leavanny: 'UltimoMorador', 
  venipede: 'YuukiTwo', 
  whirlipede: 'ToxicPlumber', 
  scolipede: 'chris', 
  cottonee: 'Akalii', 
  whimsicott: 'TheJesucristian', 
  petilil: 'Spirati', 
  lilligant: 'JuniorJMx', 
  basculin: 'DavidCitos', 
  sandile: 'Cypher', 
  krokorok: 'Snip', 
  krookodile: 'ToxicPlumber', 
  darumaka: 'ritosenpai', 
  darmanitan: 'Krampus', 
  maractus: 'ToxicPlumber', 
  dwebble: 'MasterFox', 
  crustle: 'MasterFox', 
  scraggy: 'Mittoh', 
  scrafty: 'Silvaryl', 
  sigilyph: 'LauraSkylar',
  yamask: 'JUANKAXGARCIA',
  cofagrigus: 'DavidCitos', 
  tirtouga: 'AlexisBlu', 
  trubbish: 'JuniorJMx', 
  garbodor: 'JuniorJMx', 
  zorua: 'nyumichaelis', 
  zoroark: 'chunchumaru', 
  minccino: 'KnowJiYong', 
  cinccino: 'KnowJiYong', 
  gothita: 'AdrixJK', 
  gothorita: 'MasterFox', 
  gothitelle: 'MasterFox', 
  duosion: 'Renz', 
  reuniclus: 'Krackon', 
  vanillite: 'Krackon', 
  vanillish: 'DavidCitos', 
  vanilluxe: 'YuukiTwo', 
  deerling: 'YuukiTwo', 
  sawsbuck: 'YuukiTwo', 
  karrablast: 'Jabubuu', 
  escavalier: 'Jabubuu', 
  foongus: 'JuniorJMx', 
  amoonguss: 'UltimoMorador', 
  frillish: 'GhostGD', 
  jellicent: 'GhostGD', 
  joltik: 'Mxxarc', 
  galvantula: 'Cypher', 
  ferroseed: 'DavidCitos', 
  ferrothorn: 'ToxicPlumber', 
  klink: 'IgnacioCZ',
  klang: "IgnacioCZ",
  klinklang: "IgnacioCZ",
  tynamo: 'ritosenpai', 
  eelektrik: 'ritosenpai', 
  eelektross: 'ritosenpai', 
  elgyem: 'Salva', 
  beheeyem: 'OreganoPvP', 
  litwick: 'DavidCitos', 
  lampent: 'KnowJiYong', 
  chandelure: 'Moonlyze', 
  axew: 'Silvaryl', 
  fraxure: 'Krampus', 
  haxorus: 'UltimoMorador', 
  cubchoo: 'DavidCitos', 
  beartic: 'ritosenpai', 
  cryogonal: 'aeamanh', 
  shelmet: 'DavidCitos', 
  accelgor: 'DavidCitos', 
  stunfisk: 'Renz', 
  mienfoo: 'Renz', 
  mienshao: 'Akalii', 
  druddigon: 'AdrixJK', 
  golett: 'JJean', 
  golurk: 'JJean', 
  pawniard: 'Seaba', 
  bisharp: 'Seaba', 
  bouffalant: 'Renz', 
  rufflet: 'Krampus', 
  braviary: 'LauraSkylar', 
  vullaby: 'chunchumaru', 
  heatmor: 'DivineMeditation', 
  durant: 'ToxicPlumber', 
  deino: 'ToxicPlumber', 
  zweilous: 'DavidCitos', 
  hydreigon: 'MrCartago', 
  larvesta: 'MasterFox', 
  volcarona: 'MasterFox', 
};
 
// Mejor Apostol
function getTop(capturedBy) {
  const counts = {};

  for (const name in capturedBy) {
      const trainer = capturedBy[name];
      counts[trainer] = (counts[trainer] || 0) + 1;
  }

  let maxCount = 0;
  let topTrainer = "";

  for (const trainer in counts) {
      if (counts[trainer] > maxCount) {
          maxCount = counts[trainer];
          topTrainer = trainer;
      }
  }

  return { trainer: topTrainer, count: maxCount };
}

const topData = getTop(capturedBy);