const generations = {
  "Gen 1": ["bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon", "charizard",
  "squirtle", "wartortle", "blastoise", "caterpie", "metapod", "butterfree",
  "weedle", "kakuna", "beedrill", "pidgey", "pidgeotto", "pidgeot", "rattata",
  "raticate", "spearow", "fearow", "ekans", "arbok", "pikachu", "raichu",
  "sandshrew", "sandslash", "nidoran-f", "nidorina", "nidoqueen", "nidoran-m",
  "nidorino", "nidoking", "clefairy", "clefable", "vulpix", "ninetales",
  "jigglypuff", "wigglytuff", "zubat", "golbat", "oddish", "gloom", "vileplume",
  "paras", "parasect", "venonat", "venomoth", "diglett", "dugtrio", "meowth",
  "persian", "psyduck", "golduck", "mankey", "primeape", "growlithe", "arcanine",
  "poliwag", "poliwhirl", "poliwrath", "abra", "kadabra", "alakazam", "machop",
  "machoke", "machamp", "bellsprout", "weepinbell", "victreebel", "tentacool",
  "tentacruel", "geodude", "graveler", "golem", "ponyta", "rapidash", "slowpoke",
  "slowbro", "magnemite", "magneton", "farfetchd", "doduo", "dodrio", "seel",
  "dewgong", "grimer", "muk", "shellder", "cloyster", "gastly", "haunter",
  "gengar", "onix", "drowzee", "hypno", "krabby", "kingler", "voltorb",
  "electrode", "exeggcute", "exeggutor", "cubone", "marowak", "hitmonlee",
  "hitmonchan", "lickitung", "koffing", "weezing", "rhyhorn", "rhydon",
  "chansey", "tangela", "kangaskhan", "horsea", "seadra", "goldeen", "seaking",
  "staryu", "starmie", "mr-mime", "scyther", "jynx", "electabuzz", "magmar",
  "pinsir", "tauros", "magikarp", "gyarados", "lapras", "ditto", "eevee",
  "vaporeon", "jolteon", "flareon", "porygon", "omanyte", "omastar", "kabuto",
  "kabutops", "aerodactyl", "snorlax", "articuno", "zapdos", "moltres",
  "dratini", "dragonair", "dragonite", "mewtwo"],

  "Gen 2": ["chikorita", "bayleef", "meganium", "cyndaquil", "quilava", "typhlosion",
  "totodile", "croconaw", "feraligatr", "sentret", "furret", "hoothoot",
  "noctowl", "ledyba", "ledian", "spinarak", "ariados", "crobat", "chinchou",
  "lanturn", "pichu", "cleffa", "igglybuff", "togepi", "togetic", "natu",
  "xatu", "mareep", "flaaffy", "ampharos", "bellossom", "marill", "azumarill",
  "sudowoodo", "politoed", "hoppip", "skiploom", "jumpluff", "aipom", "sunkern",
  "sunflora", "yanma", "wooper", "quagsire", "espeon", "umbreon", "murkrow",
  "slowking", "misdreavus", "unown", "wobbuffet", "girafarig", "pineco",
  "forretress", "dunsparce", "gligar", "steelix", "snubbull", "granbull",
  "qwilfish", "scizor", "shuckle", "heracross", "sneasel", "teddiursa",
  "ursaring", "slugma", "magcargo", "swinub", "piloswine", "corsola",
  "remoraid", "octillery", "delibird", "mantine", "skarmory", "houndour",
  "houndoom", "kingdra", "phanpy", "donphan", "porygon2", "stantler",
  "smeargle", "tyrogue", "hitmontop", "smoochum", "elekid", "magby",
  "miltank", "blissey", "raikou", "entei", "suicune", "larvitar", "pupitar",
  "tyranitar", "lugia"],

  "Gen 3": ["treecko", "grovyle", "sceptile", "torchic", "combusken", "blaziken",
  "mudkip", "marshtomp", "swampert", "poochyena", "mightyena", "zigzagoon",
  "linoone", "wurmple", "silcoon", "beautifly", "cascoon", "dustox", "lotad",
  "lombre", "ludicolo", "seedot", "nuzleaf", "shiftry", "taillow", "swellow",
  "wingull", "pelipper", "ralts", "kirlia", "gardevoir", "surskit",
  "masquerain", "shroomish", "breloom", "slakoth", "vigoroth", "slaking",
  "nincada", "ninjask", "shedinja", "whismur", "loudred", "exploud",
  "makuhita", "hariyama", "azurill", "nosepass", "skitty", "delcatty",
  "sableye", "mawile", "aron", "lairon", "aggron", "meditite", "medicham",
  "electrike", "manectric", "plusle", "minun", "volbeat", "illumise",
  "roselia", "gulpin", "swalot", "carvanha", "sharpedo", "wailmer",
  "wailord", "numel", "camerupt", "torkoal", "spoink", "grumpig",
  "spinda", "trapinch", "vibrava", "flygon", "cacnea", "cacturne",
  "swablu", "altaria", "zangoose", "seviper", "lunatone", "solrock",
  "barboach", "whiscash", "corphish", "crawdaunt", "baltoy", "claydol",
  "lileep", "cradily", "anorith", "armaldo", "feebas", "milotic",
  "castform", "kecleon", "shuppet", "banette", "duskull", "dusclops",
  "tropius", "chimecho", "absol", "wynaut", "snorunt", "glalie",
  "spheal", "sealeo", "walrein", "clamperl", "huntail", "gorebyss",
  "relicanth", "luvdisc", "bagon", "shelgon", "salamence",
  "beldum", "metang", "metagross","rayquaza", "jirachi"],

  "Gen 4": [ "turtwig", "grotle", "torterra", "chimchar", "monferno", "infernape",
  "piplup", "prinplup", "empoleon", "starly", "staravia", "staraptor",
  "bidoof", "bibarel", "kricketot", "kricketune", "shinx", "luxio", "luxray",
  "budew", "roserade", "cranidos", "rampardos", "shieldon", "bastiodon",
  "burmy", "wormadam", "mothim", "combee", "vespiquen", "pachirisu",
  "buizel", "floatzel", "cherubi", "cherrim", "shellos", "gastrodon",
  "ambipom", "drifloon", "drifblim", "buneary", "lopunny", "mismagius",
  "honchkrow", "glameow", "purugly", "chingling", "stunky", "skuntank",
  "bronzor", "bronzong", "bonsly", "mime-jr", "happiny", "chatot",
  "spiritomb", "gible", "gabite", "garchomp", "munchlax", "riolu", "lucario",
  "hippopotas", "hippowdon", "skorupi", "drapion", "croagunk", "toxicroak",
  "carnivine", "finneon", "lumineon", "mantyke", "snover", "abomasnow",
  "weavile", "magnezone", "lickilicky", "rhyperior", "tangrowth",
  "electivire", "magmortar", "togekiss", "yanmega", "leafeon", "glaceon",
  "gliscor", "mamoswine", "porygon-z", "gallade", "probopass", "dusknoir",
  "froslass", "rotom","heatran","darkrai", "shaymin", "arceus",],

  "Gen 5": ["snivy", "servine", "serperior", "tepig", "pignite", "emboar",
  "oshawott", "dewott", "samurott", "patrat", "watchog", "lillipup", "herdier",
  "stoutland", "purrloin", "liepard", "pansage", "simisage", "pansear", "simisear",
  "panpour", "simipour", "munna", "musharna", "pidove", "tranquill", "unfezant",
  "blitzle", "zebstrika", "roggenrola", "boldore", "gigalith", "woobat",
  "swoobat", "drilbur", "excadrill", "audino", "timburr", "gurdurr", "conkeldurr",
  "tympole", "palpitoad", "seismitoad", "throh", "sawk", "sewaddle", "swadloon",
  "leavanny", "venipede", "whirlipede", "scolipede", "cottonee", "whimsicott",
  "petilil", "lilligant", "basculin", "sandile", "krokorok", "krookodile",
  "darumaka", "darmanitan", "maractus", "dwebble", "crustle", "scraggy",
  "scrafty", "sigilyph", "yamask", "cofagrigus", "tirtouga", "carracosta",
  "archen", "archeops", "trubbish", "garbodor", "zorua", "zoroark", "minccino",
  "cinccino", "gothita", "gothorita", "gothitelle", "solosis", "duosion",
  "reuniclus", "ducklett", "swanna", "vanillite", "vanillish", "vanilluxe",
  "deerling", "sawsbuck", "emolga", "karrablast", "escavalier", "foongus",
  "amoonguss", "frillish", "jellicent", "alomomola", "joltik", "galvantula",
  "ferroseed", "ferrothorn", "klink", "klang", "klinklang", "tynamo",
  "eelektrik", "eelektross", "elgyem", "beheeyem", "litwick", "lampent",
  "chandelure", "axew", "fraxure", "haxorus", "cubchoo", "beartic", "cryogonal",
  "shelmet", "accelgor", "stunfisk", "mienfoo", "mienshao", "druddigon",
  "golett", "golurk", "pawniard", "bisharp", "bouffalant", "rufflet",
  "braviary", "vullaby", "mandibuzz", "heatmor", "durant", "deino",
  "zweilous", "hydreigon", "larvesta", "volcarona", "keldeo"],
};

const capturedBy = {
  bulbasaur: "DrMaicol",
  ivysaur: "DrMaicol",
  venusaur: "DrMaicol",
  charmander: "Tokyopp",
  charmeleon: "Tokyopp",
  charizard: "Tokyopp",
  caterpie: "Moonlyze",
  metapod: "YuukiTwo",
  butterfree: "LifeTown",
  weedle: "nyumischaleis",
  kakuna: "MangoOscuro",
  beedrill: "ISilverJr",
  pidgey: "Panchimio",
  pidgeotto: "Panchimio",
  pidgeot: "Panchimio",
  rattata: "ToxicPlumber",
  raticate: "MangoOscuro",
  spearow: "AlexisBlu",
  fearow: "DavidCitos",
  ekans: "PierciLmL",
  arbok: "MonkeyCake",
  pikachu: "DavidCitos",
  raichu: "XIPANDAIX",
  sandshrew: "TheJesucristian",
  sandslash: "aeamanh",
  "nidoran-f":"ToxicPlumber",
  nidorina: "MonkeyCake",
  nidoqueen: "ToxicPlumber",
  "nidoran-m":"ToxicPlumber",
  nidorino: "Mawilice",
  nidoking: "OreganoPVP",
  vulpix: "lRenzz",
  ninetales: "lRenzz",
  jigglypuff: "Moonlyze",
  wigglytuff: "Moonlyze",
  zubat: "TheJesucristian",
  golbat: "MixZeppeli",
  oddish: "FranCRLZ",
  gloom: "Palafo",
  vileplume: "Panchimio",
  paras: "Mawilice",
  parasect: "UltimoMorador",
  venonat: "Azathotx",
  venomoth: "Azathotx",
  diglett: "Azathotx",
  dugtrio: "Azathotx",
  meowth: "Palafo",
  persian: "BlueKahil",
  psyduck: "MonkeyCake",
  golduck: "ritosenpai",
  mankey: "Krackon",
  primeape: "aeamanh",
  growlithe: "Panchimio",
  arcanine: "gamermanco",
  poliwag: "DavidCitos",
  poliwhirl: "DavidCitos",
  poliwrath: "gamermanco",
  abra: "LifeTown",
  kadabra: "TaqueritoBonito",
  alakazam: "ToxicPlumber",
  machop: "Palafo",
  machoke: "ToxicPlumber",
  machamp: "ToxicPlumber",
  bellsprout: "ElMiga",
  weepinbell: "Palafo",
  victreebel: "Palafo",
  tentacool: "ToxicPlumber",
  tentacruel: "ToxicPlumber",
  geodude: "ritosenpai",
  graveler: "DavidCitos",
  golem: "Panchimio",
  ponyta: "Palafo",
  rapidash: "lRenzz",
  slowpoke: "XlDarcklX",
  slowbro: "cqmilo",
  magnemite: "DavidCitos",
  magneton: "aeamanh",
  farfetchd: "AdrixJK",
  doduo: "XIPANDAIX",
  dodrio: "Krackon",
  seel: "KnowJiYong",
  dewgong: "KnowJiYong",
  grimer: "DavidCitos",
  muk: "SniperioYt",
  shellder: "JuniorJMx",
  cloyster: "XxsvrgioxX",
  gastly: "ToxicPlumber",
  haunter: "RIIW",
  gengar: "ToxicPlumber",
  onix: "DavidCitos",
  drowzee: "Palafo",
  hypno: "Palafo",
  krabby: "ElMasterFox",
  kingler: "Taqueritobonito",
  voltorb: "DavidCitos",
  electrode: "salvadormc",
  cubone: 'AlexisBlu', 
  marowak: 'ToxicPlumber', 
  lickitung: 'Panchimio', 
  koffing: 'ToxicPlumber', 
  weezing: 'DavidCitos', 
  rhyhorn: 'YuukiTwo', 
  rhydon: 'DavidCitos', 
  chansey: 'Krackon', 
  tangela: 'Palafo', 
  horsea: 'lRenzz', 
  seadra: 'lRenzz', 
  goldeen: 'chunchumaru', 
  seaking: 'ToxicPlumber', 
  staryu: 'ToxicPlumber', 
  starmie: 'ToxicPlumber', 
  scyther: 'ritosenpai', 
  jynx: 'JuniorJMx', 
  electabuzz: 'DavidCitos', 
  magmar: 'DavidCitos', 
  pinsir: 'JJeam', 
  tauros: 'KnowJiYong', 
  magikarp: 'Palafo', 
  gyarados: 'ToxicPlumber', 
  lapras: 'AshFifero', 
  ditto: 'Silvaryl', 
  eevee: 'Mawilice', 
  vaporeon: 'Jabubuu', 
  jolteon: 'ritosenpai', 
  porygon: 'Mawilice', 
  kabuto: 'chunchumaru', 
  kabutops: 'chunchumaru', 
  snorlax: 'XxsvrgioxX', 
  dratini: 'SoulOfPhoenix', 
  dragonair: 'Rebukittheveil', 
  dragonite: 'Souenx', 
  cyndaquil: 'Usuario', 
  quilava: 'Usuario', 
  typhlosion: 'Usuario', 
  totodile: 'Usuario', 
  croconaw: 'Usuario', 
  feraligatr: 'Usuario', 
  sentret: 'Usuario', 
  furret: 'Usuario', 
  hoothoot: 'Usuario', 
  noctowl: 'Usuario', 
  ledyba: 'Usuario', 
  ledian: 'Usuario', 
  spinarak: 'Usuario', 
  ariados: 'Usuario', 
  crobat: 'Usuario', 
  chinchou: 'Usuario', 
  lanturn: 'Usuario', 
  pichu: 'Usuario', 
  igglybuff: 'Usuario', 
  natu: 'Usuario', 
  xatu: 'Usuario', 
  mareep: 'Usuario', 
  flaaffy: 'Usuario', 
  ampharos: 'Usuario', 
  bellossom: 'Usuario', 
  marill: 'Usuario', 
  azumarill: 'Usuario', 
  sudowoodo: 'Usuario', 
  politoed: 'Usuario', 
  hoppip: 'Usuario', 
  skiploom: 'Usuario', 
  jumpluff: 'Usuario',
  sunkern: "MarkosW",
  sunflora: "MarkosW",
  wooper: 'Usuario', 
  quagsire: 'Usuario', 
  espeon: 'Usuario', 
  umbreon: 'Usuario', 
  murkrow: 'Usuario', 
  slowking: 'Usuario', 
  misdreavus: 'Usuario', 
  unown: 'Usuario', 
  wobbuffet: 'Usuario', 
  girafarig: 'Usuario', 
  dunsparce: 'Usuario', 
  gligar: 'Usuario', 
  steelix: 'Usuario', 
  snubbull: 'Usuario', 
  granbull: 'Usuario', 
  scizor: 'Usuario', 
  heracross: 'Usuario', 
  sneasel: 'Usuario', 
  teddiursa: 'Usuario', 
  ursaring: 'Usuario', 
  slugma: 'Usuario', 
  magcargo: 'Usuario', 
  swinub: 'Usuario', 
  piloswine: 'Usuario', 
  corsola: 'Usuario', 
  remoraid: 'Usuario', 
  octillery: 'Usuario', 
  delibird: 'Usuario', 
  mantine: 'Usuario', 
  houndour: 'Usuario', 
  houndoom: 'Usuario', 
  kingdra: 'Usuario', 
  phanpy: 'Usuario', 
  donphan: 'Usuario', 
  porygon2: 'Usuario', 
  stantler: 'Usuario', 
  smeargle: 'Usuario', 
  magby: 'Usuario', 
  miltank: 'Usuario', 
  larvitar: 'Usuario', 
  pupitar: 'Usuario', 
  tyranitar: 'Usuario', 
  treecko: 'Usuario', 
  grovyle: 'Usuario', 
  sceptile: 'Usuario', 
  mudkip: 'Usuario', 
  marshtomp: 'Usuario', 
  swampert: 'Usuario', 
  poochyena: 'Usuario', 
  mightyena: 'Usuario', 
  zigzagoon: 'Usuario', 
  linoone: 'Usuario', 
  wurmple: 'Usuario', 
  silcoon: 'Usuario', 
  beautifly: 'Usuario', 
  cascoon: 'Usuario', 
  dustox: 'Usuario', 
  lotad: 'Usuario', 
  lombre: 'Usuario', 
  ludicolo: 'Usuario', 
  shiftry: 'Usuario', 
  taillow: 'Usuario', 
  swellow: 'Usuario', 
  wingull: 'Usuario', 
  pelipper: 'Usuario', 
  ralts: 'Usuario', 
  kirlia: 'Usuario', 
  gardevoir: 'Usuario', 
  surskit: 'Usuario', 
  masquerain: 'Usuario', 
  shroomish: 'Usuario', 
  breloom: 'Usuario', 
  nincada: 'Usuario', 
  whismur: 'Usuario', 
  loudred: 'Usuario', 
  exploud: 'Usuario', 
  hariyama: 'Usuario', 
  azurill: 'Usuario', 
  skitty: 'Usuario', 
  delcatty: 'Usuario', 
  sableye: 'Usuario', 
  mawile: 'Usuario', 
  aron: 'Usuario', 
  lairon: 'Usuario', 
  aggron: 'Usuario', 
  meditite: 'Usuario', 
  medicham: 'Usuario', 
  electrike: 'Usuario', 
  manectric: 'Usuario', 
  volbeat: 'Usuario', 
  roselia: 'Usuario', 
  gulpin: 'Usuario', 
  swalot: 'Usuario', 
  carvanha: 'Usuario', 
  sharpedo: 'Usuario', 
  numel: 'Usuario', 
  camerupt: 'Usuario', 
  torkoal: 'Usuario', 
  spoink: 'Usuario', 
  spinda: 'Usuario', 
  trapinch: 'Usuario', 
  vibrava: 'Usuario', 
  flygon: 'Usuario', 
  cacnea: 'Usuario', 
  cacturne: 'Usuario', 
  swablu: 'Usuario', 
  altaria: 'Usuario', 
  zangoose: 'Usuario', 
  seviper: 'Usuario', 
  lunatone: 'Usuario', 
  solrock: 'Usuario', 
  barboach: 'Usuario', 
  corphish: 'Usuario', 
  crawdaunt: 'Usuario', 
  baltoy: 'Usuario', 
  claydol: 'Usuario', 
  feebas: 'Usuario', 
  milotic: 'Usuario', 
  kecleon: 'Usuario', 
  shuppet: 'Usuario', 
  banette: 'Usuario', 
  duskull: 'Usuario', 
  dusclops: 'Usuario', 
  absol: 'Usuario', 
  wynaut: 'Usuario', 
  snorunt: 'Usuario', 
  glalie: 'Usuario', 
  spheal: 'Usuario', 
  sealeo: 'Usuario', 
  walrein: 'Usuario', 
  clamperl: 'Usuario', 
  huntail: 'Usuario', 
  gorebyss: 'Usuario', 
  luvdisc: 'Usuario', 
  bagon: 'Usuario', 
  salamence: 'Usuario', 
  beldum: 'Usuario', 
  metang: 'Usuario', 
  metagross: 'Usuario', 
  turtwig: 'Usuario', 
  grotle: 'Usuario', 
  torterra: 'Usuario', 
  starly: 'Usuario', 
  staravia: 'Usuario', 
  staraptor: 'Usuario', 
  bidoof: 'Usuario', 
  bibarel: 'Usuario', 
  kricketune: 'Usuario', 
  shinx: 'Usuario', 
  luxio: 'Usuario', 
  luxray: 'Usuario', 
  budew: 'Usuario', 
  roserade: 'Usuario', 
  shieldon: 'Usuario', 
  bastiodon: 'Usuario', 
  burmy: 'Usuario', 
  wormadam: 'Usuario', 
  mothim: 'Usuario', 
  combee: 'Usuario', 
  pachirisu: 'Usuario', 
  buizel: 'Usuario', 
  floatzel: 'Usuario', 
  shellos: 'Usuario', 
  gastrodon: 'Usuario', 
  drifblim: 'Usuario', 
  buneary: 'Usuario', 
  lopunny: 'Usuario', 
  mismagius: 'Usuario', 
  honchkrow: 'Usuario', 
  purugly: 'Usuario', 
  stunky: 'Usuario', 
  skuntank: 'Usuario', 
  bronzor: 'Usuario', 
  bronzong: 'Usuario', 
  "mime-jr": 'Usuario', 
  chatot: 'Usuario', 
  gible: 'Usuario', 
  gabite: 'Usuario', 
  garchomp: 'Usuario', 
  munchlax: 'Usuario',
  riolu: "Panchimio",
  lucario: "Panchimio",
  skorupi: 'Usuario', 
  drapion: 'Usuario', 
  finneon: 'Usuario', 
  lumineon: 'Usuario', 
  mantyke: 'Usuario', 
  snover: 'Usuario', 
  abomasnow: 'Usuario', 
  weavile: 'Usuario', 
  magnezone: 'Usuario', 
  lickilicky: 'Usuario', 
  rhyperior: 'Usuario', 
  tangrowth: 'Usuario', 
  electivire: 'Usuario', 
  gliscor: 'Usuario', 
  mamoswine: 'Usuario', 
  "porygon-z": 'Usuario', 
  probopass: 'Usuario', 
  dusknoir: 'Usuario', 
  froslass: 'Usuario', 
  rotom: 'Usuario', 
  snivy: 'Usuario', 
  servine: 'Usuario', 
  serperior: 'Usuario', 
  tepig: 'Usuario', 
  pignite: 'Usuario', 
  emboar: 'Usuario', 
  watchog: 'Usuario', 
  herdier: 'Usuario', 
  purrloin: 'Usuario', 
  liepard: 'Usuario', 
  pansage: 'Usuario', 
  simisage: 'Usuario', 
  pansear: 'Usuario', 
  simisear: 'Usuario', 
  munna: 'Usuario', 
  pidove: 'Usuario', 
  tranquill: 'Usuario', 
  unfezant: 'Usuario', 
  blitzle: 'Usuario', 
  zebstrika: 'Usuario', 
  roggenrola: 'Usuario', 
  boldore: 'Usuario', 
  gigalith: 'Usuario', 
  woobat: 'Usuario', 
  swoobat: 'Usuario', 
  timburr: 'Usuario', 
  gurdurr: 'Usuario', 
  conkeldurr: 'Usuario', 
  tympole: 'Usuario', 
  palpitoad: 'Usuario', 
  seismitoad: 'Usuario', 
  sawk: 'Usuario', 
  swadloon: 'Usuario', 
  leavanny: 'Usuario', 
  venipede: 'Usuario', 
  whirlipede: 'Usuario', 
  scolipede: 'Usuario', 
  cottonee: 'Usuario', 
  whimsicott: 'Usuario', 
  petilil: 'Usuario', 
  lilligant: 'Usuario', 
  basculin: 'Usuario', 
  sandile: 'Usuario', 
  krokorok: 'Usuario', 
  krookodile: 'Usuario', 
  darumaka: 'Usuario', 
  darmanitan: 'Usuario', 
  maractus: 'Usuario', 
  dwebble: 'Usuario', 
  crustle: 'Usuario', 
  scraggy: 'Usuario', 
  scrafty: 'Usuario', 
  sigilyph: 'Usuario', 
  cofagrigus: 'Usuario', 
  tirtouga: 'Usuario', 
  trubbish: 'Usuario', 
  garbodor: 'Usuario', 
  zorua: 'Usuario', 
  zoroark: 'Usuario', 
  minccino: 'Usuario', 
  cinccino: 'Usuario', 
  gothita: 'Usuario', 
  gothorita: 'Usuario', 
  gothitelle: 'Usuario', 
  duosion: 'Usuario', 
  reuniclus: 'Usuario', 
  vanillite: 'Usuario', 
  vanillish: 'Usuario', 
  vanilluxe: 'Usuario', 
  deerling: 'Usuario', 
  sawsbuck: 'Usuario', 
  karrablast: 'Usuario', 
  escavalier: 'Usuario', 
  foongus: 'Usuario', 
  amoonguss: 'Usuario', 
  frillish: 'Usuario', 
  jellicent: 'Usuario', 
  joltik: 'Usuario', 
  galvantula: 'Usuario', 
  ferroseed: 'Usuario', 
  ferrothorn: 'Usuario', 
  klink: 'Usuario',
  klang: "IgnacioCZ",
  klinklang: "IgnacioCZ",
  tynamo: 'Usuario', 
  eelektrik: 'Usuario', 
  eelektross: 'Usuario', 
  elgyem: 'Usuario', 
  beheeyem: 'Usuario', 
  litwick: 'Usuario', 
  lampent: 'Usuario', 
  chandelure: 'Usuario', 
  axew: 'Usuario', 
  fraxure: 'Usuario', 
  haxorus: 'Usuario', 
  cubchoo: 'Usuario', 
  beartic: 'Usuario', 
  cryogonal: 'Usuario', 
  shelmet: 'Usuario', 
  accelgor: 'Usuario', 
  stunfisk: 'Usuario', 
  mienfoo: 'Usuario', 
  mienshao: 'Usuario', 
  druddigon: 'Usuario', 
  golett: 'Usuario', 
  golurk: 'Usuario', 
  pawniard: 'Usuario', 
  bisharp: 'Usuario', 
  bouffalant: 'Usuario', 
  rufflet: 'Usuario', 
  braviary: 'Usuario', 
  vullaby: 'Usuario', 
  heatmor: 'Usuario', 
  durant: 'Usuario', 
  deino: 'Usuario', 
  zweilous: 'Usuario', 
  hydreigon: 'Usuario', 
  larvesta: 'Usuario', 
  volcarona: 'Usuario', 



  
};
 
